import React from 'react';
import { Document, Image, Page, StyleSheet, Text, View } from '@react-pdf/renderer';

const P = '#4b126f', INK = '#251936', GOLD = '#f4bd18', MUTED = '#667085';
const styles = StyleSheet.create({
  page:{paddingTop:38,paddingBottom:48,paddingHorizontal:40,fontFamily:'Helvetica',fontSize:10,color:INK,backgroundColor:'#fbf9fc'},
  cover:{padding:0,backgroundColor:P}, hero:{height:515,position:'relative'}, image:{width:'100%',height:'100%',objectFit:'cover',opacity:.68}, overlay:{position:'absolute',top:0,right:0,bottom:0,left:0,backgroundColor:'#1d092b',opacity:.55}, coverCopy:{position:'absolute',left:40,right:40,bottom:42,color:'#fff'}, brand:{color:GOLD,fontFamily:'Helvetica-Bold',fontSize:11,letterSpacing:1.7,marginBottom:22}, kickerLight:{color:'#f9e6a6',fontSize:8.5,letterSpacing:1.2,marginBottom:8}, coverTitle:{fontFamily:'Helvetica-Bold',fontSize:34,lineHeight:1.07,maxWidth:430}, coverSub:{color:'#f0e8f3',fontSize:11,lineHeight:1.5,marginTop:12,maxWidth:410}, chips:{flexDirection:'row',flexWrap:'wrap',marginTop:17}, chip:{borderColor:'#fff',borderWidth:1,borderRadius:14,paddingVertical:6,paddingHorizontal:10,marginRight:7,marginBottom:7,fontSize:8.7}, coverFoot:{paddingHorizontal:40,paddingVertical:18,backgroundColor:'#3b0e5a'}, coverFootText:{color:'#eee6f3',lineHeight:1.55,fontSize:9.5},
  kicker:{color:P,fontFamily:'Helvetica-Bold',fontSize:8,letterSpacing:1.2,marginBottom:6}, title:{color:P,fontFamily:'Helvetica-Bold',fontSize:23,lineHeight:1.14,marginBottom:11}, body:{color:'#3f4651',fontSize:10.1,lineHeight:1.65}, sub:{color:INK,fontFamily:'Helvetica-Bold',fontSize:12,marginBottom:7}, divider:{height:1,backgroundColor:'#e8e0eb',marginVertical:17},
  stats:{flexDirection:'row',flexWrap:'wrap',borderWidth:1,borderColor:'#e8deed',borderRadius:13,backgroundColor:'#fff',paddingVertical:6,marginTop:16}, stat:{width:'33.33%',paddingVertical:9,paddingHorizontal:12}, statLabel:{color:MUTED,fontSize:7.5,marginBottom:3,letterSpacing:.35}, statValue:{color:INK,fontFamily:'Helvetica-Bold',fontSize:9.5,lineHeight:1.3},
  highlightGrid:{flexDirection:'row',flexWrap:'wrap',marginTop:12,marginHorizontal:-4}, highlight:{width:'50%',padding:4}, highlightBox:{minHeight:64,borderRadius:10,backgroundColor:'#f2eafa',padding:10}, highlightNo:{color:P,fontFamily:'Helvetica-Bold',fontSize:8,marginBottom:4}, highlightText:{color:INK,fontFamily:'Helvetica-Bold',fontSize:9.4,lineHeight:1.4},
  map:{width:'100%',height:195,objectFit:'cover',borderRadius:12,marginTop:13}, card:{borderWidth:1,borderColor:'#eadff0',borderRadius:12,backgroundColor:'#fff',padding:13,marginTop:13}, route:{flexDirection:'row',alignItems:'center',marginBottom:8}, dot:{width:10,height:10,borderRadius:5,backgroundColor:GOLD,marginRight:8}, routeText:{color:'#424854',fontSize:9.5,flex:1},
  day:{flexDirection:'row',borderBottomColor:'#e6dfea',borderBottomWidth:1,paddingBottom:13,marginBottom:13}, dayBadge:{width:42,height:42,borderRadius:21,backgroundColor:P,color:'#fff',fontFamily:'Helvetica-Bold',fontSize:8,paddingTop:11,textAlign:'center',marginRight:12}, dayContent:{flex:1}, dayTitle:{color:INK,fontFamily:'Helvetica-Bold',fontSize:12.3,lineHeight:1.3,marginBottom:5}, bullet:{flexDirection:'row',marginBottom:4}, bulletMark:{color:GOLD,fontFamily:'Helvetica-Bold',width:12}, bulletText:{color:'#4a505b',fontSize:9.3,lineHeight:1.42,flex:1},
  callout:{marginTop:17,backgroundColor:'#fff7da',borderLeftColor:GOLD,borderLeftWidth:4,padding:12}, calloutTitle:{color:'#684500',fontFamily:'Helvetica-Bold',fontSize:10,marginBottom:4}, calloutText:{color:'#5c4a23',fontSize:9.3,lineHeight:1.48},
  cols:{flexDirection:'row',marginHorizontal:-5}, col:{width:'50%',paddingHorizontal:5}, listCard:{borderRadius:12,padding:13,minHeight:190,borderWidth:1}, yes:{borderColor:'#d7eadd',backgroundColor:'#f4fbf6'}, no:{borderColor:'#f0dfdb',backgroundColor:'#fff8f6'}, cardTitle:{fontFamily:'Helvetica-Bold',fontSize:12.3,marginBottom:9}, info:{borderRadius:12,borderColor:'#e4d9ea',borderWidth:1,backgroundColor:'#fff',padding:14,marginTop:12},
  priceBox:{borderRadius:14,backgroundColor:P,padding:19,color:'#fff'}, priceTag:{color:'#eedff5',fontSize:8,letterSpacing:1.1,marginBottom:5}, price:{color:GOLD,fontFamily:'Helvetica-Bold',fontSize:25}, oldPrice:{color:'#ebdff0',fontSize:10,marginTop:4}, priceCopy:{color:'#f1e8f4',fontSize:9.6,lineHeight:1.5,marginTop:10}, checkRow:{flexDirection:'row',marginBottom:7}, check:{color:'#147044',fontFamily:'Helvetica-Bold',width:14}, checkText:{color:'#444b55',fontSize:9.4,lineHeight:1.42,flex:1}, note:{flexDirection:'row',backgroundColor:'#fff',borderColor:'#e8e0eb',borderWidth:1,borderRadius:10,padding:11,marginBottom:8}, noteNo:{width:25,color:P,fontFamily:'Helvetica-Bold',fontSize:8.5,paddingTop:1}, noteText:{color:'#4b515b',fontSize:9.2,lineHeight:1.45,flex:1},
  closing:{borderRadius:15,backgroundColor:P,padding:23,color:'#fff'}, closingKicker:{color:GOLD,fontSize:8,fontFamily:'Helvetica-Bold',letterSpacing:1.1,marginBottom:7}, closingTitle:{fontFamily:'Helvetica-Bold',fontSize:21,marginBottom:8}, closingText:{color:'#f0e7f4',fontSize:10,lineHeight:1.58}, contact:{color:GOLD,fontFamily:'Helvetica-Bold',fontSize:13,marginTop:15}, footer:{position:'absolute',left:40,right:40,bottom:20,flexDirection:'row',justifyContent:'space-between',color:MUTED,fontSize:7.7},
});
const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
const list=v=>Array.isArray(v)?v.map(clean).filter(Boolean):[];
const money=v=>Number.isFinite(Number(v))?`₹${new Intl.NumberFormat('en-IN').format(Number(v))}`:'On request';
const copy=(v,fallback)=>clean(v)||fallback;
const cloudImage=v=>{try{const u=new URL(clean(v));return u.protocol==='https:'&&u.hostname==='res.cloudinary.com'?u.toString():null;}catch{return null;}};
function Footer({trip}){return <View style={styles.footer} fixed><Text>TravelEnfield · {clean(trip.title)}</Text><Text render={({pageNumber,totalPages})=>`${pageNumber} / ${totalPages}`}/></View>;}
function Header({kicker,title}){return <><Text style={styles.kicker}>{kicker}</Text><Text style={styles.title}>{title}</Text></>;}
function Bullets({items,excluded=false}){return items.map((item,i)=><View style={styles.bullet} key={`${item}-${i}`}><Text style={[styles.bulletMark,excluded?{color:'#c75443'}:null]}>•</Text><Text style={styles.bulletText}>{item}</Text></View>);}

export default function TripItineraryPdf({trip,destination}){
  const itinerary=Array.isArray(trip.itinerary)?trip.itinerary.filter(day=>clean(day?.title)||list(day?.details).length):[];
  const highlights=list(trip.itineraryPdfHighlights).length?list(trip.itineraryPdfHighlights).slice(0,8):[...itinerary.map(day=>clean(day.title)),...list(trip.inclusions)].filter(Boolean).slice(0,6);
  const inclusions=list(trip.inclusions), exclusions=list(trip.exclusions), notes=list(trip.notes);
  const intro=copy(trip.itineraryPdfIntro,copy(trip.summary,`A thoughtfully designed ${clean(trip.duration)||'group'} journey with TravelEnfield.`));
  const destinationIntro=copy(destination?.overview,copy(destination?.summary,`Explore ${clean(destination?.name||trip.destinationSlug||trip.title)} at a considered pace, with time for landscapes, local culture and shared moments.`));
  const arrival=copy(trip.itineraryPdfArrivalNote,`Please plan to reach ${clean(trip.pickup)||'the reporting point'} with enough buffer. Final reporting time and departure instructions are shared before the trip.`);
  const stay=copy(trip.itineraryPdfStayNote,'Accommodation is arranged on the booked sharing basis. Local transfers and stays follow the route and experiences listed in this itinerary.');
  const booking=copy(trip.itineraryPdfBookingNote,'Share your preferred dates and traveller count with our trip experts to check live availability and secure your place.');
  const cancellation=copy(trip.itineraryPdfCancellationNote,'Cancellation, rescheduling and refund eligibility depend on the trip type, departure date and notice period. Please review the current TravelEnfield policy before confirming your booking.');
  const routeStops=itinerary.map(day=>clean(day.title)).filter(Boolean).slice(0,6);
  const routeImage=cloudImage(trip.itineraryPdfMap)||cloudImage(trip.itineraryImage)||cloudImage(trip.image);
  return <Document title={`${clean(trip.title)} itinerary`} author="TravelEnfield" subject="Travel itinerary">
    <Page size="A4" style={styles.cover}><View style={styles.hero}>{cloudImage(trip.image)?<Image src={cloudImage(trip.image)} style={styles.image}/>:null}<View style={styles.overlay}/><View style={styles.coverCopy}><Text style={styles.brand}>TRAVELENFIELD</Text><Text style={styles.kickerLight}>CURATED GROUP JOURNEY</Text><Text style={styles.coverTitle}>{clean(trip.title)||'Your next journey'}</Text><Text style={styles.coverSub}>{clean(trip.badge)||'A thoughtfully paced journey with stays, transfers and on-ground support.'}</Text><View style={styles.chips}>{clean(trip.duration)?<Text style={styles.chip}>{clean(trip.duration)}</Text>:null}{clean(trip.groupSize)?<Text style={styles.chip}>{clean(trip.groupSize)}</Text>:null}{clean(trip.pickup)?<Text style={styles.chip}>Starts at {clean(trip.pickup)}</Text>:null}</View></View></View><View style={styles.coverFoot}><Text style={styles.coverFootText}>Your day-by-day guide to the route, included experiences and practical details. Final timings may adapt to local weather, road conditions and safety requirements.</Text></View></Page>
    <Page size="A4" style={styles.page}><Header kicker="YOUR TRIP IN BRIEF" title="A journey made to be remembered."/><Text style={styles.body}>{intro}</Text><View style={styles.stats}>{[['DURATION',clean(trip.duration)||'As selected'],['GROUP SIZE',clean(trip.groupSize)||'Small group'],['STARTING FROM',`${money(trip.price)} / person`],['PICKUP',clean(trip.pickup)||'On confirmation'],['TRIP STYLE',clean(trip.badge)||'Group departure'],['TRIP SUPPORT','TravelEnfield trip captain']].map(([label,value])=><View style={styles.stat} key={label}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>)}</View><View style={styles.divider}/><Text style={styles.sub}>The experiences that shape this trip</Text><View style={styles.highlightGrid}>{highlights.map((item,i)=><View style={styles.highlight} key={`${item}-${i}`}><View style={styles.highlightBox}><Text style={styles.highlightNo}>0{i+1}</Text><Text style={styles.highlightText}>{item}</Text></View></View>)}</View><Footer trip={trip}/></Page>
    <Page size="A4" style={styles.page}><Header kicker="ABOUT THE DESTINATION" title={clean(destination?.name||trip.destinationSlug||trip.title)}/><Text style={styles.body}>{destinationIntro}</Text>{routeImage?<Image src={routeImage} style={styles.map}/>:null}<View style={styles.card}><Text style={styles.sub}>Your route at a glance</Text>{routeStops.length?routeStops.map((stop,i)=><View style={styles.route} key={`${stop}-${i}`}><View style={styles.dot}/><Text style={styles.routeText}>{stop}</Text></View>):<Text style={styles.body}>Your route, stays and activity sequence are planned around the final confirmed departure.</Text>}</View><View style={styles.callout}><Text style={styles.calloutTitle}>Arrival & departure planning</Text><Text style={styles.calloutText}>{arrival}</Text></View><Footer trip={trip}/></Page>
    <Page size="A4" style={styles.page}><Header kicker="DAY-BY-DAY PLAN" title="Itinerary breakdown"/>{itinerary.length?itinerary.map((day,i)=><View style={styles.day} key={`${day.day}-${i}`} wrap={false}><Text style={styles.dayBadge}>DAY {clean(day.day)||i+1}</Text><View style={styles.dayContent}><Text style={styles.dayTitle}>{clean(day.title)||`Day ${i+1}`}</Text><Bullets items={list(day.details)}/></View></View>):<Text style={styles.body}>Your detailed day-wise itinerary will be shared after the departure is confirmed.</Text>}<View style={styles.callout}><Text style={styles.calloutTitle}>Good to know</Text><Text style={styles.calloutText}>The order of sightseeing, stays or driving time can change when local conditions require it. Your trip captain will always prioritise comfort, safety and the best possible on-ground experience.</Text></View><Footer trip={trip}/></Page>
    <Page size="A4" style={styles.page}><Header kicker="WHAT YOUR TRIP COVERS" title="Inclusions & travel setup"/><View style={styles.cols}><View style={styles.col}><View style={[styles.listCard,styles.yes]}><Text style={[styles.cardTitle,{color:'#147044'}]}>Included</Text><Bullets items={inclusions.length?inclusions:['Your confirmed inclusion list will be shared by the trip expert.']}/></View></View><View style={styles.col}><View style={[styles.listCard,styles.no]}><Text style={[styles.cardTitle,{color:'#a63c2d'}]}>Not included</Text><Bullets excluded items={exclusions.length?exclusions:['Personal expenses and anything not listed under inclusions.']}/></View></View></View><View style={styles.info}><Text style={styles.sub}>Stay, transfers & on-ground support</Text><Text style={styles.body}>{stay}</Text></View><View style={styles.info}><Text style={styles.sub}>What to carry</Text><Bullets items={['A valid government photo ID and any destination-specific documents.','Comfortable footwear, weather-appropriate layers and a reusable water bottle.','Personal medication, charging essentials and a small daypack for transfers or walks.']}/></View><Footer trip={trip}/></Page>
    <Page size="A4" style={styles.page}><Header kicker="PRICING & BOOKING" title="Clear next steps, before you go."/><View style={styles.priceBox}><Text style={styles.priceTag}>TRIP STARTS FROM</Text><Text style={styles.price}>{money(trip.price)} / person</Text>{Number(trip.oldPrice)>Number(trip.price)?<Text style={styles.oldPrice}>Regular price {money(trip.oldPrice)} {clean(trip.discount)?`· ${clean(trip.discount)}`:''}</Text>:null}<Text style={styles.priceCopy}>Final pricing depends on the selected departure, room-sharing preference and any optional upgrades confirmed by the trip expert.</Text></View><View style={styles.info}><Text style={styles.sub}>How to book</Text>{['Send an enquiry with your preferred date and traveller count.','Receive live availability, room-sharing choices and the final trip quote.','Confirm the booking through the secure payment instructions shared by the TravelEnfield team.'].map((text,i)=><View style={styles.checkRow} key={text}><Text style={styles.check}>{i+1}.</Text><Text style={styles.checkText}>{text}</Text></View>)}</View><View style={styles.callout}><Text style={styles.calloutTitle}>Booking & payment note</Text><Text style={styles.calloutText}>{booking}</Text></View><View style={styles.info}><Text style={styles.sub}>Cancellation & rescheduling</Text><Text style={styles.body}>{cancellation}</Text></View><Footer trip={trip}/></Page>
    <Page size="A4" style={styles.page}><Header kicker="IMPORTANT TRAVEL NOTES" title="Travel well. Travel responsibly."/>{notes.length?notes.map((note,i)=><View style={styles.note} key={`${note}-${i}`}><Text style={styles.noteNo}>{String(i+1).padStart(2,'0')}</Text><Text style={styles.noteText}>{note}</Text></View>):<Text style={styles.body}>Please follow the final joining instructions and the guidance of your trip captain throughout the journey.</Text>}<View style={styles.divider}/><Text style={styles.sub}>Health, safety & conduct</Text><Bullets items={['Follow the trip captain’s safety guidance during transfers, hikes and activities.','Share relevant medical conditions with the team before departure and carry your prescribed medication.','Treat local communities, stays and natural spaces with care. Unsafe or disruptive behaviour may affect participation.']}/><Footer trip={trip}/></Page>
    <Page size="A4" style={styles.page}><View style={styles.closing}><Text style={styles.closingKicker}>YOUR NEXT STORY STARTS HERE</Text><Text style={styles.closingTitle}>Ready to travel with us?</Text><Text style={styles.closingText}>{booking}</Text><Text style={styles.contact}>Enquire at TravelEnfield</Text></View><View style={{marginTop:26}}><Text style={styles.title}>A final word</Text><Text style={styles.body}>This itinerary is designed as a useful planning guide. The final confirmed schedule, inclusions and operational details shared by the TravelEnfield team take priority. Thank you for choosing a journey that leaves room for the road, the people and the unexpected moments in between.</Text></View><Footer trip={trip}/></Page>
  </Document>;
}
