import './enquiry-popup.js';
import { createIcons, ArrowRight, Armchair, Baby, BadgeCheck, Backpack, Bath, Bed, BedDouble, Bike, BookOpen, CalendarClock, CalendarDays, CarFront, Check, ChevronDown, ChevronRight, CircleCheckBig, Clock3, Coffee, ConciergeBell, CookingPot, DoorOpen, Droplets, Dumbbell, Flame, Gift, Hotel, IndianRupee, KeyRound, Luggage, Mail, Map, MapPin, MapPinned, Maximize, Menu, MessageCircle, Mountain, MountainSnow, Phone, Plane, Refrigerator, Search, Send, ShieldCheck, Ship, SlidersHorizontal, Snowflake, Sparkles, Star, Tags, Tent, ThumbsUp, Trees, Tv, Users, UtensilsCrossed, WandSparkles, Waves, Wifi, Wind, X } from 'lucide';

const iconSet = { ArrowRight, Armchair, Baby, BadgeCheck, Backpack, Bath, Bed, BedDouble, Bike, BookOpen, CalendarClock, CalendarDays, CarFront, Check, ChevronDown, ChevronRight, CircleCheckBig, Clock3, Coffee, ConciergeBell, CookingPot, DoorOpen, Droplets, Dumbbell, Flame, Gift, Hotel, IndianRupee, KeyRound, Luggage, Mail, Map, MapPin, MapPinned, Maximize, Menu, MessageCircle, Mountain, MountainSnow, Phone, Plane, Refrigerator, Search, Send, ShieldCheck, Ship, SlidersHorizontal, Snowflake, Sparkles, Star, Tags, Tent, ThumbsUp, Trees, Tv, Users, UtensilsCrossed, WandSparkles, Waves, Wifi, Wind, X };
const mount = document.querySelector('#page-content');
document.querySelectorAll('.logo-img, .logo-img-mobile, .mobile-nav-logo').forEach(img => { img.src = '/images/brand/logo-navbar.png'; });
const footerLogo = document.querySelector('.app-footer img'); if (footerLogo) footerLogo.src = '/images/brand/logo-footer.png';
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
const icon = (name, cls = '') => `<i data-lucide="${name}" class="${cls}"></i>`;
const readJsonResponse = async response => {
  const text = await response.text();
  if (!text.trim()) throw new Error(response.ok ? 'The server returned an empty response. Please refresh and try again.' : `Server request failed (${response.status}).`);
  try { return JSON.parse(text); } catch { throw new Error('The server returned an invalid response. Please restart the API server and try again.'); }
};
const api = async path => { const response = await fetch(`/api${path}`, { headers: { Accept: 'application/json' } }); const result = await readJsonResponse(response); if (!response.ok) throw new Error(result?.error || `Unable to load this page (${response.status})`); return result; };
const setMeta = (title, description) => { document.title = `${title} | TravelEnfield`; document.querySelector('meta[name="description"]')?.setAttribute('content', description || 'Explore curated trips with TravelEnfield.'); };
const activateIcons = () => createIcons({ icons: iconSet });

// Central Tailwind layer for HTML generated by the route renderer. Semantic
// class names remain as stable JS hooks; visual styling comes from utilities.
const tailwindMap = {
  '.page-hero': 'relative isolate min-h-[440px] overflow-hidden bg-brand-deep text-white',
  '.page-hero>img': 'absolute inset-0 size-full object-cover',
  '.page-hero-content': 'relative z-10 flex min-h-[440px] flex-col justify-end py-14',
  '.page-hero h1': 'max-w-4xl font-heading text-[clamp(2.5rem,6vw,5.5rem)] font-extrabold leading-[.95] tracking-tight',
  '.page-hero p': 'mt-4 max-w-2xl text-base leading-relaxed text-white/80',
  '.breadcrumbs': 'mb-auto flex flex-wrap items-center gap-2 text-xs text-white/70',
  '.page-eyebrow': 'mb-3 text-xs font-extrabold uppercase tracking-[.14em] text-brand-yellow',
  '.page-shell,.content-section,.custom-planner,.custom-how': 'py-12 md:py-16',
  '.category-intro': 'py-10 md:py-12',
  '.category-results': 'pb-14 pt-2 md:pb-18 md:pt-4',
  '.cards-grid': 'grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-3',
  '.listing-card': 'overflow-hidden rounded-2xl border border-brand-purple/10 bg-white shadow-lg transition hover:-translate-y-1 hover:shadow-xl',
  '.listing-card-media': 'relative block aspect-[1.45] overflow-hidden',
  '.listing-card-media img': 'size-full object-cover transition duration-500 hover:scale-105',
  '.listing-card-body': 'p-5',
  '.listing-card-body h2': 'my-2 font-heading text-xl font-extrabold text-brand-deep',
  '.listing-card-body p': 'text-sm leading-relaxed text-gray-500',
  '.card-meta,.price-row': 'flex flex-wrap items-center justify-between gap-2 text-xs text-gray-500',
  '.price-row': 'mt-5 border-t border-brand-purple/10 pt-4',
  '.card-link': 'inline-flex items-center gap-1 font-extrabold text-brand-purple',
  '.filter-bar': 'mb-7 grid grid-cols-1 gap-3 rounded-2xl border border-brand-purple/10 bg-white p-4 shadow-sm sm:grid-cols-[1fr_240px_auto]',
  '.filter-bar input,.filter-bar select,.category-filter-card input,.category-filter-card select': 'min-h-12 w-full rounded-xl border border-brand-purple/15 bg-brand-surface px-4 outline-none focus:border-brand-purple focus:ring-4 focus:ring-brand-purple/10',
  '.category-tabs': 'mt-6 flex gap-2 overflow-x-auto pb-2',
  '.category-tabs button': 'min-h-11 shrink-0 rounded-full border border-brand-purple/15 bg-white px-5 font-bold text-brand-ink',
  '.category-tabs button.active': 'border-brand-purple bg-brand-purple text-white',
  '.category-results-layout': 'grid grid-cols-[280px_minmax(0,1fr)] items-start gap-7 max-lg:grid-cols-1',
  '.category-filter-card': 'sticky top-36 rounded-2xl border border-brand-purple/10 bg-white p-5 shadow-lg max-lg:relative max-lg:top-auto',
  '.category-trip-list': 'grid gap-4',
  '.category-trip-card': 'grid grid-cols-[260px_minmax(0,1fr)] overflow-hidden rounded-2xl border border-brand-purple/10 bg-white shadow-md max-md:grid-cols-1',
  '.category-trip-media': 'relative min-h-[220px] overflow-hidden',
  '.category-trip-media img': 'absolute inset-0 size-full object-cover',
  '.category-trip-body': 'p-5',
  '.category-trip-body h2': 'my-2 font-heading text-xl font-extrabold text-brand-deep',
  '.category-trip-body p': 'text-sm leading-relaxed text-gray-500',
  '.category-trip-meta': 'flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-gray-500',
  '.category-trip-meta span,.category-trip-dates': 'inline-flex items-center gap-2',
  '.category-trip-meta svg,.category-trip-dates svg': 'size-4 shrink-0 text-brand-purple',
  '.category-trip-dates': 'mt-4 text-xs text-gray-500',
  '.category-trip-price': 'mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-brand-purple/10 pt-4 text-sm text-gray-500',
  '.category-trip-price strong': 'font-heading text-xl font-extrabold text-brand-purple',
  '.category-trip-price del': 'ml-2 text-xs',
  '.category-trip-price a': 'inline-flex min-h-11 items-center gap-1 font-extrabold text-brand-purple',
  '.category-trip-media>span,.card-badge': 'absolute left-3 top-3 z-10 rounded-full bg-brand-purple px-3 py-2 text-xs font-extrabold text-white shadow-lg',
  '.category-list-head': 'mb-4 flex flex-wrap items-end justify-between gap-3',
  '.category-list-head h2': 'font-heading text-2xl font-extrabold text-brand-deep',
  '.category-list-head>span': 'rounded-full bg-green-50 px-3 py-2 text-xs font-bold text-green-700',
  '.filter-title': 'mb-5 flex items-center gap-2 font-heading text-lg text-brand-deep',
  '.filter-title button': 'ml-auto min-h-10 rounded-lg px-2 text-xs font-bold text-brand-purple',
  '.category-filter-card>label': 'mb-4 grid gap-2 text-xs font-bold text-brand-ink',
  '.category-filter-card details': 'border-t border-brand-purple/10 py-4 text-sm text-gray-500',
  '.category-filter-card summary': 'cursor-pointer font-bold text-brand-ink',
  '.content-grid': 'grid grid-cols-[minmax(0,1fr)_340px] items-start gap-8 max-lg:grid-cols-1',
  '.prose': 'mx-auto w-full max-w-4xl text-gray-600 [&_h2]:mb-3 [&_h2]:mt-9 [&_h2]:font-heading [&_h2]:text-2xl [&_h2]:font-extrabold [&_h2]:text-brand-deep [&_p]:leading-7 [&_li]:my-2',
  '.faq-list': 'grid gap-3',
  '.faq-item': 'overflow-hidden rounded-2xl border border-brand-purple/10 bg-white shadow-sm transition',
  '.faq-item.open': 'border-brand-purple/30 shadow-lg',
  '.faq-question': 'min-h-20 w-full cursor-pointer px-5 py-4 font-heading font-bold text-brand-ink',
  '.faq-toggle': 'grid size-9 shrink-0 place-items-center rounded-full bg-brand-purple/10 text-brand-purple',
  '.faq-item.open .faq-toggle': 'bg-brand-yellow text-brand-deep',
  '.faq-answer p': 'px-5 pb-5 text-sm leading-relaxed text-gray-500',
  '.side-card,.trip-enquiry-card,.form-card,.custom-form-wrap': 'rounded-2xl border border-brand-purple/10 bg-white p-6 shadow-xl',
  '.form-grid': 'grid grid-cols-2 gap-4 max-sm:grid-cols-1',
  '.field': 'grid gap-1.5',
  '.field.full': 'col-span-full',
  '.field label,.trip-mini-form label,.departure-form label': 'grid gap-1.5 text-xs font-bold text-brand-ink',
  '.field input,.field select,.field textarea,.trip-mini-form input,.departure-form input': 'min-h-12 w-full rounded-xl border border-brand-purple/15 bg-brand-surface px-4 text-base outline-none focus:border-brand-purple focus:ring-4 focus:ring-brand-purple/10',
  '.trip-detail-layout': 'grid grid-cols-[minmax(0,1fr)_390px] items-start gap-8 max-xl:grid-cols-[minmax(0,1fr)_350px] max-lg:grid-cols-1',
  '.trip-detail-hero': 'relative isolate min-h-[620px] overflow-hidden bg-brand-deep text-white',
  '.trip-detail-bg,.trip-detail-scrim': 'absolute inset-0 size-full',
  '.trip-detail-bg': 'object-cover',
  '.trip-detail-hero-copy': 'relative z-10 flex min-h-[620px] flex-col justify-end py-16 text-center',
  '.trip-detail-hero-copy h1': 'mx-auto max-w-4xl font-heading text-[clamp(2.7rem,6vw,5.8rem)] font-extrabold leading-[.95]',
  '.trip-detail-hero-copy p': 'mx-auto mt-4 max-w-2xl text-white/80',
  '.trip-hero-chips': 'mx-auto mt-6 flex flex-wrap justify-center gap-2',
  '.trip-hero-chips span': 'inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-bold backdrop-blur',
  '.trip-enquiry-sticky': 'sticky top-32 max-lg:relative max-lg:top-auto',
  '.trip-story,.trip-roadmap,.trip-package,.trip-dates,.trip-notes': 'scroll-mt-32 py-12',
  '.trip-facts,.trip-package-grid,.trip-date-grid,.custom-benefits': 'grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3',
  '.package-panel,.trip-facts article,.trip-date-grid>button,.custom-benefits article': 'rounded-2xl border border-brand-purple/10 bg-white p-5 shadow-sm',
  '.roadmap-stop': 'relative grid grid-cols-[1fr_70px_1fr] items-center gap-5 py-8 max-md:grid-cols-[54px_1fr]',
  '.roadmap-media': 'overflow-hidden rounded-2xl shadow-lg max-md:hidden',
  '.roadmap-media img': 'aspect-[1.35] size-full object-cover',
  '.roadmap-copy': 'rounded-2xl border border-brand-purple/10 bg-white p-5 shadow-sm',
  '.detail-tabs': 'sticky top-0 z-30 border-b border-brand-purple/10 bg-white/95 backdrop-blur',
  '.trip-progress': 'flex min-h-16 items-center justify-between gap-4',
  '.trip-progress-links': 'flex gap-2 overflow-x-auto',
  '.trip-progress-links a': 'shrink-0 rounded-full bg-brand-surface px-4 py-2 text-sm font-bold',
  '.trip-progress-links a.active': 'bg-brand-purple text-white',
  '.custom-planner-grid': 'grid grid-cols-[.9fr_1.1fr] items-start gap-10 max-lg:grid-cols-1',
  '.planner-steps': 'my-7 grid gap-4',
  '.planner-steps>div': 'flex gap-4 rounded-2xl border border-brand-purple/10 bg-white p-4',
  '.article-layout': 'mx-auto max-w-4xl',
  '.empty-state': 'rounded-2xl border border-dashed border-brand-purple/25 bg-brand-surface p-10 text-center'
  ,  '.hotel-search-inline': 'mt-7 w-full rounded-3xl border border-white/20 bg-white p-3 shadow-[0_24px_50px_rgba(10,2,16,.35)] sm:p-4',
  '.hotel-search-fields': 'grid gap-3 sm:grid-cols-[1.2fr_1fr_1fr_1fr_auto] sm:items-end',
  '.hotel-search-fields label': 'grid gap-1.5 text-xs font-bold text-gray-700',
  '.hotel-search-fields input,.hotel-search-fields select': 'min-h-12 w-full rounded-xl border border-brand-purple/15 bg-brand-surface px-3.5 text-sm outline-none transition focus:border-brand-purple focus:ring-4 focus:ring-brand-purple/10',
  '.hotel-search-fields .btn': 'min-h-12 w-full rounded-xl px-6 sm:w-auto',
  '.hotel-trust-row': 'mx-auto mt-6 flex max-w-4xl flex-wrap items-center justify-center gap-x-7 gap-y-2',
  '.hotel-trust-row span': 'inline-flex items-center gap-2 text-xs font-bold text-gray-600',
  '.hotel-trust-row svg': 'size-4 text-brand-purple',
  '.hotel-card': 'group min-w-0 overflow-hidden rounded-2xl border border-brand-purple/10 bg-white shadow-lg transition hover:-translate-y-1 hover:shadow-xl',
  '.hotel-card-media': 'relative block aspect-[1.4] overflow-hidden',
  '.hotel-card-media img': 'size-full object-cover transition duration-500 group-hover:scale-105',
  '.hotel-card-badge': 'absolute left-3 top-3 z-10 rounded-full bg-brand-purple px-3 py-1.5 text-[11px] font-extrabold text-white shadow-lg',
  '.hotel-rating-badge': 'absolute right-3 top-3 z-10 inline-flex items-center gap-1 rounded-lg bg-white/95 px-2.5 py-1.5 text-xs font-extrabold text-brand-deep shadow-lg',
  '.hotel-card-body': 'min-w-0 p-5',
  '.hotel-card-stars': 'flex gap-0.5',
  '.hotel-card-stars svg': 'size-4 fill-brand-yellow text-brand-yellow',
  '.hotel-card-stars .hotel-star-empty svg': 'fill-brand-purple/10 text-brand-purple/20',
  '.hotel-hero-pills': 'mt-6 flex flex-wrap gap-2',
  '.hotel-hero-pills span': 'inline-flex items-center gap-2 rounded-full border border-white/25 bg-black/20 px-4 py-2 text-sm font-bold backdrop-blur-md',
  '.hotel-hero-pills svg': 'size-4 text-brand-yellow',
  '.hotel-card-location': 'mt-2 flex items-center gap-1.5 text-xs text-gray-500',
  '.hotel-card-location svg': 'size-3.5 text-brand-purple',
  '.hotel-card-name': 'my-2 font-heading text-xl font-extrabold text-brand-deep',
  '.hotel-card-desc': 'text-sm leading-relaxed text-gray-500',
  '.hotel-amenity-chips': 'mt-4 flex flex-wrap gap-1.5',
  '.hotel-amenity-chips span': 'inline-flex items-center gap-1 rounded-full bg-brand-surface px-2.5 py-1.5 text-[11px] font-bold text-brand-ink',
  '.hotel-amenity-chips svg': 'size-3.5 text-brand-purple',
  '.hotel-card-price': 'mt-4 flex flex-wrap items-end justify-between gap-2 border-t border-brand-purple/10 pt-4',
  '.hotel-card-price small': 'block text-[11px] text-gray-400',
  '.hotel-card-price strong': 'font-heading text-2xl font-extrabold text-brand-deep',
  '.hotel-card-price del': 'ml-1.5 text-xs text-gray-400',
  '.hotel-card-cta': 'inline-flex items-center gap-1.5 rounded-full bg-brand-yellow px-4 py-2 text-xs font-extrabold text-brand-deep shadow transition hover:-translate-y-0.5',
  '.hotel-card-cta svg': 'size-4',
  '.hotel-gallery-grid': 'grid grid-cols-2 auto-rows-[140px] gap-3 md:grid-cols-4 md:auto-rows-[160px]',
  '.hotel-gallery-item': 'relative overflow-hidden rounded-2xl',
  '.hotel-gallery-item img': 'size-full object-cover transition duration-500 hover:scale-105',
  '.hotel-gallery-item:first-child': 'col-span-2 row-span-2',
  '.hotel-facts-row': 'grid gap-3 sm:grid-cols-2 lg:grid-cols-5',
  '.hotel-fact': 'grid justify-items-center gap-1 rounded-2xl border border-brand-purple/10 bg-white p-5 text-center shadow-sm',
  '.hotel-fact svg': 'size-6 text-brand-purple',
  '.hotel-fact small': 'text-xs text-gray-500',
  '.hotel-fact strong': 'text-center text-sm',
  '.hotel-amenities-grid': 'grid gap-3 sm:grid-cols-2 lg:grid-cols-3',
  '.hotel-amenity-item': 'flex items-center gap-3 rounded-2xl border border-brand-purple/10 bg-white p-4',
  '.hotel-amenity-item svg': 'size-5 shrink-0 text-brand-purple',
  '.hotel-amenity-item span': 'text-sm font-bold text-brand-ink',
  '.hotel-room-card': 'grid min-w-0 gap-5 rounded-2xl border border-brand-purple/10 bg-white p-5 shadow-sm lg:grid-cols-[240px_minmax(0,1fr)_170px] lg:items-center',
  '.hotel-room-card>img': 'aspect-[1.4] w-full rounded-xl object-cover lg:aspect-auto lg:h-40',
  '.hotel-room-body h3': 'font-heading text-lg font-extrabold text-brand-deep',
  '.hotel-room-body>p': 'mt-1 text-xs text-gray-500',
  '.hotel-room-meta': 'mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-gray-600',
  '.hotel-room-meta span': 'inline-flex items-center gap-1.5',
  '.hotel-room-meta svg': 'size-4 text-brand-purple',
  '.hotel-room-perks': 'mt-3 flex flex-wrap gap-1.5',
  '.hotel-room-perks span': 'inline-flex items-center gap-1 rounded-full bg-lime-50 px-2.5 py-1 text-[11px] font-bold text-lime-700',
  '.hotel-room-perks svg': 'size-3.5',
  '.hotel-room-price small': 'block text-[11px] text-gray-400',
  '.hotel-room-price strong': 'font-heading text-2xl font-extrabold text-brand-purple',
  '.hotel-room-price del': 'ml-1.5 text-xs text-gray-400',
  '.hotel-room-price .btn': 'mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-full bg-brand-yellow px-5 text-xs font-extrabold text-brand-deep transition hover:-translate-y-0.5 hover:shadow-lg',
  '.hotel-room-price .btn svg': 'size-4',
  '.hotel-booking-card': 'min-w-0 overflow-hidden rounded-[26px] border border-brand-purple/10 bg-white p-6 shadow-[0_24px_60px_rgba(69,13,105,.14)]',
  '.hotel-booking-form': 'grid gap-3',
  '.hotel-booking-form label': 'grid gap-1.5 text-xs font-bold text-gray-800',
  '.hotel-booking-form input,.hotel-booking-form select': 'min-h-12 min-w-0 w-full rounded-xl border border-brand-purple/15 bg-[#fcfbfd] px-3 text-sm outline-none transition focus:border-brand-purple focus:ring-4 focus:ring-brand-purple/10',
  '.hotel-booking-row': 'grid min-w-0 grid-cols-2 gap-2',
  '.hotel-review-bars': 'grid gap-2',
  '.hotel-review-bar': 'grid grid-cols-[46px_minmax(0,1fr)_34px] items-center gap-2 text-xs text-gray-500',
  '.hotel-review-bar .hotel-review-track': 'h-2 overflow-hidden rounded-full bg-gray-100',
  '.hotel-review-bar .hotel-review-track>span': 'block h-full rounded-full bg-brand-yellow',
  '.hotel-nearby-list': 'grid gap-3',
  '.hotel-nearby-list li': 'flex items-center gap-3 rounded-2xl border border-brand-purple/10 bg-white p-4 text-sm text-gray-600',
  '.hotel-nearby-list svg': 'size-5 shrink-0 text-brand-purple',
  '.hotel-section': 'scroll-mt-28 py-12',
  '.hotel-detail-shell': 'bg-[radial-gradient(circle_at_10%_5%,#f5ecf9,transparent_28%),#fcfbfd] py-12 lg:py-16',
  '.hotel-detail-layout': 'grid min-w-0 items-start gap-10 lg:grid-cols-[minmax(0,1fr)_360px]',
  '.hotel-detail-main': 'min-w-0',
  '.hotel-booking-sticky': 'order-first min-w-0 lg:order-none lg:sticky lg:top-24',
  '.departure-modal': 'fixed inset-0 z-[120] grid place-items-center p-4',
  '.departure-backdrop': 'absolute inset-0 border-0 bg-brand-ink/70 backdrop-blur-sm',
  '.departure-dialog': 'relative z-10 w-[min(100%,480px)] rounded-3xl bg-white p-7 shadow-2xl',
  '.departure-close': 'absolute right-3 top-3 grid size-11 place-items-center rounded-full border border-brand-purple/10 bg-white text-brand-purple',
  '.departure-kicker': 'inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-wider text-brand-purple',
  '.departure-dialog h2': 'mb-2 mt-3 font-heading text-2xl font-extrabold text-brand-deep',
  '.departure-dialog>p': 'mb-5 text-sm leading-relaxed text-gray-500',
  '.departure-form': 'grid gap-3',
  '.departure-safe': 'mt-4 flex items-center justify-center gap-2 text-xs text-gray-500'
};
function applyTailwindStyles(root = document) {
  for (const [selector, classes] of Object.entries(tailwindMap)) {
    root.querySelectorAll(selector).forEach(element => element.classList.add(...classes.split(' ')));
  }
}

const dropdowns = [...document.querySelectorAll('.nav-dropdown')];
dropdowns.forEach(item => item.querySelector('.nav-dropdown-toggle')?.addEventListener('click', event => { const open=!item.classList.contains('open'); dropdowns.forEach(x=>{x.classList.remove('open');x.querySelector('button')?.setAttribute('aria-expanded','false')}); if(open){item.classList.add('open');event.currentTarget.setAttribute('aria-expanded','true')}}));
document.addEventListener('click', event => { if(!event.target.closest('.nav-dropdown')) dropdowns.forEach(x=>{x.classList.remove('open');x.querySelector('button')?.setAttribute('aria-expanded','false')}); });
const mobileNav=document.querySelector('#mobile-nav'), mobileOverlay=document.querySelector('#mobile-nav-overlay');
if(mobileOverlay&&mobileNav)document.body.append(mobileOverlay,mobileNav);
const drawerTriggers=[...document.querySelectorAll('[data-drawer-trigger]')];
const mobileDropdowns=[...document.querySelectorAll('.mobile-nav-dropdown')];
let mobileNavReturnFocus = null;
const setMobileNav=open=>{mobileNav?.classList.toggle('open',open);mobileOverlay?.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);mobileNav?.setAttribute('aria-hidden',String(!open));document.querySelector('#hamburger')?.setAttribute('aria-expanded',String(open));drawerTriggers.forEach(trigger=>trigger.setAttribute('aria-expanded',String(open)));if(open){mobileNavReturnFocus=document.activeElement;document.querySelector('#mobile-nav-close')?.focus()}else{mobileDropdowns.forEach(d=>{d.classList.remove('open');d.querySelector('.mobile-dropdown-toggle')?.setAttribute('aria-expanded','false')});if(mobileNavReturnFocus instanceof HTMLElement)mobileNavReturnFocus.focus()}};
document.querySelector('#hamburger')?.addEventListener('click',()=>setMobileNav(true));document.querySelector('#mobile-nav-close')?.addEventListener('click',()=>setMobileNav(false));mobileOverlay?.addEventListener('click',()=>setMobileNav(false));
drawerTriggers.forEach(trigger=>trigger.addEventListener('click',()=>setMobileNav(true)));
document.querySelectorAll('.mobile-nav-link',mobileNav).forEach(link=>{if(!link.classList.contains('mobile-dropdown-toggle'))link.addEventListener('click',()=>setMobileNav(false))});
mobileDropdowns.forEach(dropdown=>{const toggle=dropdown.querySelector('.mobile-dropdown-toggle');toggle?.addEventListener('click',()=>{const wasOpen=dropdown.classList.contains('open');mobileDropdowns.forEach(d=>{d.classList.remove('open');d.querySelector('.mobile-dropdown-toggle')?.setAttribute('aria-expanded','false')});if(!wasOpen){dropdown.classList.add('open');toggle.setAttribute('aria-expanded','true')}})});
document.addEventListener('keydown', event => { if(event.key==='Escape'){setMobileNav(false);dropdowns.forEach(x=>{x.classList.remove('open');x.querySelector('button')?.setAttribute('aria-expanded','false')})} });

function hero({ title, description, image = '/images/hero.jpg', eyebrow = 'TravelEnfield', crumbs = [] }) {
  return `<section class="page-hero"><img src="${esc(image)}" alt="" /><div class="page-hero-content container"><div class="breadcrumbs"><a href="/">Home</a>${crumbs.map(c=>`<span>/</span><a href="${c.href}">${esc(c.label)}</a>`).join('')}</div><div class="page-eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div></section>`;
}
function tripCard(trip) {
  return `<article class="listing-card" data-search="${esc(`${trip.title} ${trip.destinationSlug}`.toLowerCase())}" data-price="${trip.price}" data-duration="${trip.nights}"><a class="listing-card-media" href="/trips/${esc(trip.slug)}"><img src="${esc(trip.image)}" alt="${esc(trip.title)}" loading="lazy" /><span class="card-badge">${esc(trip.badge || 'Group Trip')}</span></a><div class="listing-card-body"><div class="card-meta"><span>${icon('clock-3')} ${esc(trip.duration)}</span><span>${icon('users')} ${esc(trip.groupSize || 'Group')}</span></div><h2><a href="/trips/${esc(trip.slug)}">${esc(trip.title)}</a></h2><p>${esc(trip.summary)}</p><div class="price-row"><del>${money(trip.oldPrice)}</del><strong>${money(trip.price)}</strong><a class="card-link" href="/trips/${esc(trip.slug)}" aria-label="View ${esc(trip.title)}">View ${icon('chevron-right')}</a></div></div></article>`;
}
function categoryTripCard(trip) { return `<article class="category-trip-card" data-search="${esc(`${trip.title} ${trip.destinationSlug}`.toLowerCase())}" data-price="${trip.price}" data-duration="${trip.nights}"><a href="/trips/${esc(trip.slug)}" class="category-trip-media"><img src="${esc(trip.image)}" alt="${esc(trip.title)}" loading="lazy"><span>${esc(trip.badge||'Group trip')}</span></a><div class="category-trip-body"><div class="category-trip-meta"><span>${icon('clock-3')} ${esc(trip.duration)}</span><span>${icon('users')} ${esc(trip.groupSize)}</span></div><h2><a href="/trips/${esc(trip.slug)}">${esc(trip.title)}</a></h2><p>${esc(trip.summary)}</p><div class="category-trip-dates">${icon('calendar-days')} ${esc((trip.dates||[]).slice(0,3).join(' · '))}</div><div class="category-trip-price"><span>From <strong>${money(trip.price)}</strong> <del>${money(trip.oldPrice)}</del></span><a href="/trips/${esc(trip.slug)}">View trip ${icon('chevron-right')}</a></div></div></article>`; }
function destinationCard(item) {
  return `<article class="listing-card" data-search="${esc(item.name.toLowerCase())}"><a class="listing-card-media" href="/destinations/${esc(item.slug)}"><img src="${esc(item.image)}" alt="${esc(item.name)}" loading="lazy" /></a><div class="listing-card-body"><div class="card-meta"><span>${icon('map-pin')} ${esc(item.category)}</span><span>${esc(item.bestTime)}</span></div><h2><a href="/destinations/${esc(item.slug)}">${esc(item.name)}</a></h2><p>${esc(item.tagline)}</p><div class="price-row"><span>From</span><strong>${money(item.startingPrice)}</strong><a class="card-link" href="/destinations/${esc(item.slug)}">Explore ${icon('chevron-right')}</a></div></div></article>`;
}
function filterBar(showSort = true) {
  return `<div class="filter-bar"><label class="sr-only" for="page-search">Search</label><input id="page-search" type="search" placeholder="Search trips or destinations…" />${showSort ? '<select id="page-sort" aria-label="Sort results"><option value="featured">Recommended</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="short">Shortest first</option></select>' : ''}<span class="result-count" id="result-count"></span></div>`;
}
function wireFilters() {
  const input = document.querySelector('#page-search'); const sort = document.querySelector('#page-sort'); const grid = document.querySelector('.cards-grid'); if (!grid) return;
  const cards = [...grid.children];
  const update = () => { const query = input?.value.trim().toLowerCase() || ''; cards.forEach(card => card.hidden = !card.dataset.search.includes(query)); const visible = cards.filter(c=>!c.hidden); document.querySelector('#result-count').textContent = `${visible.length} results`; if (sort) { const key=sort.value; visible.sort((a,b)=> key==='low'?a.dataset.price-b.dataset.price:key==='high'?b.dataset.price-a.dataset.price:key==='short'?a.dataset.duration-b.dataset.duration:0).forEach(card=>grid.append(card)); } };
  input?.addEventListener('input', update); sort?.addEventListener('change', update); update();
}

async function renderListing(slug) {
  const map = { 'trips':'all','upcoming-trips':'upcoming','domestic-trips':'domestic','international-trips':'international','weekend-trips':'weekend','deals':'all','bike-trips':'bike-trips','backpacking-trips':'backpacking-trips','trekking-trips':'trekking-trips' };
  const tripCategory = map[slug];
  const [category, loadedTrips] = await Promise.all([
    api(`/categories/${slug}`).catch(() => ({ name:'Trips', title:'Explore all trips', description:'Compare curated domestic and international journeys.' })),
    api(`/trips${tripCategory && tripCategory !== 'all' ? `?category=${encodeURIComponent(tripCategory)}` : ''}`),
  ]);
  let trips = loadedTrips || []; if(slug==='deals') trips=trips.filter(t=>t.discount);
  const destinationTabs=[...new Set(trips.map(t=>t.destinationSlug).filter(Boolean))];
  setMeta(category.title, category.description); mount.innerHTML = hero({title:category.title,description:category.description,image:category.image||'/images/hero.jpg',eyebrow:category.eyebrow||'Curated departures'})+`<section class="category-intro"><div class="container"><span class="page-eyebrow">Curated by TravelEnfield</span><h2>Explore ${esc(category.name||'our trips')}</h2><p>${esc(category.description)}</p><div class="category-tabs"><button class="active" data-category-tab="all">All trips</button>${destinationTabs.map(x=>`<button data-category-tab="${esc(x)}">${esc(x.replaceAll('-',' '))}</button>`).join('')}</div></div></section><section class="category-results"><div class="container category-results-layout"><aside class="category-filter-card"><div class="filter-title">${icon('sliders-horizontal')} <strong>Filters</strong><button type="button" id="clear-filters">Clear</button></div><label>Search trips<input id="page-search" type="search" placeholder="Destination or trip name"></label><label>Sort by<select id="page-sort"><option value="featured">Recommended</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="short">Shortest first</option></select></label><details open><summary>Trip type</summary><p>Small-group departures with a trained trip captain.</p></details><details><summary>Budget</summary><p>Transparent per-person prices are shown on every card.</p></details><a href="/custom-trip" class="btn btn-primary btn-block">Need a custom trip?</a></aside><div class="category-list-wrap"><div class="category-list-head"><div><span id="result-count"></span><h2>Trips ready for you</h2></div><span>Verified departures</span></div><div class="category-trip-list">${trips.length?trips.map(categoryTripCard).join(''):'<div class="empty-state"><h2>New departures coming soon</h2><p>Plan private dates with our trip team.</p><a class="btn btn-primary" href="/custom-trip">Plan a custom trip</a></div>'}</div></div></div></section>`; wireFilters();
  document.querySelectorAll('[data-category-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-category-tab]').forEach(x=>x.classList.remove('active'));button.classList.add('active');const key=button.dataset.categoryTab;document.querySelector('#page-search').value=key==='all'?'':key.replaceAll('-',' ');document.querySelector('#page-search').dispatchEvent(new Event('input'))}));
  document.querySelector('#clear-filters')?.addEventListener('click',()=>{document.querySelector('#page-search').value='';document.querySelector('#page-sort').value='featured';document.querySelector('#page-search').dispatchEvent(new Event('input'))});
}

async function renderDestination(slug) {
  const [item,trips] = await Promise.all([api(`/destinations/${slug}`),api(`/trips?destination=${slug}`)]); setMeta(`${item.name} Tour Packages`,item.summary);
  mount.innerHTML=hero({title:`${item.name} Tour Packages`,description:item.tagline,image:item.image,eyebrow:`From ${money(item.startingPrice)}`,crumbs:[{href:'/trips',label:'Destinations'}]})+`<section class="content-section"><div class="container content-grid"><article class="prose"><h2>About ${esc(item.name)}</h2><p>${esc(item.summary)}</p><h2>Top highlights</h2><ul>${item.highlights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Things to do</h2><ul>${item.thingsToDo.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Best time to visit</h2><p>${esc(item.bestTime)}</p><h2>Travel essentials</h2><ul>${item.travelTips.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><aside class="side-card"><h3>Plan ${esc(item.name)}</h3><span class="trip-price-big">${money(item.startingPrice)}</span><p>Custom dates, stays and experiences for your group.</p><a class="btn btn-primary btn-block" href="/custom-trip?destination=${esc(item.slug)}">Plan a custom trip</a></aside></div></section><section class="content-section alt"><div class="container"><h2 class="section-title">Available ${esc(item.name)} trips</h2><div class="cards-grid">${trips.length?trips.map(tripCard).join(''):'<div class="empty-state"><p>New departures are being planned. Send us an enquiry for private dates.</p></div>'}</div></div></section><section class="content-section"><div class="container"><h2 class="section-title">Frequently asked questions</h2><div class="faq-list max-w-4xl">${item.faq.map((x,i)=>`<div class="faq-item${i===0?' open':''}"><button class="faq-question" type="button" aria-expanded="${i===0}"><span>${esc(x.question)}</span><span class="faq-toggle" aria-hidden="true">+</span></button><div class="faq-answer"><p>${esc(x.answer)}</p></div></div>`).join('')}</div></div></section>`;applyTailwindStyles(mount);activateIcons();wireFaq();
}

function amenityIcon(amenity) {
  const a = String(amenity || '').toLowerCase();
  if (a.includes('wifi')) return 'wifi';
  if (a.includes('breakfast')) return 'coffee';
  if (a.includes('restaurant') || a.includes('dining') || a.includes('caf') || a.includes('kitchen')) return 'utensils-crossed';
  if (a.includes('gym')) return 'dumbbell';
  if (a.includes('pool')) return 'waves';
  if (a.includes('spa') || a.includes('oxygen') || a.includes('wellness')) return 'wind';
  if (a.includes('parking')) return 'car-front';
  if (a.includes('airport') || a.includes('transfer')) return 'plane';
  if (a.includes('heating') || a.includes('heater')) return 'snowflake';
  if (a.includes('hot water') || a.includes('toiletries') || a.includes('bath')) return 'droplets';
  if (a.includes('bonfire') || a.includes('fireplace')) return 'flame';
  if (a.includes('balcony') || a.includes('sit-out')) return 'door-open';
  if (a.includes('mini bar') || a.includes('minibar') || a.includes('fridge')) return 'refrigerator';
  if (a.includes('yoga')) return 'sparkles';
  if (a.includes('shuttle')) return 'car-front';
  if (a.includes('bicycle') || a.includes('bike hire')) return 'bike';
  if (a.includes('kayak') || a.includes('boat') || a.includes('water')) return 'ship';
  if (a.includes('family') || a.includes('kids')) return 'baby';
  if (a.includes('garden')) return 'trees';
  if (a.includes('mountain') || a.includes('view') || a.includes('trek') || a.includes('walk')) return 'mountain';
  return 'sparkles';
}
function starRow(hotel, cls = 'hotel-card-stars') {
  const filled = Math.min(5, Math.max(1, Math.round(hotel.star || 4)));
  return `<span class="${cls}" role="img" aria-label="${hotel.star} star hotel">${Array.from({ length: filled }, () => icon('star')).join('')}${Array.from({ length: 5 - filled }, () => `<span class="hotel-star-empty">${icon('star')}</span>`).join('')}</span>`;
}
function hotelCard(hotel) {
  return `<article class="hotel-card" data-search="${esc(`${hotel.name} ${hotel.location} ${hotel.area || ''} ${hotel.destinationSlug}`.toLowerCase())}" data-price="${hotel.pricePerNight}" data-rating="${hotel.rating}" data-stars="${hotel.star}" data-destination="${esc(hotel.destinationSlug)}"><a class="hotel-card-media" href="/hotels/${esc(hotel.slug)}"><img src="${esc(hotel.image)}" alt="${esc(hotel.name)}" loading="lazy" /><span class="hotel-card-badge">${esc(hotel.badge || 'Handpicked Stay')}</span><span class="hotel-rating-badge">${icon('star')} ${esc(hotel.rating)}</span></a><div class="hotel-card-body">${starRow(hotel)}<p class="hotel-card-location">${icon('map-pin')} ${esc(hotel.location)}</p><h2 class="hotel-card-name"><a href="/hotels/${esc(hotel.slug)}">${esc(hotel.name)}</a></h2><p class="hotel-card-desc">${esc(hotel.tagline)}</p><div class="hotel-amenity-chips">${(hotel.amenities || []).slice(0, 3).map(a => `<span>${icon(amenityIcon(a))} ${esc(a)}</span>`).join('')}</div><div class="hotel-card-price"><div><small>${esc(hotel.roomType || 'Room')} · per night</small><strong>${money(hotel.pricePerNight)}</strong><del>${money(hotel.oldPricePerNight)}</del></div><a class="hotel-card-cta" href="/hotels/${esc(hotel.slug)}">View stay ${icon('arrow-right')}</a></div></div></article>`;
}
function hotelRoomCard(hotel, room) {
  return `<article class="hotel-room-card"><img src="${esc(hotel.image)}" alt="${esc(room.name)}" loading="lazy" /><div class="hotel-room-body"><h3>${esc(room.name)}</h3><p>${esc(room.view || 'Comfortable stay')}</p><div class="hotel-room-meta"><span>${icon('bed')} ${esc(room.bed)}</span><span>${icon('users')} ${esc(room.occupancy)}</span><span>${icon('maximize')} ${esc(room.size)}</span></div><div class="hotel-room-perks">${(room.perks || []).map(p => `<span>${icon('check')} ${esc(p)}</span>`).join('')}</div></div><div class="hotel-room-price"><small>${esc(room.name)} · per night</small><strong>${money(room.price)}</strong><del>${money(room.oldPrice)}</del><button type="button" data-room="${esc(room.name)}" data-price="${room.price}">${icon('calendar-clock')} Reserve this room</button></div></article>`;
}
function ratingDistribution(rating) {
  const five = Math.min(92, Math.round(30 + (rating - 3.5) * 55));
  const four = Math.min(40, Math.max(4, Math.round((5 - rating) * 18)));
  const three = Math.max(1, Math.round((5 - rating) * 4));
  const two = Math.max(0, Math.round((5 - rating) * 2));
  const one = Math.max(0, 100 - five - four - three - two);
  return [['5', five], ['4', four], ['3', three], ['2', two], ['1', one]];
}
const isoDate = d => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

async function renderHotels() {
  const [stays, dests] = await Promise.all([api('/hotels'), api('/destinations')]);
  const tabs = [...new Set(stays.map(h => h.destinationSlug))];
  const destNames = Object.fromEntries((dests || []).map(d => [d.slug, d.name]));
  const label = slug => (destNames[slug] || slug || '').replaceAll('-', ' ');
  setMeta('Hotels & Handpicked Stays', 'Verified partner hotels across India and beyond with transparent per-night rates, free cancellation and real guest ratings.');
  const today = new Date(); const later = new Date(); later.setDate(later.getDate() + 2);
  mount.innerHTML = `<section class="page-hero"><img src="/images/social-banner.jpg" alt="" /><div class="page-hero-content container"><div class="breadcrumbs"><a href="/">Home</a></div><div class="page-eyebrow">Verified partner stays</div><h1>Stay somewhere you will love</h1><p>Handpicked hotels near our group-trip routes, with clear per-night pricing, free cancellation and real guest ratings.</p><form class="hotel-search-fields hotel-search-inline" id="hotel-search"><label>Where to<span class="sr-only"> destination</span><select id="hotel-destination"><option value="all">Anywhere</option>${tabs.map(x => `<option value="${esc(x)}">${esc(label(x))}</option>`).join('')}</select></label><label>Check-in<input type="date" id="hotel-checkin" value="${isoDate(today)}"></label><label>Check-out<input type="date" id="hotel-checkout" value="${isoDate(later)}"></label><label>Guests<select id="hotel-guests">${[1, 2, 3, 4, 5, 6].map(g => `<option>${g} ${g === 1 ? 'guest' : 'guests'}</option>`).join('')}</select></label><button class="btn btn-primary" type="submit">${icon('search')} Search stays</button></form></div></section>`
    + `<section class="category-results"><div class="container"><div class="category-intro"><div class="destination-heading"><div><span class="section-kicker">Curated by TravelEnfield</span><h2 class="section-title">${stays.length} stays ready for you</h2><p>Every stay is verified, guest-rated and free to cancel.</p></div></div><div class="category-tabs"><button class="active" data-hotel-tab="all">All stays</button>${tabs.map(x => `<button data-hotel-tab="${esc(x)}">${esc(label(x))}</button>`).join('')}</div></div><div class="filter-bar"><label class="sr-only" for="hotel-search-input">Search hotels</label><input id="hotel-search-input" type="search" placeholder="Search hotels, cities or destinations…" /><select id="hotel-sort" aria-label="Sort stays"><option value="featured">Recommended</option><option value="priceLow">Price: low to high</option><option value="priceHigh">Price: high to low</option><option value="rating">Top rated</option><option value="stars">Star rating</option></select><span class="result-count" id="hotel-result-count"></span></div><div class="cards-grid" id="hotel-grid">${stays.length ? stays.map(hotelCard).join('') : '<div class="empty-state"><h2>More stays coming soon</h2><p>Tell us where you are headed and we will find a verified stay for you.</p><a class="btn btn-primary" href="/custom-trip">Plan a custom trip</a></div>'}</div><div class="hotel-trust-row"><span>${icon('shield-check')} No prepayment to reserve</span><span>${icon('calendar-clock')} Free cancellation on most stays</span><span>${icon('thumbs-up')} Verified guest ratings</span><span>${icon('badge-check')} Best-price promise</span></div></div></section>`;
  applyTailwindStyles(mount); activateIcons();
  const input = document.querySelector('#hotel-search-input');
  const sort = document.querySelector('#hotel-sort');
  const grid = document.querySelector('#hotel-grid');
  const count = document.querySelector('#hotel-result-count');
  const cards = [...grid.children];
  let activeTab = 'all';
  const update = () => {
    const query = input?.value.trim().toLowerCase() || '';
    let visible = cards.filter(card => (activeTab === 'all' || card.dataset.destination === activeTab) && card.dataset.search.includes(query));
    if (sort) {
      const key = sort.value;
      visible.sort((a, b) => key === 'priceLow' ? a.dataset.price - b.dataset.price : key === 'priceHigh' ? b.dataset.price - a.dataset.price : key === 'rating' ? b.dataset.rating - a.dataset.rating : key === 'stars' ? b.dataset.stars - a.dataset.stars : 0);
    }
    visible.forEach(card => grid.append(card));
    cards.forEach(card => card.hidden = !visible.includes(card));
    if (count) count.textContent = `${visible.length} stays`;
  };
  input?.addEventListener('input', update);
  sort?.addEventListener('change', update);
  document.querySelectorAll('[data-hotel-tab]').forEach(button => button.addEventListener('click', () => {
    document.querySelectorAll('[data-hotel-tab]').forEach(x => x.classList.remove('active'));
    button.classList.add('active');
    activeTab = button.dataset.hotelTab;
    update();
  }));
  const form = document.querySelector('#hotel-search');
  form?.addEventListener('submit', event => {
    event.preventDefault();
    const destination = document.querySelector('#hotel-destination')?.value || 'all';
    document.querySelectorAll('[data-hotel-tab]').forEach(x => x.classList.toggle('active', x.dataset.hotelTab === destination));
    activeTab = destination;
    if (input) input.value = '';
    update();
    grid.scrollIntoView({ behavior: 'smooth', block: 'start' });
  });
  update();
}

function wireHotelBooking(hotel) {
  const form = document.querySelector('#hotel-booking-form'); if (!form) return;
  const today = new Date(); const later = new Date(); later.setDate(later.getDate() + 2);
  const checkin = form.querySelector('#book-checkin'); if (checkin && !checkin.value) checkin.value = isoDate(today);
  const checkout = form.querySelector('#book-checkout'); if (checkout && !checkout.value) checkout.value = isoDate(later);
  document.querySelectorAll('[data-room]').forEach(button => button.addEventListener('click', () => {
    const room = form.querySelector('#book-room');
    if (room) room.value = button.dataset.room;
    const price = form.querySelector('#book-price');
    if (price) price.textContent = money(Number(button.dataset.price));
    document.querySelector('.hotel-booking-sticky')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  }));
  form.addEventListener('submit', async event => {
    event.preventDefault();
    const submit = form.querySelector('button[type=submit]');
    const status = form.querySelector('.form-status');
    submit.disabled = true; status.textContent = 'Reserving your stay…';
    try {
      const body = { ...Object.fromEntries(new FormData(form)), type: 'hotel-detail', destination: hotel.name, travellers: Number(form.querySelector('#book-guests')?.value || 1) };
      const response = await fetch('/api/enquiries', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      if (!response.ok) throw new Error();
      status.className = 'form-status success'; status.textContent = 'Stay request received. Our hotel expert will call you shortly.'; form.reset();
      const checkin2 = form.querySelector('#book-checkin'); if (checkin2) checkin2.value = isoDate(new Date());
      const checkout2 = form.querySelector('#book-checkout'); if (checkout2) checkout2.value = isoDate(new Date(Date.now() + 2 * 86400000));
    } catch {
      status.className = 'form-status error'; status.textContent = 'Could not save right now. Please try again.';
    } finally {
      submit.disabled = false;
    }
  });
}

function wireFaq(root = mount) {
  root.querySelectorAll('.faq-item').forEach((item, index) => {
    const question = item.querySelector('.faq-question');
    const answer = item.querySelector('.faq-answer');
    if (!question || !answer) return;
    const answerId = `faq-answer-${index + 1}`;
    answer.id = answerId;
    question.setAttribute('aria-controls', answerId);
    question.addEventListener('click', () => {
      const willOpen = !item.classList.contains('open');
      root.querySelectorAll('.faq-item.open').forEach(openItem => {
        if (openItem !== item) {
          openItem.classList.remove('open');
          openItem.querySelector('.faq-question')?.setAttribute('aria-expanded', 'false');
        }
      });
      item.classList.toggle('open', willOpen);
      question.setAttribute('aria-expanded', String(willOpen));
    });
  });
}

async function renderHotel(slug) {
  const hotel = await api(`/hotels/${slug}`);
  setMeta(`${hotel.name} · ${hotel.location}`, hotel.summary);
  const gallery = hotel.gallery || [hotel.image];
  const thumbs = [gallery[1] || hotel.image, gallery[2] || hotel.image, gallery[3] || hotel.image, gallery[4] || hotel.image];
  const facts = [
    { icon: 'star', label: 'Star rating', value: `${hotel.star} Star` },
    { icon: 'thumbs-up', label: 'Guest rating', value: `${hotel.rating} / 5` },
    { icon: 'calendar-clock', label: 'Check-in', value: hotel.policies?.checkIn || '14:00' },
    { icon: 'key-round', label: 'Check-out', value: hotel.policies?.checkOut || '12:00' },
    { icon: 'map-pin', label: 'Location', value: hotel.location || hotel.area || 'City centre' },
  ];
  mount.innerHTML = `<section class="page-hero"><img src="${esc(hotel.image)}" alt="${esc(hotel.name)}" /><div class="page-hero-content container"><div class="breadcrumbs"><a href="/">Home</a><span>/</span><a href="/hotels">Hotels</a><span>/</span><span>${esc(hotel.name)}</span></div><div class="page-eyebrow">${esc(hotel.star)}-star stay · ${esc(hotel.location)}</div><h1>${esc(hotel.name)}</h1><p>${esc(hotel.tagline)}</p><div class="hotel-hero-pills"><span>${icon('star')} ${esc(hotel.rating)} · ${esc(hotel.reviews)} verified reviews</span><span>${icon('calendar-clock')} Check-in ${esc(hotel.policies?.checkIn || '14:00')}</span><span>${icon('key-round')} Check-out ${esc(hotel.policies?.checkOut || '12:00')}</span></div></div></section>`
    + `<section class="hotel-detail-shell"><div class="container hotel-detail-layout"><main class="hotel-detail-main">
      <section class="hotel-section" id="overview"><div class="hotel-gallery-grid"><div class="hotel-gallery-item"><img src="${esc(gallery[0] || hotel.image)}" alt="${esc(hotel.name)} main view" /></div>${thumbs.map((src, i) => `<div class="hotel-gallery-item"><img src="${esc(src)}" alt="${esc(hotel.name)} view ${i + 2}" loading="lazy" /></div>`).join('')}</div>
      <div class="hotel-facts-row">${facts.map(f => `<article class="hotel-fact">${icon(f.icon)}<small>${esc(f.label)}</small><strong>${esc(f.value)}</strong></article>`).join('')}</div>
      <div class="trip-section-heading" style="margin-top:3rem"><span class="page-eyebrow">THE STAY</span><h2>${esc(hotel.name)} at a glance</h2><p>${esc(hotel.summary)}</p></div>
      <div class="hotel-amenities-grid">${hotel.amenities.map(a => `<div class="hotel-amenity-item">${icon(amenityIcon(a))}<span>${esc(a)}</span></div>`).join('')}</div></section>
      <section class="hotel-section" id="rooms"><div class="trip-section-heading"><span class="page-eyebrow">ROOMS & RATES</span><h2>Choose your room</h2><p>Clear rates with breakfast, cancellation and view details on every card.</p></div><div class="hotel-room-list" style="display:grid;gap:1rem">${hotel.rooms.map(room => hotelRoomCard(hotel, room)).join('')}</div></section>
      <section class="hotel-section" id="location"><div class="trip-section-heading"><span class="page-eyebrow">LOCATION</span><h2>Where you will stay</h2><p>Easy to reach, close to the places you came to see.</p></div><ul class="hotel-nearby-list">${(hotel.nearby || []).map(x => `<li>${icon('map-pin')} ${esc(x)}</li>`).join('')}</ul><div class="hotel-highlight-note" style="margin-top:1rem"><div class="hotel-amenity-item">${icon('badge-check')}<span>${esc(hotel.area || `${hotel.name} is walkable to local markets and key landmarks.`)}</span></div></div></section>
      <section class="hotel-section" id="reviews"><div class="trip-section-heading"><span class="page-eyebrow">GUEST REVIEWS</span><h2>What guests say</h2><p>Rated ${esc(hotel.rating)} / 5 by ${esc(hotel.reviews)} verified guests.</p></div><div class="side-card"><div class="hotel-review-summary" style="display:flex;align-items:center;gap:1rem;margin-bottom:1.25rem"><strong style="font-size:2.75rem;font-weight:800;color:var(--brand-deep, #450d69)">${esc(hotel.rating)}</strong><div>${starRow(hotel, 'hotel-card-stars')}<p style="margin-top:.25rem;font-size:.8rem;color:#6b7280">${esc(hotel.reviews)} verified reviews</p></div></div><div class="hotel-review-bars">${ratingDistribution(hotel.rating).map(([star, pct]) => `<div class="hotel-review-bar"><span>${star}★</span><div class="hotel-review-track"><span style="width:${pct}%"></span></div><span>${pct}%</span></div>`).join('')}</div></div></section>
      <section class="hotel-section" id="faq"><div class="trip-section-heading"><span class="page-eyebrow">GOOD TO KNOW</span><h2>Frequently asked questions</h2></div><div class="content-grid"><div class="faq-list">${(hotel.faq || []).map((x, i) => `<div class="faq-item${i === 0 ? ' open' : ''}"><button class="faq-question" type="button" aria-expanded="${i === 0}"><span>${esc(x.question)}</span><span class="faq-toggle" aria-hidden="true">+</span></button><div class="faq-answer"><p>${esc(x.answer)}</p></div></div>`).join('')}</div><aside class="side-card"><h3>Pair this stay with a trip</h3><p>Add ${esc(hotel.name)} to a group trip or private itinerary across ${esc(hotel.location.split(',')[0] || hotel.location)}.</p><a class="btn btn-primary btn-block" href="/custom-trip?destination=${esc(hotel.destinationSlug)}&hotel=${esc(hotel.slug)}">${icon('sparkles')} Plan around this stay</a></aside></div></section>
    </main><aside class="hotel-booking-sticky"><div class="hotel-booking-card"><span class="enquiry-trust">${icon('shield-check')} Verified stay · Free cancellation</span><p class="trip-from">Rooms from</p><div class="trip-enquiry-price"><strong id="book-price">${money(hotel.rooms?.[0]?.price || hotel.pricePerNight)}</strong><del>${money(hotel.rooms?.[0]?.oldPrice || hotel.oldPricePerNight)}</del></div><p class="trip-saving">${esc(hotel.badge || 'Handpicked partner stay')} · per night</p><form id="hotel-booking-form" class="hotel-booking-form"><label>Check-in<input name="checkIn" id="book-checkin" type="date" required /></label><label>Check-out<input name="checkOut" id="book-checkout" type="date" required /></label><div class="hotel-booking-row"><label>Guests<select name="guests" id="book-guests">${[1, 2, 3, 4, 5, 6].map(g => `<option>${g}</option>`).join('')}</select></label><label>Room<select name="roomType" id="book-room">${hotel.rooms.map(r => `<option>${esc(r.name)}</option>`).join('')}</select></label></div><label>Full name<input name="name" required autocomplete="name" placeholder="Your name" /></label><label>Phone number<input name="phone" required type="tel" autocomplete="tel" placeholder="+91 98765 43210" /></label><label>Email<input name="email" required type="email" autocomplete="email" placeholder="you@email.com" /></label><button class="btn btn-primary btn-block" type="submit">${icon('calendar-clock')} Reserve this stay</button><p class="form-status" role="status"></p></form><div class="enquiry-assurance"><span>${icon('phone')} Callback in 15 mins</span><span>${icon('shield-check')} No prepayment</span><span>${icon('calendar-clock')} Free cancellation</span></div></div></aside></div></section>`;
  applyTailwindStyles(mount); activateIcons();
  wireHotelBooking(hotel);
  wireFaq();
}

async function renderTrip(slug) {
  const trip=await api(`/trips/${slug}`); setMeta(trip.title,trip.summary);
  const itinerary=(trip.itinerary||[]);
  const tripImage=trip.image||'/assets/images/hero.jpg';
  mount.innerHTML=`<section class="trip-detail-hero">
    <img class="trip-detail-bg" src="${esc(tripImage)}" alt="${esc(trip.title)}" />
    <div class="trip-detail-scrim"></div>
    <figure class="trip-float trip-float-left"><img src="${esc(tripImage)}" alt="Scenic view from ${esc(trip.title)}" /></figure>
    <figure class="trip-float trip-float-right"><img src="${esc(tripImage)}" alt="Travel experience in ${esc(trip.title)}" /></figure>
    <div class="container trip-detail-hero-copy">
      <div class="breadcrumbs"><a href="/">Home</a><span>/</span><a href="/trips">Trips</a><span>/</span><span>${esc(trip.title)}</span></div>
      <span class="trip-detail-kicker">${icon('circle-check-big')} ${esc(trip.badge||'Curated group trip')}</span>
      <h1>${esc(trip.title)}</h1><p>${esc(trip.summary)}</p>
      <div class="trip-hero-chips"><span>${icon('clock-3')} ${esc(trip.duration)}</span><span>${icon('users')} ${esc(trip.groupSize)}</span><span>${icon('map-pin')} ${esc(trip.pickup)}</span></div>
    </div>
  </section>
  <nav class="detail-tabs trip-tabs" aria-label="Trip sections"><div class="container trip-progress"><div class="trip-progress-links"><a href="#overview" data-step="overview">Overview</a><a href="#itinerary" data-step="itinerary">Roadmap</a><a href="#inclusions" data-step="inclusions">Inclusions</a><a href="#dates" data-step="dates">Dates</a><a href="#notes" data-step="notes">Notes</a></div><a class="trip-next-step" href="#itinerary"><span><small>Next</small><strong>Roadmap</strong></span>${icon('chevron-right')}</a></div></nav>
  <section class="trip-detail-shell"><div class="container trip-detail-layout">
    <main class="trip-detail-main">
      <section class="trip-story" id="overview"><span class="page-eyebrow">THE JOURNEY AT A GLANCE</span><h2>One route. A lifetime of stories.</h2><p>${esc(trip.summary)}</p>
        <div class="trip-facts"><article>${icon('clock-3')}<small>Duration</small><strong>${esc(trip.duration)}</strong></article><article>${icon('users')}<small>Group size</small><strong>${esc(trip.groupSize)}</strong></article><article>${icon('map-pin')}<small>Meet-up point</small><strong>${esc(trip.pickup)}</strong></article></div>
      </section>
      <section class="trip-roadmap" id="itinerary"><div class="trip-section-heading"><span class="page-eyebrow">DAY-BY-DAY ROADMAP</span><h2>See how your adventure unfolds</h2><p>Every stop has breathing room—so you experience the place, not just tick it off.</p></div><div class="roadmap-line">
        ${itinerary.map((day,index)=>`<article class="roadmap-stop ${index%2?'roadmap-right':'roadmap-left'}"><figure class="roadmap-media"><img src="${esc(tripImage)}" alt="Day ${day.day}: ${esc(day.title)}" /></figure><span class="roadmap-dot"><small>DAY</small>${day.day}</span><div class="roadmap-copy"><span>Stop ${String(index+1).padStart(2,'0')}</span><h3>${esc(day.title)}</h3>${(day.details||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</div></article>`).join('')}
      </div></section>
      <section class="trip-package" id="inclusions"><div class="trip-section-heading"><span class="page-eyebrow">CLEAR & HONEST</span><h2>Everything you need to know</h2></div><div class="trip-package-grid"><article class="package-panel included"><h3>${icon('circle-check-big')} Included in your trip</h3><ul>${(trip.inclusions||[]).map(x=>`<li>${icon('check')} ${esc(x)}</li>`).join('')}</ul></article><article class="package-panel excluded"><h3>${icon('x')} Not included</h3><ul>${(trip.exclusions||[]).map(x=>`<li>${icon('x')} ${esc(x)}</li>`).join('')}</ul></article></div></section>
      <section class="trip-dates" id="dates"><div class="trip-section-heading"><span class="page-eyebrow">UPCOMING DEPARTURES</span><h2>Choose your travel window</h2><p>Select a departure to reserve your interest. No payment is needed.</p></div><div class="trip-date-grid">${(trip.dates||[]).map(x=>`<button type="button" data-departure="${esc(x)}">${icon('calendar-days')}<strong>${esc(x)}</strong><small>Seats available</small><em>Select date ${icon('chevron-right')}</em></button>`).join('')}</div></section>
      <section class="trip-notes" id="notes"><h2>${icon('shield-check')} Good to know before you go</h2><ul>${(trip.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>
    </main>
    <aside class="trip-enquiry-sticky"><div class="trip-enquiry-card"><span class="enquiry-trust">${icon('shield-check')} Free expert consultation</span><p class="trip-from">Starting from</p><div class="trip-enquiry-price"><strong>${money(trip.price)}</strong><del>${money(trip.oldPrice)}</del></div><p class="trip-saving">${esc(trip.discount||'Limited departure offer')}</p><form id="enquiry-form" class="trip-mini-form"><label>Full name<input name="name" required autocomplete="name" placeholder="Your name" /></label><label>Phone number<input name="phone" required type="tel" autocomplete="tel" placeholder="+91 98765 43210" /></label><label>Email<input name="email" required type="email" autocomplete="email" placeholder="you@email.com" /></label><div class="mini-form-row"><label>Travel date<input name="travelDate" type="date" /></label><label>Travellers<input name="travellers" type="number" min="1" value="2" /></label></div><input type="hidden" name="destination" value="${esc(trip.title)}" /><input type="hidden" name="type" value="trip-detail" /><button class="btn btn-primary btn-block" type="submit">${icon('send')} Get a trip plan</button><p class="form-status" role="status"></p></form><div class="enquiry-assurance"><span>${icon('phone')} Callback in 15 mins</span><span>${icon('shield-check')} No spam. Ever.</span></div></div></aside>
  </div></section>`;
  wireForm();
  wireTripExperience(trip);
}

function wireTripExperience(trip){
  const steps=[['overview','Overview'],['itinerary','Roadmap'],['inclusions','Inclusions'],['dates','Dates'],['notes','Notes']];
  const links=[...document.querySelectorAll('.trip-progress-links a')],next=document.querySelector('.trip-next-step');
  const setActive=id=>{const index=Math.max(0,steps.findIndex(([key])=>key===id));links.forEach(link=>{const active=link.dataset.step===id;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','step');else link.removeAttribute('aria-current')});const target=steps[index+1]||steps[0];next.href=`#${target[0]}`;next.querySelector('small').textContent=index===steps.length-1?'Start again':'Next';next.querySelector('strong').textContent=target[1];next.classList.toggle('is-last',index===steps.length-1)};
  const observer=new IntersectionObserver(entries=>{const visible=entries.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:'-32% 0px -52% 0px',threshold:[0,.1,.3,.6]});
  steps.forEach(([id])=>{const section=document.getElementById(id);if(section)observer.observe(section)});setActive('overview');
  const revealItems=[...document.querySelectorAll('.roadmap-stop,.trip-facts article,.package-panel,.trip-date-grid>button,.trip-notes')];
  if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{rootMargin:'0px 0px -10% 0px',threshold:.12});revealItems.forEach((item,index)=>{item.classList.add('trip-reveal');item.style.setProperty('--reveal-delay',`${Math.min(index%4,3)*70}ms`);revealObserver.observe(item)})}else revealItems.forEach(item=>item.classList.add('is-visible'));
  document.querySelectorAll('[data-departure]').forEach(button=>button.addEventListener('click',()=>openDepartureForm(trip,button.dataset.departure,button)));
}

function departureInputValue(label){const parsed=new Date(`${label} ${new Date().getFullYear()}`);if(Number.isNaN(parsed.getTime()))return '';if(parsed<new Date())parsed.setFullYear(parsed.getFullYear()+1);return `${parsed.getFullYear()}-${String(parsed.getMonth()+1).padStart(2,'0')}-${String(parsed.getDate()).padStart(2,'0')}`}
function openDepartureForm(trip,dateLabel,trigger){
  document.querySelector('.departure-modal')?.remove();
  document.body.insertAdjacentHTML('beforeend',`<div class="departure-modal open"><button class="departure-backdrop" type="button" aria-label="Close departure form"></button><section class="departure-dialog" role="dialog" aria-modal="true" aria-labelledby="departure-title"><button class="departure-close" type="button" aria-label="Close">${icon('x')}</button><span class="departure-kicker">${icon('calendar-days')} Selected departure</span><h2 id="departure-title">Travel on ${esc(dateLabel)}</h2><p>${esc(trip.title)} · Our expert will confirm availability before you pay.</p><form class="departure-form"><label>Full name<input name="name" required autocomplete="name" placeholder="Your name"></label><label>Phone number<input name="phone" type="tel" required autocomplete="tel" placeholder="+91 98765 43210"></label><label>Travel date<input name="travelDate" type="date" value="${departureInputValue(dateLabel)}" required></label><input type="hidden" name="destination" value="${esc(trip.title)}"><input type="hidden" name="type" value="selected-departure"><button class="btn btn-primary" type="submit">${icon('send')} Request this date</button><p class="form-status" role="status"></p></form><small class="departure-safe">${icon('shield-check')} No payment · No spam · Free callback</small></section></div>`);
  const modal=document.querySelector('.departure-modal');applyTailwindStyles(modal);activateIcons();const form=modal.querySelector('form'),close=()=>{modal.remove();trigger?.focus()};modal.querySelectorAll('.departure-backdrop,.departure-close').forEach(x=>x.addEventListener('click',close));
  const escape=e=>{if(e.key==='Escape'){document.removeEventListener('keydown',escape);close()}};document.addEventListener('keydown',escape);modal.querySelector('input')?.focus();
  form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]'),status=form.querySelector('.form-status');button.disabled=true;status.textContent='Saving your selected departure…';try{const body={...Object.fromEntries(new FormData(form)),travellers:1};const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error();status.className='form-status success';status.textContent='Date request received. Our expert will call you shortly.';setTimeout(close,1800)}catch{status.className='form-status error';status.textContent='Could not save right now. Please try again.'}finally{button.disabled=false}})
}

async function renderTripLegacy(slug) {
  const trip=await api(`/trips/${slug}`); setMeta(trip.title,trip.summary);
  mount.innerHTML=hero({title:trip.title,description:trip.summary,image:trip.image,eyebrow:`${trip.duration} • ${trip.badge}`,crumbs:[{href:'/trips',label:'Trips'}]})+`<nav class="detail-tabs"><div class="container"><a href="#overview">Overview</a><a href="#itinerary">Itinerary</a><a href="#inclusions">Inclusions</a><a href="#dates">Dates</a><a href="#notes">Notes</a></div></nav><section class="content-section" id="overview"><div class="container content-grid"><article class="prose"><h2>About the trip</h2><p>${esc(trip.summary)}</p><h2>Trip details</h2><ul><li><strong>Duration:</strong> ${esc(trip.duration)}</li><li><strong>Group size:</strong> ${esc(trip.groupSize)}</li><li><strong>Pickup:</strong> ${esc(trip.pickup)}</li></ul><h2 id="itinerary">Itinerary breakdown</h2><div class="timeline">${trip.itinerary.map(day=>`<div class="timeline-item"><span class="day-pill">D${day.day}</span><div><h3>${esc(day.title)}</h3>${day.details.map(x=>`<p>${esc(x)}</p>`).join('')}</div></div>`).join('')}</div><h2 id="inclusions">What’s in the package?</h2><div class="two-col-list"><div class="list-panel"><h3>Included</h3><ul>${trip.inclusions.map(x=>`<li>${icon('check')} ${esc(x)}</li>`).join('')}</ul></div><div class="list-panel"><h3>Not included</h3><ul>${trip.exclusions.map(x=>`<li>${icon('x')} ${esc(x)}</li>`).join('')}</ul></div></div><h2 id="dates">Upcoming dates</h2><p>${trip.dates.map(x=>`<span class="filter-pill">${icon('calendar-days')} ${esc(x)}</span>`).join(' ')}</p><h2 id="notes">Important notes</h2><ul>${trip.notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><aside class="side-card"><span>Starting from</span><span class="trip-price-big">${money(trip.price)}</span><p><del>${money(trip.oldPrice)}</del> · ${esc(trip.discount)}</p><ul><li>${trip.duration}</li><li>${trip.groupSize}</li><li>20% to reserve your seat</li></ul><a class="btn btn-primary btn-block" href="/custom-trip?destination=${esc(trip.destinationSlug)}&trip=${esc(trip.slug)}">Send enquiry</a></aside></div></section>`;
}

function enquiryForm(type='custom') { return `<form class="form-card" id="enquiry-form"><div class="form-grid"><div class="field"><label for="name">Full name</label><input id="name" name="name" required autocomplete="name" /></div><div class="field"><label for="phone">Phone</label><input id="phone" name="phone" type="tel" required autocomplete="tel" /></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" required autocomplete="email" /></div><div class="field"><label for="destination">Destination</label><input id="destination" name="destination" required /></div><div class="field"><label for="travelDate">Travel date</label><input id="travelDate" name="travelDate" type="date" /></div><div class="field"><label for="travellers">Travellers</label><input id="travellers" name="travellers" type="number" min="1" value="1" /></div><div class="field"><label for="budget">Budget per person</label><select id="budget" name="budget"><option>Under ₹20,000</option><option>₹20,000–₹50,000</option><option>₹50,000–₹1,00,000</option><option>Above ₹1,00,000</option></select></div><div class="field full"><label for="message">Trip preferences</label><textarea id="message" name="message" placeholder="Tell us about stays, activities, departure city or anything important."></textarea></div><div class="field full"><button class="btn btn-primary" type="submit">${icon('send')} Send enquiry</button></div></div><p class="form-status" role="status"></p><input type="hidden" name="type" value="${type}" /></form>`; }
function wireForm(){const form=document.querySelector('#enquiry-form');if(!form)return;const params=new URLSearchParams(location.search);if(params.get('destination'))form.destination.value=params.get('destination');form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');const status=form.querySelector('.form-status');button.disabled=true;status.textContent='Sending…';try{const body=Object.fromEntries(new FormData(form));body.travellers=Number(body.travellers);const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error();status.className='form-status success';status.textContent='Thanks! Your enquiry is saved. Our travel expert will contact you shortly.';form.reset();}catch{status.className='form-status error';status.textContent='Could not save your enquiry. Please try again.';}finally{button.disabled=false;}})}

async function renderCustom(){setMeta('Plan a Custom Trip','Tell us your preferences and receive a personalised TravelEnfield itinerary.');mount.innerHTML=hero({title:'A trip that feels entirely yours.',description:'Tell us how you like to travel. A real trip expert will shape the route, stays and experiences around you—then explain every detail clearly.',eyebrow:'Personal planning, human support',image:'/images/custom-trip-consultation.jpg'})+`<section class="custom-proof"><div class="container"><div>${icon('shield-check')}<span><strong>Transparent quote</strong><small>Clear inclusions before you confirm</small></span></div><div>${icon('users')}<span><strong>Real travel expert</strong><small>One person guides your planning</small></span></div><div>${icon('circle-check-big')}<span><strong>Verified partners</strong><small>Handpicked stays and experiences</small></span></div><div>${icon('phone')}<span><strong>Support throughout</strong><small>Help before and during the trip</small></span></div></div></section><section class="custom-planner"><div class="container custom-planner-grid"><aside class="custom-planner-copy"><span class="page-eyebrow">Start with the essentials</span><h2>You dream it.<br>We make it workable.</h2><p>There is no pressure to know the perfect itinerary. Share the basics and our specialist will help you make the right trade-offs.</p><div class="planner-steps"><div><b>01</b><span><strong>Tell us your preferences</strong><small>Dates, people, pace and approximate budget.</small></span></div><div><b>02</b><span><strong>Speak with one expert</strong><small>We understand priorities and propose the right route.</small></span></div><div><b>03</b><span><strong>Review a clear plan</strong><small>Itinerary, stays and inclusions—nothing hidden.</small></span></div></div><div class="planner-promise">${icon('shield-check')}<p><strong>Your details stay private.</strong><br>We only use them to plan and discuss this enquiry.</p></div></aside><div class="custom-form-wrap"><div class="custom-form-head"><span>Usually takes 2 minutes</span><h2>Tell us about your trip</h2><p>No payment required. Our team normally responds within one working day.</p></div>${enquiryForm('custom-trip')}</div></div></section><section class="custom-how"><div class="container"><div class="section-header"><div><span class="page-eyebrow">Why customise?</span><h2 class="section-title">More freedom. Less guesswork.</h2></div></div><div class="custom-benefits"><article>${icon('map-pin')}<h3>Routes built for your pace</h3><p>Slow mornings, packed adventure days, or a balanced mix—the schedule follows you.</p></article><article>${icon('backpack')}<h3>Stays that fit the occasion</h3><p>Friends, families, couples and teams need different spaces. We plan accordingly.</p></article><article>${icon('indian-rupee')}<h3>Budget used where it matters</h3><p>We help prioritise comfort and experiences instead of adding unnecessary extras.</p></article></div></div></section>`;wireForm();}
async function renderBlogs(){const blogs=await api('/blogs');setMeta('Travel Blog','Original destination guides and practical travel advice.');mount.innerHTML=hero({title:'TravelEnfield Journal',description:'Useful guides, real planning advice and destination inspiration.',eyebrow:'Travel smarter',image:'/images/social-banner.jpg'})+`<section class="page-shell"><div class="container">${filterBar(false)}<div class="cards-grid">${blogs.map(b=>`<article class="listing-card" data-search="${esc((b.title+' '+b.category).toLowerCase())}"><a class="listing-card-media" href="/blog/${b.slug}"><img src="${b.image}" alt="${esc(b.title)}" loading="lazy"></a><div class="listing-card-body"><div class="card-meta">${esc(b.category)} · ${esc(b.readTime)}</div><h2><a href="/blog/${b.slug}">${esc(b.title)}</a></h2><p>${esc(b.excerpt)}</p><a class="card-link" href="/blog/${b.slug}">Read guide ${icon('chevron-right')}</a></div></article>`).join('')}</div></div></section>`;wireFilters();}
async function renderBlog(slug){const b=await api(`/blogs/${slug}`);setMeta(b.title,b.excerpt);mount.innerHTML=hero({title:b.title,description:b.excerpt,image:b.image,eyebrow:b.category,crumbs:[{href:'/blog',label:'Blog'}]})+`<section class="content-section"><article class="container article-layout"><div class="article-meta"><span>${esc(b.author)}</span><span>${esc(b.readTime)}</span><span>${new Date(b.publishedAt).toLocaleDateString('en-IN',{dateStyle:'medium'})}</span></div><div class="prose">${b.sections.map(s=>`<h2>${esc(s.heading)}</h2><p>${esc(s.body)}</p>`).join('')}<h2>Ready to experience it?</h2><p><a class="btn btn-primary" href="/custom-trip">Plan a custom trip</a></p></div></article></section>`;}
async function renderPage(slug){const p=await api(`/pages/${slug}`);setMeta(p.title,p.intro);const contact=slug==='contact-us'?`<section class="page-shell"><div class="container">${enquiryForm('contact')}</div></section>`:'';mount.innerHTML=hero({title:p.title,description:p.intro,eyebrow:p.eyebrow,image:slug==='reviews'?'/images/social-banner.jpg':'/images/hero.jpg'})+`<section class="content-section"><div class="container article-layout prose">${p.sections.map(s=>`<h2>${esc(s.heading)}</h2><p>${esc(s.body)}</p>`).join('')}</div></section>${contact}`;wireForm();}
function authForm(){return `<form class="form-card" id="auth-form"><div class="form-grid"><div class="field full signup-only"><label for="auth-name">Name</label><input id="auth-name" name="name" autocomplete="name" /></div><div class="field full"><label for="auth-email">Email</label><input id="auth-email" name="email" type="email" required autocomplete="email" /></div><div class="field full"><label for="auth-password">Password</label><input id="auth-password" name="password" type="password" minlength="6" required autocomplete="current-password" /></div><div class="field full"><button class="btn btn-primary" type="submit">Continue</button></div></div><p class="form-status" role="status"></p></form>`}
function renderAuth(mode){setMeta(mode==='signup'?'Create Account':'Login','Access your saved trips and enquiries.');mount.innerHTML=hero({title:mode==='signup'?'Create your account':'Welcome back',description:'Save favourites and keep your TravelEnfield journey details together.',eyebrow:'Traveller account'})+`<section class="page-shell"><div class="container">${authForm()}<p class="center">${mode==='signup'?'Already registered? <a href="/login">Login</a>':'New here? <a href="/signup">Create an account</a>'}</p></div></section>`;if(mode==='login')document.querySelector('.signup-only').remove();const form=document.querySelector('#auth-form');form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status');try{const response=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const result=await response.json();if(!response.ok)throw new Error(result.error);localStorage.setItem('travelenfield-user',JSON.stringify(result.user));status.className='form-status success';status.textContent=`Welcome, ${result.user.name}!`; }catch(error){status.className='form-status error';status.textContent=error.message;}})}

async function router(){try{const parts=location.pathname.split('/').filter(Boolean);const first=parts[0]||'';if(['trips','upcoming-trips','domestic-trips','international-trips','weekend-trips','deals','bike-trips','backpacking-trips','trekking-trips'].includes(first)&&parts.length===1)await renderListing(first);else if(first==='trips'&&parts[1])await renderTrip(parts[1]);else if(first==='destinations'&&parts[1])await renderDestination(parts[1]);else if(first==='hotels'&&parts.length===1)await renderHotels();else if(first==='hotels'&&parts[1])await renderHotel(parts[1]);else if(first==='custom-trip')await renderCustom();else if(first==='blog'&&!parts[1])await renderBlogs();else if(first==='blog'&&parts[1])await renderBlog(parts[1]);else if(['about-us','contact-us','reviews','faq','privacy-policy','terms-and-conditions','cancellation-policy'].includes(first))await renderPage(first);else if(['login','signup'].includes(first))renderAuth(first);else throw new Error('Page not found');applyTailwindStyles(mount);activateIcons();}catch(error){setMeta('Page not found','The requested page could not be loaded.');mount.innerHTML=`<section class="page-shell"><div class="container empty-state"><h1>${esc(error.message)}</h1><p>Return to the homepage or explore available trips.</p><a class="btn btn-primary" href="/">Go home</a></div></section>`;applyTailwindStyles(mount);}}

router();
