import './enquiry-popup.js';
import { createIcons, Backpack, Bike, BookOpen, CalendarDays, CarFront, Check, ChevronDown, ChevronRight, CircleCheckBig, Clock3, Gift, IndianRupee, Luggage, Mail, Map, MapPin, Menu, MessageCircle, MountainSnow, Phone, Plane, Search, Send, ShieldCheck, SlidersHorizontal, Sparkles, Tags, Users, WandSparkles, X } from 'lucide';

const iconSet = { Backpack, Bike, BookOpen, CalendarDays, CarFront, Check, ChevronDown, ChevronRight, CircleCheckBig, Clock3, Gift, IndianRupee, Luggage, Mail, Map, MapPin, Menu, MessageCircle, MountainSnow, Phone, Plane, Search, Send, ShieldCheck, SlidersHorizontal, Sparkles, Tags, Users, WandSparkles, X };
const mount = document.querySelector('#page-content');
document.querySelectorAll('.logo-img, .logo-img-mobile, .mobile-nav-logo').forEach(img => { img.src = '/images/brand/logo-navbar.png'; });
const footerLogo = document.querySelector('.app-footer img'); if (footerLogo) footerLogo.src = '/images/brand/logo-footer.png';
const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);
const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]));
const icon = (name, cls = '') => `<i data-lucide="${name}" class="${cls}"></i>`;
const readJsonResponse = async response => {
  const text = await response.text();
  if (!text.trim()) throw new Error(response.ok ? 'The server returned an empty response. Please refresh and try again.' : `Server request failed (${response.status}).`);
  try { return JSON.parse(text); } catch { throw new Error('The server returned an invalid response. Please restart the API server and try again.'); }
};
const api = async path => { const response = await fetch(`/api${path}`, { headers: { Accept: 'application/json' } }); const result = await readJsonResponse(response); if (!response.ok) throw new Error(result?.error || `Unable to load this page (${response.status})`); return result; };
const setMeta = (title, description) => { document.title = `${title} | TravelEnfield`; document.querySelector('meta[name="description"]')?.setAttribute('content', description || 'Explore curated trips with TravelEnfield.'); };
const activateIcons = () => createIcons({ icons: iconSet });

const dropdowns = [...document.querySelectorAll('.nav-dropdown')];
dropdowns.forEach(item => item.querySelector('.nav-dropdown-toggle')?.addEventListener('click', event => { const open=!item.classList.contains('open'); dropdowns.forEach(x=>{x.classList.remove('open');x.querySelector('button')?.setAttribute('aria-expanded','false')}); if(open){item.classList.add('open');event.currentTarget.setAttribute('aria-expanded','true')}}));
document.addEventListener('click', event => { if(!event.target.closest('.nav-dropdown')) dropdowns.forEach(x=>{x.classList.remove('open');x.querySelector('button')?.setAttribute('aria-expanded','false')}); });
const mobileNav=document.querySelector('#mobile-nav'), mobileOverlay=document.querySelector('#mobile-nav-overlay');
if(mobileOverlay&&mobileNav)document.body.append(mobileOverlay,mobileNav);
const drawerTriggers=[...document.querySelectorAll('[data-drawer-trigger]')];
const setMobileNav=open=>{mobileNav?.classList.toggle('open',open);mobileOverlay?.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);mobileNav?.setAttribute('aria-hidden',String(!open));document.querySelector('#hamburger')?.setAttribute('aria-expanded',String(open));drawerTriggers.forEach(trigger=>trigger.setAttribute('aria-expanded',String(open)))};
document.querySelector('#hamburger')?.addEventListener('click',()=>setMobileNav(true));document.querySelector('#mobile-nav-close')?.addEventListener('click',()=>setMobileNav(false));mobileOverlay?.addEventListener('click',()=>setMobileNav(false));
drawerTriggers.forEach(trigger=>trigger.addEventListener('click',()=>setMobileNav(true)));
document.addEventListener('keydown', event => { if(event.key==='Escape'){setMobileNav(false);dropdowns.forEach(x=>{x.classList.remove('open');x.querySelector('button')?.setAttribute('aria-expanded','false')})} });

function hero({ title, description, image = '/images/hero.jpg', eyebrow = 'TravelEnfield', crumbs = [] }) {
  return `<section class="page-hero"><img src="${esc(image)}" alt="" /><div class="page-hero-content container"><div class="breadcrumbs"><a href="/">Home</a>${crumbs.map(c=>`<span>/</span><a href="${c.href}">${esc(c.label)}</a>`).join('')}</div><div class="page-eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(description)}</p></div></section>`;
}
function tripCard(trip) {
  return `<article class="listing-card" data-search="${esc(`${trip.title} ${trip.destinationSlug}`.toLowerCase())}" data-price="${trip.price}" data-duration="${trip.nights}"><a class="listing-card-media" href="/trips/${esc(trip.slug)}"><img src="${esc(trip.image)}" alt="${esc(trip.title)}" loading="lazy" /><span class="card-badge">${esc(trip.badge || 'Group Trip')}</span></a><div class="listing-card-body"><div class="card-meta"><span>${icon('clock-3')} ${esc(trip.duration)}</span><span>${icon('users')} ${esc(trip.groupSize || 'Group')}</span></div><h2><a href="/trips/${esc(trip.slug)}">${esc(trip.title)}</a></h2><p>${esc(trip.summary)}</p><div class="price-row"><del>${money(trip.oldPrice)}</del><strong>${money(trip.price)}</strong><a class="card-link" href="/trips/${esc(trip.slug)}" aria-label="View ${esc(trip.title)}">View ${icon('chevron-right')}</a></div></div></article>`;
}
function categoryTripCard(trip) { return `<article class="category-trip-card" data-search="${esc(`${trip.title} ${trip.destinationSlug}`.toLowerCase())}" data-price="${trip.price}" data-duration="${trip.nights}"><a href="/trips/${esc(trip.slug)}" class="category-trip-media"><img src="${esc(trip.image)}" alt="${esc(trip.title)}" loading="lazy"><span>${esc(trip.badge||'Group trip')}</span></a><div class="category-trip-body"><div class="category-trip-meta"><span>${icon('clock-3')} ${esc(trip.duration)}</span><span>${icon('users')} ${esc(trip.groupSize)}</span></div><h2><a href="/trips/${esc(trip.slug)}">${esc(trip.title)}</a></h2><p>${esc(trip.summary)}</p><div class="category-trip-dates">${icon('calendar-days')} ${esc((trip.dates||[]).slice(0,3).join(' · '))}</div><div class="category-trip-price"><span>From <strong>${money(trip.price)}</strong> <del>${money(trip.oldPrice)}</del></span><a href="/trips/${esc(trip.slug)}">View trip ${icon('chevron-right')}</a></div></div></article>`; }
function destinationCard(item) {
  return `<article class="listing-card" data-search="${esc(item.name.toLowerCase())}"><a class="listing-card-media" href="/destinations/${esc(item.slug)}"><img src="${esc(item.image)}" alt="${esc(item.name)}" loading="lazy" /></a><div class="listing-card-body"><div class="card-meta"><span>${icon('map-pin')} ${esc(item.category)}</span><span>${esc(item.bestTime)}</span></div><h2><a href="/destinations/${esc(item.slug)}">${esc(item.name)}</a></h2><p>${esc(item.tagline)}</p><div class="price-row"><span>From</span><strong>${money(item.startingPrice)}</strong><a class="card-link" href="/destinations/${esc(item.slug)}">Explore ${icon('chevron-right')}</a></div></div></article>`;
}
function filterBar(showSort = true) {
  return `<div class="filter-bar"><label class="sr-only" for="page-search">Search</label><input id="page-search" type="search" placeholder="Search trips or destinations…" />${showSort ? '<select id="page-sort" aria-label="Sort results"><option value="featured">Recommended</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="short">Shortest first</option></select>' : ''}<span class="result-count" id="result-count"></span></div>`;
}
function wireFilters() {
  const input = document.querySelector('#page-search'); const sort = document.querySelector('#page-sort'); const grid = document.querySelector('.cards-grid'); if (!grid) return;
  const cards = [...grid.children];
  const update = () => { const query = input?.value.trim().toLowerCase() || ''; cards.forEach(card => card.hidden = !card.dataset.search.includes(query)); const visible = cards.filter(c=>!c.hidden); document.querySelector('#result-count').textContent = `${visible.length} results`; if (sort) { const key=sort.value; visible.sort((a,b)=> key==='low'?a.dataset.price-b.dataset.price:key==='high'?b.dataset.price-a.dataset.price:key==='short'?a.dataset.duration-b.dataset.duration:0).forEach(card=>grid.append(card)); } };
  input?.addEventListener('input', update); sort?.addEventListener('change', update); update();
}

async function renderListing(slug) {
  const map = { 'trips':'all','upcoming-trips':'upcoming','domestic-trips':'domestic','international-trips':'international','weekend-trips':'weekend','deals':'all','bike-trips':'bike-trips','backpacking-trips':'backpacking-trips','trekking-trips':'trekking-trips' };
  const tripCategory = map[slug];
  const [category, loadedTrips] = await Promise.all([
    api(`/categories/${slug}`).catch(() => ({ name:'Trips', title:'Explore all trips', description:'Compare curated domestic and international journeys.' })),
    api(`/trips${tripCategory && tripCategory !== 'all' ? `?category=${encodeURIComponent(tripCategory)}` : ''}`),
  ]);
  let trips = loadedTrips || []; if(slug==='deals') trips=trips.filter(t=>t.discount);
  const destinationTabs=[...new Set(trips.map(t=>t.destinationSlug).filter(Boolean))];
  setMeta(category.title, category.description); mount.innerHTML = hero({title:category.title,description:category.description,image:category.image||'/images/hero.jpg',eyebrow:category.eyebrow||'Curated departures'})+`<section class="category-intro"><div class="container"><span class="page-eyebrow">Curated by TravelEnfield</span><h2>Explore ${esc(category.name||'our trips')}</h2><p>${esc(category.description)}</p><div class="category-tabs"><button class="active" data-category-tab="all">All trips</button>${destinationTabs.map(x=>`<button data-category-tab="${esc(x)}">${esc(x.replaceAll('-',' '))}</button>`).join('')}</div></div></section><section class="category-results"><div class="container category-results-layout"><aside class="category-filter-card"><div class="filter-title">${icon('sliders-horizontal')} <strong>Filters</strong><button type="button" id="clear-filters">Clear</button></div><label>Search trips<input id="page-search" type="search" placeholder="Destination or trip name"></label><label>Sort by<select id="page-sort"><option value="featured">Recommended</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="short">Shortest first</option></select></label><details open><summary>Trip type</summary><p>Small-group departures with a trained trip captain.</p></details><details><summary>Budget</summary><p>Transparent per-person prices are shown on every card.</p></details><a href="/custom-trip" class="btn btn-primary btn-block">Need a custom trip?</a></aside><div class="category-list-wrap"><div class="category-list-head"><div><span id="result-count"></span><h2>Trips ready for you</h2></div><span>Verified departures</span></div><div class="category-trip-list cards-grid">${trips.length?trips.map(categoryTripCard).join(''):'<div class="empty-state"><h2>New departures coming soon</h2><p>Plan private dates with our trip team.</p><a class="btn btn-primary" href="/custom-trip">Plan a custom trip</a></div>'}</div></div></div></section>`; wireFilters();
  document.querySelectorAll('[data-category-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-category-tab]').forEach(x=>x.classList.remove('active'));button.classList.add('active');const key=button.dataset.categoryTab;document.querySelector('#page-search').value=key==='all'?'':key.replaceAll('-',' ');document.querySelector('#page-search').dispatchEvent(new Event('input'))}));
  document.querySelector('#clear-filters')?.addEventListener('click',()=>{document.querySelector('#page-search').value='';document.querySelector('#page-sort').value='featured';document.querySelector('#page-search').dispatchEvent(new Event('input'))});
}

async function renderDestination(slug) {
  const [item,trips] = await Promise.all([api(`/destinations/${slug}`),api(`/trips?destination=${slug}`)]); setMeta(`${item.name} Tour Packages`,item.summary);
  mount.innerHTML=hero({title:`${item.name} Tour Packages`,description:item.tagline,image:item.image,eyebrow:`From ${money(item.startingPrice)}`,crumbs:[{href:'/trips',label:'Destinations'}]})+`<section class="content-section"><div class="container content-grid"><article class="prose"><h2>About ${esc(item.name)}</h2><p>${esc(item.summary)}</p><h2>Top highlights</h2><ul>${item.highlights.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Things to do</h2><ul>${item.thingsToDo.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>Best time to visit</h2><p>${esc(item.bestTime)}</p><h2>Travel essentials</h2><ul>${item.travelTips.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><aside class="side-card"><h3>Plan ${esc(item.name)}</h3><span class="trip-price-big">${money(item.startingPrice)}</span><p>Custom dates, stays and experiences for your group.</p><a class="btn btn-primary btn-block" href="/custom-trip?destination=${esc(item.slug)}">Plan a custom trip</a></aside></div></section><section class="content-section alt"><div class="container"><h2 class="section-title">Available ${esc(item.name)} trips</h2><div class="cards-grid">${trips.length?trips.map(tripCard).join(''):'<div class="empty-state"><p>New departures are being planned. Send us an enquiry for private dates.</p></div>'}</div></div></section><section class="content-section"><div class="container prose"><h2>Frequently asked questions</h2>${item.faq.map(x=>`<details class="faq-item"><summary class="faq-question">${esc(x.question)}</summary><p>${esc(x.answer)}</p></details>`).join('')}</div></section>`;
}

async function renderTrip(slug) {
  const trip=await api(`/trips/${slug}`); setMeta(trip.title,trip.summary);
  const itinerary=(trip.itinerary||[]);
  const tripImage=trip.image||'/assets/images/hero.jpg';
  mount.innerHTML=`<section class="trip-detail-hero">
    <img class="trip-detail-bg" src="${esc(tripImage)}" alt="${esc(trip.title)}" />
    <div class="trip-detail-scrim"></div>
    <figure class="trip-float trip-float-left"><img src="${esc(tripImage)}" alt="Scenic view from ${esc(trip.title)}" /></figure>
    <figure class="trip-float trip-float-right"><img src="${esc(tripImage)}" alt="Travel experience in ${esc(trip.title)}" /></figure>
    <div class="container trip-detail-hero-copy">
      <div class="breadcrumbs"><a href="/">Home</a><span>/</span><a href="/trips">Trips</a><span>/</span><span>${esc(trip.title)}</span></div>
      <span class="trip-detail-kicker">${icon('circle-check-big')} ${esc(trip.badge||'Curated group trip')}</span>
      <h1>${esc(trip.title)}</h1><p>${esc(trip.summary)}</p>
      <div class="trip-hero-chips"><span>${icon('clock-3')} ${esc(trip.duration)}</span><span>${icon('users')} ${esc(trip.groupSize)}</span><span>${icon('map-pin')} ${esc(trip.pickup)}</span></div>
    </div>
  </section>
  <nav class="detail-tabs trip-tabs" aria-label="Trip sections"><div class="container trip-progress"><div class="trip-progress-links"><a href="#overview" data-step="overview">Overview</a><a href="#itinerary" data-step="itinerary">Roadmap</a><a href="#inclusions" data-step="inclusions">Inclusions</a><a href="#dates" data-step="dates">Dates</a><a href="#notes" data-step="notes">Notes</a></div><a class="trip-next-step" href="#itinerary"><span><small>Next</small><strong>Roadmap</strong></span>${icon('chevron-right')}</a></div></nav>
  <section class="trip-detail-shell"><div class="container trip-detail-layout">
    <main class="trip-detail-main">
      <section class="trip-story" id="overview"><span class="page-eyebrow">THE JOURNEY AT A GLANCE</span><h2>One route. A lifetime of stories.</h2><p>${esc(trip.summary)}</p>
        <div class="trip-facts"><article>${icon('clock-3')}<small>Duration</small><strong>${esc(trip.duration)}</strong></article><article>${icon('users')}<small>Group size</small><strong>${esc(trip.groupSize)}</strong></article><article>${icon('map-pin')}<small>Meet-up point</small><strong>${esc(trip.pickup)}</strong></article></div>
      </section>
      <section class="trip-roadmap" id="itinerary"><div class="trip-section-heading"><span class="page-eyebrow">DAY-BY-DAY ROADMAP</span><h2>See how your adventure unfolds</h2><p>Every stop has breathing room—so you experience the place, not just tick it off.</p></div><div class="roadmap-line">
        ${itinerary.map((day,index)=>`<article class="roadmap-stop ${index%2?'roadmap-right':'roadmap-left'}"><figure class="roadmap-media"><img src="${esc(tripImage)}" alt="Day ${day.day}: ${esc(day.title)}" /></figure><span class="roadmap-dot"><small>DAY</small>${day.day}</span><div class="roadmap-copy"><span>Stop ${String(index+1).padStart(2,'0')}</span><h3>${esc(day.title)}</h3>${(day.details||[]).map(x=>`<p>${esc(x)}</p>`).join('')}</div></article>`).join('')}
      </div></section>
      <section class="trip-package" id="inclusions"><div class="trip-section-heading"><span class="page-eyebrow">CLEAR & HONEST</span><h2>Everything you need to know</h2></div><div class="trip-package-grid"><article class="package-panel included"><h3>${icon('circle-check-big')} Included in your trip</h3><ul>${(trip.inclusions||[]).map(x=>`<li>${icon('check')} ${esc(x)}</li>`).join('')}</ul></article><article class="package-panel excluded"><h3>${icon('x')} Not included</h3><ul>${(trip.exclusions||[]).map(x=>`<li>${icon('x')} ${esc(x)}</li>`).join('')}</ul></article></div></section>
      <section class="trip-dates" id="dates"><div class="trip-section-heading"><span class="page-eyebrow">UPCOMING DEPARTURES</span><h2>Choose your travel window</h2><p>Select a departure to reserve your interest. No payment is needed.</p></div><div class="trip-date-grid">${(trip.dates||[]).map(x=>`<button type="button" data-departure="${esc(x)}">${icon('calendar-days')}<strong>${esc(x)}</strong><small>Seats available</small><em>Select date ${icon('chevron-right')}</em></button>`).join('')}</div></section>
      <section class="trip-notes" id="notes"><h2>${icon('shield-check')} Good to know before you go</h2><ul>${(trip.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>
    </main>
    <aside class="trip-enquiry-sticky"><div class="trip-enquiry-card"><span class="enquiry-trust">${icon('shield-check')} Free expert consultation</span><p class="trip-from">Starting from</p><div class="trip-enquiry-price"><strong>${money(trip.price)}</strong><del>${money(trip.oldPrice)}</del></div><p class="trip-saving">${esc(trip.discount||'Limited departure offer')}</p><form id="enquiry-form" class="trip-mini-form"><label>Full name<input name="name" required autocomplete="name" placeholder="Your name" /></label><label>Phone number<input name="phone" required type="tel" autocomplete="tel" placeholder="+91 98765 43210" /></label><label>Email<input name="email" required type="email" autocomplete="email" placeholder="you@email.com" /></label><div class="mini-form-row"><label>Travel date<input name="travelDate" type="date" /></label><label>Travellers<input name="travellers" type="number" min="1" value="2" /></label></div><input type="hidden" name="destination" value="${esc(trip.title)}" /><input type="hidden" name="type" value="trip-detail" /><button class="btn btn-primary btn-block" type="submit">${icon('send')} Get a trip plan</button><p class="form-status" role="status"></p></form><div class="enquiry-assurance"><span>${icon('phone')} Callback in 15 mins</span><span>${icon('shield-check')} No spam. Ever.</span></div></div></aside>
  </div></section>`;
  wireForm();
  wireTripExperience(trip);
}

function wireTripExperience(trip){
  const steps=[['overview','Overview'],['itinerary','Roadmap'],['inclusions','Inclusions'],['dates','Dates'],['notes','Notes']];
  const links=[...document.querySelectorAll('.trip-progress-links a')],next=document.querySelector('.trip-next-step');
  const setActive=id=>{const index=Math.max(0,steps.findIndex(([key])=>key===id));links.forEach(link=>{const active=link.dataset.step===id;link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','step');else link.removeAttribute('aria-current')});const target=steps[index+1]||steps[0];next.href=`#${target[0]}`;next.querySelector('small').textContent=index===steps.length-1?'Start again':'Next';next.querySelector('strong').textContent=target[1];next.classList.toggle('is-last',index===steps.length-1)};
  const observer=new IntersectionObserver(entries=>{const visible=entries.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:'-32% 0px -52% 0px',threshold:[0,.1,.3,.6]});
  steps.forEach(([id])=>{const section=document.getElementById(id);if(section)observer.observe(section)});setActive('overview');
  const revealItems=[...document.querySelectorAll('.roadmap-stop,.trip-facts article,.package-panel,.trip-date-grid>button,.trip-notes')];
  if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{rootMargin:'0px 0px -10% 0px',threshold:.12});revealItems.forEach((item,index)=>{item.classList.add('trip-reveal');item.style.setProperty('--reveal-delay',`${Math.min(index%4,3)*70}ms`);revealObserver.observe(item)})}else revealItems.forEach(item=>item.classList.add('is-visible'));
  document.querySelectorAll('[data-departure]').forEach(button=>button.addEventListener('click',()=>openDepartureForm(trip,button.dataset.departure,button)));
}

function departureInputValue(label){const parsed=new Date(`${label} ${new Date().getFullYear()}`);if(Number.isNaN(parsed.getTime()))return '';if(parsed<new Date())parsed.setFullYear(parsed.getFullYear()+1);return `${parsed.getFullYear()}-${String(parsed.getMonth()+1).padStart(2,'0')}-${String(parsed.getDate()).padStart(2,'0')}`}
function openDepartureForm(trip,dateLabel,trigger){
  document.querySelector('.departure-modal')?.remove();
  document.body.insertAdjacentHTML('beforeend',`<div class="departure-modal open"><button class="departure-backdrop" type="button" aria-label="Close departure form"></button><section class="departure-dialog" role="dialog" aria-modal="true" aria-labelledby="departure-title"><button class="departure-close" type="button" aria-label="Close">${icon('x')}</button><span class="departure-kicker">${icon('calendar-days')} Selected departure</span><h2 id="departure-title">Travel on ${esc(dateLabel)}</h2><p>${esc(trip.title)} · Our expert will confirm availability before you pay.</p><form class="departure-form"><label>Full name<input name="name" required autocomplete="name" placeholder="Your name"></label><label>Phone number<input name="phone" type="tel" required autocomplete="tel" placeholder="+91 98765 43210"></label><label>Travel date<input name="travelDate" type="date" value="${departureInputValue(dateLabel)}" required></label><input type="hidden" name="destination" value="${esc(trip.title)}"><input type="hidden" name="type" value="selected-departure"><button class="btn btn-primary" type="submit">${icon('send')} Request this date</button><p class="form-status" role="status"></p></form><small class="departure-safe">${icon('shield-check')} No payment · No spam · Free callback</small></section></div>`);
  activateIcons();const modal=document.querySelector('.departure-modal'),form=modal.querySelector('form'),close=()=>{modal.remove();trigger?.focus()};modal.querySelectorAll('.departure-backdrop,.departure-close').forEach(x=>x.addEventListener('click',close));
  const escape=e=>{if(e.key==='Escape'){document.removeEventListener('keydown',escape);close()}};document.addEventListener('keydown',escape);modal.querySelector('input')?.focus();
  form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]'),status=form.querySelector('.form-status');button.disabled=true;status.textContent='Saving your selected departure…';try{const body={...Object.fromEntries(new FormData(form)),travellers:1};const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error();status.className='form-status success';status.textContent='Date request received. Our expert will call you shortly.';setTimeout(close,1800)}catch{status.className='form-status error';status.textContent='Could not save right now. Please try again.'}finally{button.disabled=false}})
}

async function renderTripLegacy(slug) {
  const trip=await api(`/trips/${slug}`); setMeta(trip.title,trip.summary);
  mount.innerHTML=hero({title:trip.title,description:trip.summary,image:trip.image,eyebrow:`${trip.duration} • ${trip.badge}`,crumbs:[{href:'/trips',label:'Trips'}]})+`<nav class="detail-tabs"><div class="container"><a href="#overview">Overview</a><a href="#itinerary">Itinerary</a><a href="#inclusions">Inclusions</a><a href="#dates">Dates</a><a href="#notes">Notes</a></div></nav><section class="content-section" id="overview"><div class="container content-grid"><article class="prose"><h2>About the trip</h2><p>${esc(trip.summary)}</p><h2>Trip details</h2><ul><li><strong>Duration:</strong> ${esc(trip.duration)}</li><li><strong>Group size:</strong> ${esc(trip.groupSize)}</li><li><strong>Pickup:</strong> ${esc(trip.pickup)}</li></ul><h2 id="itinerary">Itinerary breakdown</h2><div class="timeline">${trip.itinerary.map(day=>`<div class="timeline-item"><span class="day-pill">D${day.day}</span><div><h3>${esc(day.title)}</h3>${day.details.map(x=>`<p>${esc(x)}</p>`).join('')}</div></div>`).join('')}</div><h2 id="inclusions">What’s in the package?</h2><div class="two-col-list"><div class="list-panel"><h3>Included</h3><ul>${trip.inclusions.map(x=>`<li>${icon('check')} ${esc(x)}</li>`).join('')}</ul></div><div class="list-panel"><h3>Not included</h3><ul>${trip.exclusions.map(x=>`<li>${icon('x')} ${esc(x)}</li>`).join('')}</ul></div></div><h2 id="dates">Upcoming dates</h2><p>${trip.dates.map(x=>`<span class="filter-pill">${icon('calendar-days')} ${esc(x)}</span>`).join(' ')}</p><h2 id="notes">Important notes</h2><ul>${trip.notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><aside class="side-card"><span>Starting from</span><span class="trip-price-big">${money(trip.price)}</span><p><del>${money(trip.oldPrice)}</del> · ${esc(trip.discount)}</p><ul><li>${trip.duration}</li><li>${trip.groupSize}</li><li>20% to reserve your seat</li></ul><a class="btn btn-primary btn-block" href="/custom-trip?destination=${esc(trip.destinationSlug)}&trip=${esc(trip.slug)}">Send enquiry</a></aside></div></section>`;
}

function enquiryForm(type='custom') { return `<form class="form-card" id="enquiry-form"><div class="form-grid"><div class="field"><label for="name">Full name</label><input id="name" name="name" required autocomplete="name" /></div><div class="field"><label for="phone">Phone</label><input id="phone" name="phone" type="tel" required autocomplete="tel" /></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" required autocomplete="email" /></div><div class="field"><label for="destination">Destination</label><input id="destination" name="destination" required /></div><div class="field"><label for="travelDate">Travel date</label><input id="travelDate" name="travelDate" type="date" /></div><div class="field"><label for="travellers">Travellers</label><input id="travellers" name="travellers" type="number" min="1" value="1" /></div><div class="field"><label for="budget">Budget per person</label><select id="budget" name="budget"><option>Under ₹20,000</option><option>₹20,000–₹50,000</option><option>₹50,000–₹1,00,000</option><option>Above ₹1,00,000</option></select></div><div class="field full"><label for="message">Trip preferences</label><textarea id="message" name="message" placeholder="Tell us about stays, activities, departure city or anything important."></textarea></div><div class="field full"><button class="btn btn-primary" type="submit">${icon('send')} Send enquiry</button></div></div><p class="form-status" role="status"></p><input type="hidden" name="type" value="${type}" /></form>`; }
function wireForm(){const form=document.querySelector('#enquiry-form');if(!form)return;const params=new URLSearchParams(location.search);if(params.get('destination'))form.destination.value=params.get('destination');form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');const status=form.querySelector('.form-status');button.disabled=true;status.textContent='Sending…';try{const body=Object.fromEntries(new FormData(form));body.travellers=Number(body.travellers);const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error();status.className='form-status success';status.textContent='Thanks! Your enquiry is saved. Our travel expert will contact you shortly.';form.reset();}catch{status.className='form-status error';status.textContent='Could not save your enquiry. Please try again.';}finally{button.disabled=false;}})}

async function renderCustom(){setMeta('Plan a Custom Trip','Tell us your preferences and receive a personalised TravelEnfield itinerary.');mount.innerHTML=hero({title:'A trip that feels entirely yours.',description:'Tell us how you like to travel. A real trip expert will shape the route, stays and experiences around you—then explain every detail clearly.',eyebrow:'Personal planning, human support',image:'/images/custom-trip-consultation.jpg'})+`<section class="custom-proof"><div class="container"><div>${icon('shield-check')}<span><strong>Transparent quote</strong><small>Clear inclusions before you confirm</small></span></div><div>${icon('users')}<span><strong>Real travel expert</strong><small>One person guides your planning</small></span></div><div>${icon('circle-check-big')}<span><strong>Verified partners</strong><small>Handpicked stays and experiences</small></span></div><div>${icon('phone')}<span><strong>Support throughout</strong><small>Help before and during the trip</small></span></div></div></section><section class="custom-planner"><div class="container custom-planner-grid"><aside class="custom-planner-copy"><span class="page-eyebrow">Start with the essentials</span><h2>You dream it.<br>We make it workable.</h2><p>There is no pressure to know the perfect itinerary. Share the basics and our specialist will help you make the right trade-offs.</p><div class="planner-steps"><div><b>01</b><span><strong>Tell us your preferences</strong><small>Dates, people, pace and approximate budget.</small></span></div><div><b>02</b><span><strong>Speak with one expert</strong><small>We understand priorities and propose the right route.</small></span></div><div><b>03</b><span><strong>Review a clear plan</strong><small>Itinerary, stays and inclusions—nothing hidden.</small></span></div></div><div class="planner-promise">${icon('shield-check')}<p><strong>Your details stay private.</strong><br>We only use them to plan and discuss this enquiry.</p></div></aside><div class="custom-form-wrap"><div class="custom-form-head"><span>Usually takes 2 minutes</span><h2>Tell us about your trip</h2><p>No payment required. Our team normally responds within one working day.</p></div>${enquiryForm('custom-trip')}</div></div></section><section class="custom-how"><div class="container"><div class="section-header"><div><span class="page-eyebrow">Why customise?</span><h2 class="section-title">More freedom. Less guesswork.</h2></div></div><div class="custom-benefits"><article>${icon('map-pin')}<h3>Routes built for your pace</h3><p>Slow mornings, packed adventure days, or a balanced mix—the schedule follows you.</p></article><article>${icon('backpack')}<h3>Stays that fit the occasion</h3><p>Friends, families, couples and teams need different spaces. We plan accordingly.</p></article><article>${icon('indian-rupee')}<h3>Budget used where it matters</h3><p>We help prioritise comfort and experiences instead of adding unnecessary extras.</p></article></div></div></section>`;wireForm();}
async function renderBlogs(){const blogs=await api('/blogs');setMeta('Travel Blog','Original destination guides and practical travel advice.');mount.innerHTML=hero({title:'TravelEnfield Journal',description:'Useful guides, real planning advice and destination inspiration.',eyebrow:'Travel smarter',image:'/images/social-banner.jpg'})+`<section class="page-shell"><div class="container">${filterBar(false)}<div class="cards-grid">${blogs.map(b=>`<article class="listing-card" data-search="${esc((b.title+' '+b.category).toLowerCase())}"><a class="listing-card-media" href="/blog/${b.slug}"><img src="${b.image}" alt="${esc(b.title)}" loading="lazy"></a><div class="listing-card-body"><div class="card-meta">${esc(b.category)} · ${esc(b.readTime)}</div><h2><a href="/blog/${b.slug}">${esc(b.title)}</a></h2><p>${esc(b.excerpt)}</p><a class="card-link" href="/blog/${b.slug}">Read guide ${icon('chevron-right')}</a></div></article>`).join('')}</div></div></section>`;wireFilters();}
async function renderBlog(slug){const b=await api(`/blogs/${slug}`);setMeta(b.title,b.excerpt);mount.innerHTML=hero({title:b.title,description:b.excerpt,image:b.image,eyebrow:b.category,crumbs:[{href:'/blog',label:'Blog'}]})+`<section class="content-section"><article class="container article-layout"><div class="article-meta"><span>${esc(b.author)}</span><span>${esc(b.readTime)}</span><span>${new Date(b.publishedAt).toLocaleDateString('en-IN',{dateStyle:'medium'})}</span></div><div class="prose">${b.sections.map(s=>`<h2>${esc(s.heading)}</h2><p>${esc(s.body)}</p>`).join('')}<h2>Ready to experience it?</h2><p><a class="btn btn-primary" href="/custom-trip">Plan a custom trip</a></p></div></article></section>`;}
async function renderPage(slug){const p=await api(`/pages/${slug}`);setMeta(p.title,p.intro);const contact=slug==='contact-us'?`<section class="page-shell"><div class="container">${enquiryForm('contact')}</div></section>`:'';mount.innerHTML=hero({title:p.title,description:p.intro,eyebrow:p.eyebrow,image:slug==='reviews'?'/images/social-banner.jpg':'/images/hero.jpg'})+`<section class="content-section"><div class="container article-layout prose">${p.sections.map(s=>`<h2>${esc(s.heading)}</h2><p>${esc(s.body)}</p>`).join('')}</div></section>${contact}`;wireForm();}
function authForm(){return `<form class="form-card" id="auth-form"><div class="form-grid"><div class="field full signup-only"><label for="auth-name">Name</label><input id="auth-name" name="name" autocomplete="name" /></div><div class="field full"><label for="auth-email">Email</label><input id="auth-email" name="email" type="email" required autocomplete="email" /></div><div class="field full"><label for="auth-password">Password</label><input id="auth-password" name="password" type="password" minlength="6" required autocomplete="current-password" /></div><div class="field full"><button class="btn btn-primary" type="submit">Continue</button></div></div><p class="form-status" role="status"></p></form>`}
function renderAuth(mode){setMeta(mode==='signup'?'Create Account':'Login','Access your saved trips and enquiries.');mount.innerHTML=hero({title:mode==='signup'?'Create your account':'Welcome back',description:'Save favourites and keep your TravelEnfield journey details together.',eyebrow:'Traveller account'})+`<section class="page-shell"><div class="container">${authForm()}<p class="center">${mode==='signup'?'Already registered? <a href="/login">Login</a>':'New here? <a href="/signup">Create an account</a>'}</p></div></section>`;if(mode==='login')document.querySelector('.signup-only').remove();const form=document.querySelector('#auth-form');form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status');try{const response=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const result=await response.json();if(!response.ok)throw new Error(result.error);localStorage.setItem('travelenfield-user',JSON.stringify(result.user));status.className='form-status success';status.textContent=`Welcome, ${result.user.name}!`; }catch(error){status.className='form-status error';status.textContent=error.message;}})}

async function router(){try{const parts=location.pathname.split('/').filter(Boolean);const first=parts[0]||'';if(['trips','upcoming-trips','domestic-trips','international-trips','weekend-trips','deals','bike-trips','backpacking-trips','trekking-trips'].includes(first)&&parts.length===1)await renderListing(first);else if(first==='trips'&&parts[1])await renderTrip(parts[1]);else if(first==='destinations'&&parts[1])await renderDestination(parts[1]);else if(first==='custom-trip')await renderCustom();else if(first==='blog'&&!parts[1])await renderBlogs();else if(first==='blog'&&parts[1])await renderBlog(parts[1]);else if(['about-us','contact-us','reviews','faq','privacy-policy','terms-and-conditions','cancellation-policy'].includes(first))await renderPage(first);else if(['login','signup'].includes(first))renderAuth(first);else throw new Error('Page not found');activateIcons();}catch(error){setMeta('Page not found','The requested page could not be loaded.');mount.innerHTML=`<section class="page-shell"><div class="container empty-state"><h1>${esc(error.message)}</h1><p>Return to the homepage or explore available trips.</p><a class="btn btn-primary" href="/">Go home</a></div></section>`;}}

router();
