const svg=(body)=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`;
const closeIcon=svg('<path d="M18 6 6 18M6 6l12 12"/>');
const callIcon=svg('<path d="M4 14a8 8 0 0 1 16 0"/><path d="M18 19c0 1.1-.9 2-2 2h-3"/><path d="M4 14v4a2 2 0 0 0 2 2h1v-8H6a2 2 0 0 0-2 2ZM20 14v4a2 2 0 0 1-2 2h-1v-8h1a2 2 0 0 1 2 2Z"/>');
const shieldIcon=svg('<path d="M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3v8Z"/><path d="m9 12 2 2 4-4"/>');

document.body.insertAdjacentHTML('beforeend',`<button class="enquiry-orbit" id="enquiry-orbit" aria-label="Open trip enquiry form"><span class="enquiry-orbit-ring"></span>${callIcon}<span>Plan my trip</span></button>
<div class="enquiry-modal" id="enquiry-modal" aria-hidden="true"><div class="enquiry-backdrop" data-popup-close></div><section class="enquiry-dialog" role="dialog" aria-modal="true" aria-labelledby="enquiry-title"><button class="enquiry-close" type="button" data-popup-close aria-label="Close enquiry form">${closeIcon}</button><div class="enquiry-panel"><div class="enquiry-trust"><span class="enquiry-kicker">Planning soon?</span><h2 id="enquiry-title">Get a route that fits—not a copied itinerary.</h2><p>Share three details. A real TravelEnfield expert will help with dates, budget and the right travel style.</p><div class="enquiry-proof"><div>${shieldIcon}<span><strong>No payment now</strong><small>The planning call is completely free</small></span></div><div>${callIcon}<span><strong>Human response</strong><small>Usually within one working day</small></span></div></div><div class="enquiry-urgency"><strong>Travelling in the next 30 days?</strong><span>Send your request early so stays and transfers can be checked properly.</span></div></div><form class="enquiry-quick-form" id="enquiry-quick-form"><div class="quick-form-head"><span>Free trip consultation</span><h3>Where should we call you?</h3></div><label for="quick-name">Full name</label><input id="quick-name" name="name" required autocomplete="name" placeholder="Your name"><label for="quick-phone">Phone number</label><input id="quick-phone" name="phone" type="tel" required autocomplete="tel" inputmode="tel" pattern="[0-9 +()-]{10,}" placeholder="10-digit mobile number"><label for="quick-destination">Destination or trip idea</label><input id="quick-destination" name="destination" required placeholder="e.g. Ladakh, Bali, weekend escape"><button type="submit">Get my free trip plan <span>→</span></button><p class="quick-form-note">By submitting, you agree to be contacted about this enquiry. No spam.</p><p class="quick-form-status" role="status" aria-live="polite"></p></form></div></section></div>`);

const modal=document.querySelector('#enquiry-modal');
const trigger=document.querySelector('#enquiry-orbit');
const form=document.querySelector('#enquiry-quick-form');
let returnFocus=null;
const focusable=()=>[...modal.querySelectorAll('button,input,a,[tabindex]:not([tabindex="-1"])')];
function setPopup(open){modal.classList.toggle('open',open);modal.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('popup-open',open);if(open){returnFocus=document.activeElement;requestAnimationFrame(()=>form.querySelector('input')?.focus())}else{returnFocus?.focus?.()}}
trigger.addEventListener('click',()=>setPopup(true));
modal.querySelectorAll('[data-popup-close]').forEach(item=>item.addEventListener('click',()=>setPopup(false)));
document.addEventListener('keydown',event=>{if(!modal.classList.contains('open'))return;if(event.key==='Escape')setPopup(false);if(event.key==='Tab'){const items=focusable(),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type="submit"]'),status=form.querySelector('.quick-form-status');button.disabled=true;status.className='quick-form-status';status.textContent='Sending your request…';try{const body={...Object.fromEntries(new FormData(form)),type:'popup-enquiry',travellers:1};const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error();status.classList.add('success');status.textContent='Request received. A TravelEnfield expert will contact you shortly.';form.reset()}catch{status.classList.add('error');status.textContent='Could not send right now. Please try again or use WhatsApp.'}finally{button.disabled=false}});
if(!new URLSearchParams(window.location.search).has('noPopup')) window.setTimeout(()=>setPopup(true),6000);
