import 'dotenv/config';
import mongoose from 'mongoose';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { Destination, Trip, Category, Blog, Page, Hotel } from './models.js';

let cdnMap = {};
try { cdnMap = JSON.parse(readFileSync(new URL('../cloudinary-uploads.json', import.meta.url), 'utf8')); } catch {}
const cdn = path => cdnMap[path] || path;
const img = slug => cdn(`/images/destinations/${slug}.jpg`);
const commonFaq = name => [
  { question: `What is the best time to visit ${name}?`, answer: `The ideal season depends on the experiences you prefer. Our trip experts recommend dates with comfortable weather and reliable local access.` },
  { question: `Can I customise my ${name} trip?`, answer: 'Yes. Dates, stay category, activities and transfers can be customised for private groups, couples and families.' },
  { question: 'Are solo travellers welcome?', answer: 'Absolutely. Our fixed departures are designed for solo travellers as well as friends and couples.' },
];
const categoryFaq = name => [
  { question: `How do I choose the right ${name.toLowerCase()}?`, answer: 'Compare duration, group size and price on each trip card, or use the filters to narrow things down by destination and budget.' },
  { question: 'Can these trips be customised?', answer: 'Yes. If a fixed departure does not fit your dates or group, our team can put together a private itinerary instead.' },
  { question: 'Are solo travellers welcome?', answer: 'Absolutely. Every departure is designed so solo travellers join a group from day one, not just a seat on a bus.' },
  { question: 'What is included in the price?', answer: 'Stays, transfers, a trip captain and the experiences listed on each trip page. Flights, personal expenses and taxes are shown separately before you book.' },
];
export const destinations = [
  ['Ladakh','ladakh','domestic',19499,'May to September','High passes, blue lakes and unforgettable Himalayan roads',['Pangong Lake','Nubra Valley','Khardung La'],['Bike through mountain passes','Visit monasteries','Camp near Pangong']],
  ['Spiti Valley','spiti','domestic',17999,'May to October','Ancient monasteries and stark high-altitude landscapes',['Kaza','Key Monastery','Chandratal Lake'],['Drive the full circuit','Stargaze in remote villages','Explore fossil villages']],
  ['Manali','manali','domestic',9499,'October to June','A quick Himalayan escape for snow, cafés and adventure',['Solang Valley','Atal Tunnel','Old Manali'],['Try snow activities','Explore local cafés','Visit mountain villages']],
  ['Kerala','kerala','domestic',14999,'September to March','Backwaters, tea gardens and a slower tropical rhythm',['Munnar','Alleppey','Varkala'],['Stay on a houseboat','Walk through tea estates','Watch a coastal sunset']],
  ['Meghalaya','meghalaya','domestic',15499,'October to April','Living root bridges, clear rivers and rain-washed forests',['Shillong','Dawki','Cherrapunji'],['Walk a living root bridge','Boat on the Umngot','Chase waterfalls']],
  ['Bali','bali','international',44999,'April to October','Temples, island adventures and vibrant tropical culture',['Ubud','Nusa Penida','Uluwatu'],['Sunrise at Mount Batur','Island hopping','Explore temples']],
  ['Thailand','thailand','international',32999,'November to March','Tropical islands, street food and legendary nightlife',['Bangkok','Krabi','Phuket'],['Long-tail boat tour','Explore night markets','Visit island beaches']],
  ['Nepal','nepal','international',29999,'March to May, September to November','Himalayan views, heritage towns and welcoming mountain culture',['Kathmandu','Pokhara','Annapurna'],['Watch an Himalayan sunrise','Explore heritage squares','Walk a mountain trail']],
].map(([name,slug,category,startingPrice,bestTime,tagline,highlights,thingsToDo]) => ({ name,slug,category,startingPrice,bestTime,tagline,summary:`Discover ${name} with transparent inclusions, handpicked stays and experienced TravelEnfield trip captains.`,image:img(slug),highlights,thingsToDo,travelTips:['Carry a valid government ID','Keep weather-ready layers','Respect local culture and ecology'],faq:commonFaq(name) }));

const itinerary = names => names.map((title, i) => ({ day:i+1,title,details:[`Experience ${title} with your trip captain.`, 'Meals, transfers and stay follow the inclusions listed below.'] }));
export const trips = [
  {title:'Leh Ladakh Bike Trip',slug:'leh-ladakh-bike-trip',destinationSlug:'ladakh',categories:['all','upcoming','domestic','bike-trips'],image:cdn('https://res.cloudinary.com/dq3typk9u/image/upload/v1786542549/travelenfield/categories/bike-trips.jpg'),duration:'6 nights / 7 days',nights:6,price:19499,oldPrice:24999,discount:'22% Off',badge:'Free Goodies',summary:'Ride across iconic high passes and remote valleys on a supported Himalayan motorcycle journey.',groupSize:'12–20 travellers',pickup:'Leh Airport',dates:['Aug 15','Aug 22','Sep 5','Sep 12'],itinerary:itinerary(['Arrival and acclimatisation in Leh','Leh local exploration','Leh to Nubra Valley','Nubra to Pangong Lake','Pangong to Leh','Buffer and celebration','Departure']),featured:true},
  {title:'Spiti Valley Road Trip',slug:'spiti-valley-road-trip',destinationSlug:'spiti',categories:['all','upcoming','domestic','backpacking-trips','bike-trips'],image:img('spiti'),duration:'7 nights / 8 days',nights:7,price:17999,oldPrice:22999,discount:'22% Off',badge:'Bestseller',summary:'A high-altitude road trip through monasteries, villages and dramatic cold-desert landscapes.',groupSize:'12–18 travellers',pickup:'Delhi',dates:['Aug 20','Sep 1','Sep 15','Oct 2'],itinerary:itinerary(['Delhi to Shimla','Shimla to Chitkul','Chitkul to Kalpa','Kalpa to Kaza','Kaza local circuit','Kaza to Chandratal','Chandratal to Manali','Departure']),featured:true},
  {title:'Bali Adventure Tour',slug:'bali-adventure-tour',destinationSlug:'bali',categories:['all','upcoming','international'],image:img('bali'),duration:'5 nights / 6 days',nights:5,price:44999,oldPrice:54999,discount:'18% Off',badge:'Free Goodies',summary:'A balanced Bali escape with temples, waterfalls, island views and social evenings.',groupSize:'10–18 travellers',pickup:'Denpasar Airport',dates:['Sep 10','Sep 24','Oct 8','Oct 22'],itinerary:itinerary(['Arrival in Bali','Ubud culture trail','Nusa Penida day trip','Mount Batur sunrise','Uluwatu and leisure','Departure']),featured:true},
  {title:'Thailand Beach Getaway',slug:'thailand-beach-getaway',destinationSlug:'thailand',categories:['all','upcoming','international'],image:img('thailand'),duration:'5 nights / 6 days',nights:5,price:32999,oldPrice:39999,discount:'18% Off',badge:'Trending',summary:'Island scenery, bustling markets and a fun group itinerary across Thailand.',groupSize:'10–18 travellers',pickup:'Bangkok Airport',dates:['Sep 5','Sep 19','Oct 3','Oct 17'],itinerary:itinerary(['Bangkok arrival','Bangkok city highlights','Fly to Krabi','Island hopping','Leisure and night market','Departure'])},
  {title:'Manali Snow Adventure',slug:'manali-snow-adventure',destinationSlug:'manali',categories:['all','upcoming','domestic','weekend','bike-trips'],image:img('manali'),duration:'3 nights / 4 days',nights:3,price:9499,oldPrice:12999,discount:'27% Off',badge:'Weekend Pick',summary:'A compact mountain break with snow activities, cafés and scenic drives.',groupSize:'12–24 travellers',pickup:'Delhi',dates:['Aug 10','Aug 17','Aug 24','Aug 31'],itinerary:itinerary(['Delhi to Manali','Solang Valley adventure','Old Manali and local sights','Return to Delhi'])},
  {title:'Meghalaya Explorer',slug:'meghalaya-explorer',destinationSlug:'meghalaya',categories:['all','upcoming','domestic','backpacking-trips','bike-trips'],image:img('meghalaya'),duration:'5 nights / 6 days',nights:5,price:15499,oldPrice:19999,discount:'23% Off',badge:'New',summary:'Clear rivers, forest trails and living root bridges in India’s northeast.',groupSize:'10–18 travellers',pickup:'Guwahati Airport',dates:['Sep 8','Sep 22','Oct 6','Oct 20'],itinerary:itinerary(['Guwahati to Shillong','Cherrapunji waterfalls','Living root bridge trek','Dawki and Mawlynnong','Shillong local day','Departure'])},
].map(t => ({...t,inclusions:['Comfortable stays on sharing basis','Transfers as per itinerary','Trip captain throughout the journey','Experiences specifically mentioned'],exclusions:['Flights unless explicitly mentioned','Personal expenses and tips','Meals not listed in the itinerary','GST and applicable taxes'],notes:['Carry a valid photo ID.','Final schedule may change due to weather or local conditions.']}));

export const hotels = [
  ['The Grand Dragon, Leh','the-grand-dragon-leh','ladakh','Leh, Ladakh','4','4.8','412','Bestseller','Mountain-view stay near Leh city','Sumptuous rooms with warm hospitality right in the heart of Ladakh’s capital.','7499','9999','Premium Mountain Room',['Breakfast included','Free WiFi','Oxygen support','In-house café','Airport pickup','Heated rooms'],['Heated rooms with mountain views','Gurudwara Pathar Sahib close by','Popular with group trips','Free airport transfer'],['3.2 km from Leh Airport','Walk to Leh Main Market','20 min to Shanti Stupa'],['Deluxe Mountain Room','2 adults','22 m²','Queen bed','Mountain view',['Breakfast','Heating','Hill view balcony'],'7499','9999','Premium Mountain Room','2 adults','30 m²','King bed','Panoramic valley view',['Breakfast','Heating','Minibar','Balcony'],'9499','12499','Family Suite','4 adults','46 m²','2 Queen beds','Valley + hill view',['Breakfast','Heating','Living area'],'12499','15999'],'14:00','12:00','Free cancellation up to 7 days before check-in',['Is breakfast included in the room rate?','Yes, a vegetarian spread is included for all stays.','Do you help with permits for travellers?','Yes, our front desk assists group trip travellers with permit paperwork.','Is there oxygen support on site?','The property has supplemental oxygen and a clinic on call.']],
  ['The Kaza Stays, Spiti Valley','the-kaza-stays-spiti','spiti','Kaza, Spiti','4','4.9','287','Traveller Favourite','Cosy village stay under star-filled skies','Simple, warm rooms with solar hot water and the best homestyle food in Spiti.','6499','8499','Mountain View Room',['Breakfast & dinner','Solar heating','Free WiFi','Bonfire evenings','Guided walks'],['Star-gazing terrace','Fresh Himalayan food','Supports local families','Bonfire every evening'],['2.1 km from Kaza Bus Stand','Next to Key Monastery road','8 min to Kaza main market'],['Mountain View Room','2 adults','18 m²','Queen bed','Village & peak view',['Breakfast + dinner','Solar heating'],'6499','8499','Courtyard Deluxe','2 adults','24 m²','Queen bed','Courtyard view',['All meals','Fireplace'],'7999','10499','Family Suite','5 adults','40 m²','3 Queen beds','Valley view',['All meals','Private sit-out'],'11999','15499'],'13:30','11:30','Free cancellation up to 3 days before check-in',['Is the water heated by solar?','Yes, solar heating is available in the morning and evening.','Do you arrange local taxis?','We arrange shared taxis to key monasteries and Chandratal.']],
  ['Solang Valley Resort, Manali','solang-valley-resort-manali','manali','Solang, Manali','3','4.6','531','Weekend Pick','Cosy rooms with snow views near Solang','A warm, well-priced retreat minutes from Manali’s best adventure spots.','5499','7299','Superior Valley Room',['Breakfast included','Free WiFi','In-house restaurant','Bonfire nights','Adventure desk'],['5 min from Solang adventure zone','Snow-view balconies','Adventure activity desk','Parking for bikers'],['5.2 km from Solang Valley','1.2 km from Old Manali','8 km from Atal Tunnel'],['Superior Valley Room','2 adults','20 m²','Queen bed','Valley view',['Breakfast','Balcony'],'5499','7299','Premium Snow View','2 adults','26 m²','King bed','Snow-capped peaks',['Breakfast','Heating'],'6499','8799','Family Cottage','5 adults','42 m²','2 Queen beds','River & valley view',['Breakfast','Fireplace','Garden'],'9999','12999'],'14:00','11:00','Free cancellation up to 24 hours before check-in',['Is parking available for bikes?','Yes, secure covered parking is available for motorcycle trips.','Do rooms have heating?','Premium rooms and cottages include heaters in winter.']],
  ['Spice Tree Munnar, Kerala','spice-tree-munnar-kerala','kerala','Munnar, Kerala','4','4.7','398','Couples Choice','Tea-garden cottages wrapped in mist','Stay between cardamom plantations and rolling tea estates with private balconies.','6499','8499','Tea Estate Cottage',['Breakfast included','Free WiFi','Plantation walks','Bonfire on request','Ayurvedic spa'],['Tea-garden views from every room','Guided plantation walk','Spa and wellness corner','Popular with couples'],['9 km from Munnar town','1 km to tea gardens','Near Eravikulam road'],['Tea Estate Cottage','2 adults','24 m²','Queen bed','Tea garden view',['Breakfast','Balcony'],'6499','8499','Plantation Suite','2 adults','34 m²','King bed','Cardamom valley view',['Breakfast','Bathtub'],'8999','11499','Family Villa','4 adults','52 m²','2 King beds','Private garden',['Breakfast','Living room'],'12999','16499'],'14:00','11:00','Free cancellation up to 3 days before check-in',['Do you arrange plantation tours?','Yes, guided walks can be booked at the front desk.','Is the spa included?','Wellness treatments are available at an extra charge.']],
  ['Ri Kynjai, Shillong','ri-kynjai-shillong','meghalaya','Shillong, Meghalaya','4','4.8','246','New','Lakeside retreat above Umiam Lake','A serene stay with dramatic lake views, local food and warm Khasi hospitality.','7999','10499','Lake View Room',['Breakfast included','Free WiFi','In-house restaurant','Lake activities','Fireplace lounge'],['Panoramic Umiam Lake views','Local Khasi cuisine','Kayaking & boating desk','Near Umiam viewpoint'],['15 km from Shillong city','5 min from Umiam Lake','2 km from Umiam viewpoint'],['Lake View Room','2 adults','26 m²','Queen bed','Umiam Lake view',['Breakfast','Balcony'],'7999','10499','Deluxe Lake Suite','2 adults','36 m²','King bed','Full lake panorama',['Breakfast','Bathtub'],'10499','13499','Family Lake House','4 adults','55 m²','2 King beds','Lake + hill view',['Breakfast','Living area'],'14499','18499'],'14:00','11:00','Free cancellation up to 7 days before check-in',['Can we do water activities nearby?','Kayaking and boating are available on Umiam Lake nearby.','Is the property accessible by car?','Yes, the resort has dedicated parking and a scenic drive approach.']],
  ['Aksari Villa, Ubud','aksari-villa-ubud-bali','bali','Ubud, Bali','5','4.9','364','Luxury','Private pool villas in the rice fields','Tranquil pool villas surrounded by jungle and rice terraces, minutes from Ubud’s culture.','11499','15499','Pool Access Villa',['Breakfast included','Free WiFi','Private pool','Airport transfer','Spa services'],['Private pool villa','Rice terrace views','Daily yoga on request','10 min to Ubud market'],['4 km from Ubud Palace','15 min to Monkey Forest','Close to Tegalalang terraces'],['Pool Access Villa','2 adults','40 m²','King bed','Rice terrace view',['Breakfast','Private pool'],'11499','15499','Jungle Villa','2 adults','52 m²','King bed','Jungle view',['Breakfast','Private pool','Outdoor bath'],'13999','18499','Family Pool Villa','4 adults','90 m²','2 King beds','Rice terrace + pool',['Breakfast','Private pool','Butler service'],'20999','27499'],'14:00','12:00','Free cancellation up to 7 days before check-in',['Is there a shuttle to Ubud centre?','Yes, a complimentary shuttle runs to Ubud centre three times a day.','Are villas family friendly?','Yes, the family pool villa is set up for two adults and two children.']],
  ['Amari Phuket, Thailand','amari-phuket-thailand','thailand','Phuket, Thailand','5','4.8','672','Trending','Beachfront rooms with sea views','Modern beachfront stay on Patong Beach with a sunset rooftop pool.','9499','12999','Deluxe Sea View',['Breakfast included','Free WiFi','Rooftop pool','Gym','Beach access'],['Direct Patong Beach access','Rooftop infinity pool','Sunsets from the terrace','Walkable nightlife'],['On Patong Beach','5 min to Bangla Road','45 min from Phuket Airport'],['Deluxe Sea View','2 adults','30 m²','King bed','Sea view',['Breakfast','Balcony'],'9499','12999','Premier Ocean Suite','2 adults','48 m²','King bed','Panoramic ocean view',['Breakfast','Lounge access'],'12999','16999','Beachfront Family Room','4 adults','60 m²','2 Queen beds','Beachfront view',['Breakfast','Kids welcome'],'16999','21999'],'14:00','12:00','Free cancellation up to 5 days before check-in',['Is breakfast included?','Yes, a buffet breakfast is included for all room categories.','Is the rooftop pool open to all guests?','Yes, the rooftop infinity pool is open to all in-house guests.']],
  ['Tiger Mountain Pokhara, Nepal','tiger-mountain-pokhara-nepal','nepal','Pokhara, Nepal','4','4.7','312','Couples Choice','Sunrise-facing rooms over the lake','A hillside boutique stay with sunrise views across Phewa Lake and the Annapurna range.','6999','9299','Annapurna View Room',['Breakfast included','Free WiFi','Rooftop restaurant','Sunrise deck','Bicycle hire'],['Annapurna sunrise view','Steps from Phewa Lake','Bicycle & kayak hire','Local heritage feel'],['2.5 km from Lakeside','On Phewa Lake','Near World Peace Pagoda ferry'],['Annapurna View Room','2 adults','24 m²','Queen bed','Annapurna + lake view',['Breakfast','Balcony'],'6999','9299','Lakefront Suite','2 adults','38 m²','King bed','Phewa Lake frontage',['Breakfast','Sit-out'],'9499','12499','Family Suite','4 adults','50 m²','2 Queen beds','Mountain + lake view',['Breakfast','Living area'],'12499','15999'],'13:00','11:00','Free cancellation up to 4 days before check-in',['Do you arrange sunrise paragliding?','Yes, we help book paragliding and sunrise activities at the desk.','Is breakfast vegetarian friendly?','Absolutely, a vegetarian menu is available every morning.']],
].map(([name,slug,destinationSlug,location,star,rating,reviews,badge,tagline,summary,pricePerNight,oldPricePerNight,roomType,amenities,highlights,nearby,rooms,policiesCheckIn,policiesCheckOut,policiesCancellation,faq]) => {
  const image=cdn(`/images/destinations/${destinationSlug}.jpg`);
  const chunk=(arr,n)=>{const out=[];for(let i=0;i<arr.length;i+=n)out.push(arr.slice(i,i+n));return out;};
  return {name,slug,destinationSlug,location,star:Number(star),rating:Number(rating),reviews:Number(reviews),badge,tagline,summary,pricePerNight:Number(pricePerNight),oldPricePerNight:Number(oldPricePerNight),roomType,image,gallery:[image,cdn('https://res.cloudinary.com/dq3typk9u/image/upload/v1786542569/travelenfield/social-banner.jpg'),cdn('https://res.cloudinary.com/dq3typk9u/image/upload/v1786542561/travelenfield/hero.jpg'),cdn('https://res.cloudinary.com/dq3typk9u/image/upload/v1786542559/travelenfield/group-trips-himalaya-hero.jpg')],amenities,highlights,nearby,rooms:chunk(rooms,8).map(([roomName,occupancy,size,bed,view,perks,price,oldPrice],index)=>({id:`${slug}-r${index+1}`,name:roomName,occupancy,size,bed,view,perks:perks||[],price:Number(price),oldPrice:Number(oldPrice)})),policies:{checkIn:policiesCheckIn,checkOut:policiesCheckOut,cancellation:policiesCancellation},faq:Array.from({length:Math.floor(faq.length/2)},(_,i)=>({question:faq[i*2],answer:faq[i*2+1]})),featured:['bestseller','traveller favourite'].some(x=>x===badge.toLowerCase())};
});

export const categoryData = [
  ['All Trips','trips','Explore all TravelEnfield trips','Compare curated departures across India and international destinations.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542561/travelenfield/hero.jpg','Find your next story'],
  ['Upcoming Group Trips','upcoming-trips','Upcoming group departures','Meet like-minded travellers on fixed-date journeys led by experienced captains.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542569/travelenfield/social-banner.jpg','Fixed dates, effortless planning'],
  ['Domestic Trips','domestic-trips','Explore India','From Himalayan roads to tropical backwaters, discover curated journeys closer to home.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542553/travelenfield/destinations/ladakh.jpg','Journeys across India'],
  ['International Trips','international-trips','Travel beyond borders','Original international itineraries with clear inclusions and on-trip support.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542552/travelenfield/destinations/bali.jpg','Beyond borders'],
  ['Weekend Trips','weekend-trips','Make the weekend count','Short, high-energy escapes designed around convenient departures.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542554/travelenfield/destinations/manali.jpg','Quick escapes'],
  ['Deals','deals','Current trip deals','Limited-period prices and early-bird benefits on selected departures.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542558/travelenfield/destinations/thailand.jpg','Limited-period benefits'],
  ['Bike Trips','bike-trips','Ride farther. Feel more.','Supported motorcycle journeys through Ladakh and India’s most dramatic open roads.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542549/travelenfield/categories/bike-trips.jpg','Two wheels, one unforgettable road'],
  ['Backpacking Trips','backpacking-trips','Backpacking trips for curious people','Social, immersive routes with thoughtful stays and experienced trip captains.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542557/travelenfield/destinations/spiti.jpg','Travel light, connect deeply'],
  ['Trekking Trips','trekking-trips','Trails worth earning','High-altitude landscapes, expert-led routes and small-group mountain experiences.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542556/travelenfield/destinations/nepal.jpg','Walk into the wild'],
].map(([name,slug,title,description,image,eyebrow]) => ({name,slug,title,description,image:cdn(image),eyebrow,filters:['destination','budget','duration','date'],faq:categoryFaq(name)}));

export const blogs = [
  ['Best Time to Visit Ladakh','best-time-to-visit-ladakh','Plan around open roads, comfortable weather and the experiences you value most.','ladakh','Destination Guide'],
  ['Places to Visit in Spiti Valley','places-to-visit-in-spiti','A practical guide to monasteries, villages, lakes and high-altitude viewpoints.','spiti','Places to Visit'],
  ['Things to Do in Bali','things-to-do-in-bali','Temples, sunrise hikes, island trips and local cultural experiences.','bali','Things to Do'],
  ['Meghalaya Travel Guide','meghalaya-travel-guide','Everything to know before exploring root bridges, rivers and waterfalls.','meghalaya','Travel Guide'],
].map(([title,slug,excerpt,imageSlug,category],i) => ({title,slug,excerpt,image:img(imageSlug),category,author:'TravelEnfield Editorial',readTime:`${5+i} min read`,publishedAt:new Date(2026,6,i+1),sections:[{heading:'Why this journey deserves a place on your list',body:excerpt+' TravelEnfield recommends planning with enough flexibility for weather, local conditions and spontaneous discoveries.'},{heading:'Planning essentials',body:'Confirm your dates early, pack for the season, keep digital copies of your documents and review package inclusions before booking.'},{heading:'Travel responsibly',body:'Support local businesses, avoid single-use plastic and follow the guidance of local hosts and trip captains.'}]}));

export const pageData = [
  ['about-us','About TravelEnfield','Our story','Trips that feel unforgettable, not complicated.','We design transparent, social and well-supported journeys for modern Indian travellers.'],
  ['contact-us','Contact TravelEnfield','Let’s plan your journey','Talk to a real travel expert.','Call, WhatsApp or send an enquiry and our team will help you choose the right trip.'],
  ['reviews','Reviews & Community','Traveller stories','Real journeys. Real connections.','Our community is built around safe, memorable trips and the friendships created along the way.'],
  ['faq','Frequently Asked Questions','Need help?','Clear answers before you book.','Find information about payments, departures, cancellations, stays and trip support.'],
  ['privacy-policy','Privacy Policy','Legal','How we handle your information.','We collect only the information needed to operate enquiries, bookings and account services responsibly.'],
  ['terms-and-conditions','Terms and Conditions','Legal','Terms for using TravelEnfield.','These terms explain booking responsibilities, payments, trip operations and acceptable website use.'],
  ['cancellation-policy','Cancellation Policy','Legal','Flexible, clearly explained cancellation terms.','Refund and rescheduling eligibility depends on the trip type and notice period.'],
].map(([slug,title,eyebrow,intro,body]) => ({slug,title,eyebrow,intro,sections:[{heading:'Overview',body},{heading:'Need more information?',body:'Contact TravelEnfield before confirming a booking if any part of a package or policy is unclear.'}]}));

async function seedDatabase() {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/travelenfield');
  await Promise.all([Destination.deleteMany({}),Trip.deleteMany({}),Category.deleteMany({}),Blog.deleteMany({}),Page.deleteMany({}),Hotel.deleteMany({})]);
  await Promise.all([Destination.insertMany(destinations),Trip.insertMany(trips),Category.insertMany(categoryData),Blog.insertMany(blogs),Page.insertMany(pageData),Hotel.insertMany(hotels)]);
  console.log(`Seeded ${destinations.length} destinations, ${trips.length} trips, ${categoryData.length} categories, ${blogs.length} blogs, ${pageData.length} pages and ${hotels.length} hotels.`);
  await mongoose.disconnect();
}

const invokedDirectly = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) seedDatabase().catch(error => {
  console.error('Database seed failed:', error);
  process.exitCode = 1;
});
