import 'dotenv/config';
import mongoose from 'mongoose';
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { Destination, Trip, Category, Blog, Page, Hotel } from './models.js';

let cdnMap = {};
try { cdnMap = JSON.parse(readFileSync(new URL('../cloudinary-uploads.json', import.meta.url), 'utf8')); } catch {}
const cdn = path => cdnMap[path] || path;
const img = slug => cdn(`/images/destinations/${slug}.jpg`);
const commonFaq = name => [
  { question: `What is the best time to visit ${name}?`, answer: `The ideal season depends on the experiences you prefer. Our trip experts recommend dates with comfortable weather and reliable local access.` },
  { question: `Can I customise my ${name} trip?`, answer: 'Yes. Dates, stay category, activities and transfers can be customised for private groups, couples and families.' },
  { question: 'Are solo travellers welcome?', answer: 'Absolutely. Our fixed departures are designed for solo travellers as well as friends and couples.' },
];
const categoryFaq = name => [
  { question: `How do I choose the right ${name.toLowerCase()}?`, answer: 'Compare duration, group size and price on each trip card, or use the filters to narrow things down by destination and budget.' },
  { question: 'Can these trips be customised?', answer: 'Yes. If a fixed departure does not fit your dates or group, our team can put together a private itinerary instead.' },
  { question: 'Are solo travellers welcome?', answer: 'Absolutely. Every departure is designed so solo travellers join a group from day one, not just a seat on a bus.' },
  { question: 'What is included in the price?', answer: 'Stays, transfers, a trip captain and the experiences listed on each trip page. Flights, personal expenses and taxes are shown separately before you book.' },
];
const destinationImage = {
  'spiti-winter':'spiti', kashmir:'manali', uttarakhand:'nepal', himachal:'manali', andaman:'kerala', rajasthan:'meghalaya',
  vietnam:'thailand', 'sri-lanka':'bali', bhutan:'nepal', dubai:'thailand', maldives:'bali', singapore:'thailand',
  rishikesh:'nepal', jibhi:'manali', chopta:'spiti', coorg:'kerala',
};
const destinationProfiles = {
  ladakh: { overview:'Ladakh is a high-altitude Himalayan journey of wide-open valleys, cobalt lakes, prayer flags and roads that feel like an adventure in themselves. A well-designed first trip balances Leh acclimatisation with Nubra Valley, Pangong Lake, monasteries and high passes so that every day feels rewarding without pushing the body too quickly.', planningNotes:'Altitude is the most important part of planning. Keep your first 24 to 36 hours light, drink water regularly, avoid strenuous activity on arrival and follow your trip captain’s acclimatisation advice. Roads are weather-led, so keep buffer time and carry warm layers even in peak summer.', idealDuration:'6 to 8 days', gettingThere:'Leh is reached by flight from major Indian cities. Road journeys via Srinagar or Manali are seasonal and usually best planned from late spring through early autumn, subject to local road updates.', localInsight:'Spend an unhurried evening around Leh market, try local Ladakhi food and visit a monastery early in the day. These quiet moments add as much character as Pangong Lake or Khardung La.' },
  spiti: { overview:'Spiti Valley is a dramatic cold-desert road trip where high mountains, old monasteries, tiny villages and star-filled nights set the rhythm. The classic circuit through Shimla, Kinnaur, Kaza, Key and Chandratal is ideal for travellers who enjoy long scenic drives and landscapes that change every few hours.', planningNotes:'This is a high-altitude route, so a gradual ascent is the safer and more comfortable way to travel. Mobile signal, fuel stations and medical services can be limited in remote stretches; keep cash, warm layers, a reusable bottle and a flexible approach to road closures.', idealDuration:'7 to 9 days', gettingThere:'Most first-time trips begin from Delhi and enter through Shimla and Kinnaur, returning via Manali when the Kunzum route is open. Shared cabs, private vehicles and curated group departures are the most practical ways to cover the circuit.', localInsight:'Wake up early in Kaza or a nearby village, speak with local hosts and slow down at a monastery. Spiti becomes memorable when you allow the landscape and village life to set the pace.' },
  manali: { overview:'Manali is an easy Himalayan escape that combines river valleys, snow views, adventure activities and a lively cafe culture. It can be a quick weekend break, a family holiday or the gateway to longer journeys toward Lahaul, Spiti and Ladakh.', planningNotes:'Travel time from Delhi or Chandigarh can be long on busy weekends, so overnight transfers or an extra night help keep the holiday relaxed. Snow conditions vary by month; pack waterproof shoes and warm layers for Solang or higher routes, while summer visitors should still carry a light jacket.', idealDuration:'3 to 5 days', gettingThere:'Manali is commonly reached by overnight Volvo, private car or cab from Delhi and Chandigarh. Bhuntar Airport is the nearest airport, followed by a mountain road transfer.', localInsight:'Old Manali is best explored on foot in the morning or early evening. Pair one active Solang day with a slower village, riverside or cafe day for a much better balance.' },
  kerala: { overview:'Kerala brings together tea-covered hills, backwaters, beaches, spice gardens and a deeply rooted food culture. Munnar, Thekkady, Alleppey, Kochi and Varkala can be combined into a relaxed route that feels varied without requiring difficult travel days.', planningNotes:'The state has distinct microclimates: hill stations can be cool and wet while the coast stays warm. Build in adequate road time between Munnar, Thekkady and Alleppey, carry light rain protection, and reserve houseboats or popular boutique stays early in peak season.', idealDuration:'5 to 7 days', gettingThere:'Kochi, Thiruvananthapuram and Kozhikode are the main air gateways. Private road transfers are the most comfortable way to connect hill country, backwaters and the coast.', localInsight:'Choose one experience that slows the route down—a spice walk, a local cooking session, a sunset canoe ride or an early tea-estate walk—rather than treating Kerala only as a checklist.' },
  meghalaya: { overview:'Meghalaya is a lush northeast journey of misty plateaus, limestone caves, clear rivers, waterfalls and living root bridges. Shillong, Cherrapunji, Dawki and Mawlynnong form a strong first route for travellers who want natural beauty, local culture and soft adventure.', planningNotes:'Weather changes quickly and monsoon rain can be intense, so waterproof footwear and a rain layer are useful almost year-round. Road distances may look short but hill driving is slow; plan one major experience per day and check local guidance before cave, river or trekking activities.', idealDuration:'5 to 7 days', gettingThere:'Guwahati is the primary gateway, with onward road transfers to Shillong and the Khasi and Jaintia Hills. Private cabs or organised group transfers are the most convenient option.', localInsight:'The Umngot River is most magical in softer morning light, while root-bridge walks are more enjoyable with a slower pace, local guide and time to understand the communities that protect them.' },
  bali: { overview:'Bali is a colourful island journey of rice terraces, temple rituals, surf-lined shores, dramatic cliffs and creative neighbourhoods. A balanced first itinerary pairs Ubud’s cultural heart with Nusa Penida, Uluwatu or Seminyak, leaving room for pool time and unplanned evenings.', planningNotes:'Bali is best enjoyed without changing hotels every night. Base yourself in one or two areas, allow for traffic between regions, dress respectfully at temples and carry reef-safe sun protection for beach and boat days. Check passport, visa and travel-insurance requirements before flying.', idealDuration:'6 to 8 days', gettingThere:'Ngurah Rai International Airport in Denpasar is Bali’s main arrival point. Private airport transfers and local drivers are convenient for day trips across the island.', localInsight:'A small local warung meal, sunrise around the rice terraces and a ceremony or temple visit with respectful dress offer a richer experience than rushing only between beach clubs and photo spots.' },
  thailand: { overview:'Thailand is an energetic mix of street food, ornate temples, tropical beaches, island hopping and easy-going social evenings. Bangkok, Krabi, Phuket and nearby islands work well together for a first trip that blends city culture with coast time.', planningNotes:'Plan flights and island transfers with breathing room, especially in wet-season months. Keep lightweight clothing, sun protection and modest temple-covering layers ready. Visa, passport validity and entry conditions should be verified before departure.', idealDuration:'5 to 7 days', gettingThere:'Bangkok is the main international gateway, with domestic flights and road transfers connecting Phuket, Krabi and other beach regions. Airport-to-hotel transfers are easily arranged in advance.', localInsight:'Make time for an evening food market and a quieter long-tail boat outing. Thailand feels more memorable when one part of the itinerary is deliberately slower than the nightlife and sightseeing schedule.' },
  nepal: { overview:'Nepal combines Himalayan panoramas, ancient temple towns, lakeside Pokhara and welcoming mountain culture. Kathmandu, Bhaktapur, Nagarkot and Pokhara make an accessible first journey, while trekkers can extend the route into Annapurna or Everest-region trails with the right preparation.', planningNotes:'Check passport, visa and travel-insurance requirements before booking. Mountain weather changes quickly, so itinerary buffers and layered clothing matter even outside winter. For higher treks, choose experienced local support and allow enough time for acclimatisation.', idealDuration:'5 to 8 days', gettingThere:'Kathmandu’s Tribhuvan International Airport is the primary gateway. Overland entry is also possible through selected India–Nepal border points, followed by private road transfers or domestic flights.', localInsight:'Beyond the postcard mountain views, walk the heritage lanes of Bhaktapur, try a local Newari meal and give Pokhara an extra sunset evening by the lake.' },
  'spiti-winter': { overview:'A Winter Spiti trip is for travellers who want the quiet, snow-covered side of the Himalayas. The route is weather-led, so the experience is planned around acclimatisation, reliable stays and enough buffer for changing road conditions.', planningNotes:'Winter travel works best with a flexible mindset. Keep an extra day in hand, choose warm layered clothing and follow local road guidance rather than treating the itinerary as fixed.', idealDuration:'6 to 8 days', gettingThere:'Usually approached from Shimla through the lower Kinnaur route, subject to local road and weather conditions.', localInsight:'Winter villages are calm and services can be limited; travelling with a local support team makes planning far easier.' },
  kashmir: { overview:'Kashmir brings together alpine meadows, lake life, Mughal-era gardens and mountain villages in one memorable Himalayan holiday. A well-paced route leaves room for Srinagar, Gulmarg, Pahalgam and the slower moments in between.', planningNotes:'Pack layers for cool evenings even in summer, keep photo ID handy for hotel check-in, and leave room in the schedule for weather-related changes in higher areas.', idealDuration:'5 to 7 days', gettingThere:'Srinagar is the usual gateway, with onward road transfers to Gulmarg, Pahalgam and nearby valleys.', localInsight:'A shikara ride, a walk through old Srinagar and a meal featuring Kashmiri flavours make the journey feel more rooted than a quick sightseeing loop.' },
  uttarakhand: { overview:'Uttarakhand is made for mountain road trips, riverside breaks and temple-town culture. From Mussoorie and Nainital to Rishikesh, Auli and quieter hill villages, it can be shaped into a relaxed family holiday or an active escape.', planningNotes:'Hill drives take longer than maps suggest. Start early, carry light rain protection in the monsoon months, and keep your plan flexible around road and weather updates.', idealDuration:'4 to 8 days', gettingThere:'Delhi is a common starting point, with rail and road connections through Dehradun, Haridwar, Kathgodam and Rishikesh.', localInsight:'The best routes combine one iconic stop with a smaller village or forest stay, rather than trying to cover the whole state in a few days.' },
  himachal: { overview:'Himachal Pradesh offers an easy mix of snow peaks, cedar forests, café towns and road-trip views. Manali, Shimla, Dharamshala, Kasol and Jibhi each have a distinct pace, making the state ideal for repeat travel.', planningNotes:'Choose a compact circuit instead of overloading the route. Mountain weather changes quickly, so warm layers and a weather-aware driving plan matter across seasons.', idealDuration:'4 to 7 days', gettingThere:'Most trips begin from Delhi or Chandigarh, with road connections into the Kullu, Shimla and Kangra regions.', localInsight:'Early mornings are best for scenic drives; evenings are better reserved for local cafés, village walks or simply slowing down.' },
  andaman: { overview:'Andaman is a sea-and-islands escape built around clear water, relaxed beach time and marine experiences. Port Blair, Havelock and Neil Island combine well when ferry timings are planned carefully from the start.', planningNotes:'Ferries and water activities are weather-sensitive, so avoid a tightly packed itinerary. Carry sun protection, quick-dry clothing and valid government photo ID for island transfers.', idealDuration:'5 to 7 days', gettingThere:'Port Blair is the main arrival point, followed by scheduled inter-island ferries.', localInsight:'Keep one unplanned sunset evening on Havelock or Neil Island—those slower hours are often the highlight of the trip.' },
  rajasthan: { overview:'Rajasthan pairs grand forts and palaces with desert landscapes, craft traditions and some of India’s most characterful cities. Jaipur, Jodhpur, Udaipur and Jaisalmer can be combined into a cultural route with a strong sense of place.', planningNotes:'Days can be warm for much of the year, so plan outdoor sightseeing for mornings and late afternoons. Comfortable walking shoes are useful for forts, bazaars and old-city lanes.', idealDuration:'5 to 8 days', gettingThere:'Jaipur, Jodhpur and Udaipur have convenient air and rail connections; private road transfers link the classic circuit.', localInsight:'Add a local craft, food or heritage walk to balance landmark sightseeing with the everyday culture of each city.' },
  vietnam: { overview:'Vietnam rewards travellers with a contrast of old quarters, limestone scenery, lantern-lit towns, coffee culture and a remarkable food trail. Hanoi, Ha Long Bay, Da Nang and Hoi An create a natural first-time circuit.', planningNotes:'Build in breathing room between domestic transfers, keep an international card or local currency ready for small purchases, and check entry and visa requirements before booking flights.', idealDuration:'6 to 9 days', gettingThere:'Hanoi and Ho Chi Minh City are the main international gateways, with domestic flights and road transfers connecting regional stops.', localInsight:'A street-food walk and an unhurried evening in Hoi An add more depth than rushing between photo stops.' },
  'sri-lanka': { overview:'Sri Lanka fits tea-country rail views, wildlife, colonial-era towns and tropical beaches into one compact island journey. The classic route connects Colombo or Negombo, Kandy, Ella, the southern coast and a national park.', planningNotes:'Use a paced route because mountain roads and train journeys take time. Check visa requirements before departure and carry a light rain layer alongside beachwear.', idealDuration:'6 to 9 days', gettingThere:'Colombo is the primary gateway, followed by private transfers or scenic rail segments across the island.', localInsight:'The Kandy–Ella train is best experienced as part of the journey, not as a rushed transfer between two packed sightseeing days.' },
  bhutan: { overview:'Bhutan is a thoughtful Himalayan journey of dzongs, prayer flags, forest trails and quietly beautiful valleys. Thimphu, Punakha and Paro are a strong first itinerary for travellers who value culture and a slower pace.', planningNotes:'Travel formalities, entry permits and daily travel rules should be checked well before booking. Respectful clothing for monasteries and comfortable footwear for uneven paths are essential.', idealDuration:'5 to 7 days', gettingThere:'Paro is the main air gateway; road entry is also possible for eligible travellers through designated border points.', localInsight:'Leave time for a monastery visit or a short valley walk—Bhutan is best absorbed slowly, not ticked off quickly.' },
  dubai: { overview:'Dubai blends city-scale architecture, desert landscapes, beach clubs, malls and international dining in a compact, easy-to-navigate holiday. It works equally well as a short city break or as a stop combined with nearby Abu Dhabi.', planningNotes:'Reserve major experiences ahead during busy travel periods, dress for warm weather, and keep your passport and visa arrangements in order before departure.', idealDuration:'4 to 6 days', gettingThere:'Dubai International Airport is the main gateway, with city transfers by metro, taxi and private vehicle.', localInsight:'Balance the skyline with a desert sunset or creek-side evening for a more rounded experience of the city.' },
  maldives: { overview:'The Maldives is ideal for travellers who want a calm island stay centred on clear lagoons, house reefs and time to switch off. Choosing the right island or resort matters more than trying to move around frequently.', planningNotes:'Review transfer type and timings before booking, pack reef-safe sun protection, and confirm what meals, water activities and transfers are included in your stay.', idealDuration:'4 to 6 nights', gettingThere:'International arrivals land in Malé, followed by speedboat or seaplane transfers arranged by the property.', localInsight:'A few planned water activities plus generous free time is usually more rewarding than an over-scheduled island itinerary.' },
  singapore: { overview:'Singapore is a polished, high-energy city break with gardens, waterfront walks, neighbourhood food centres and family-friendly attractions. It is easy to navigate and pairs naturally with Sentosa, Marina Bay and cultural districts.', planningNotes:'Keep lightweight rain protection for quick tropical showers, use contactless payment where possible and reserve sought-after attractions in advance during peak dates.', idealDuration:'4 to 5 days', gettingThere:'Changi Airport connects directly to the city by taxi, rail and private transfer.', localInsight:'Hawker centres and neighbourhood walks around Kampong Glam, Chinatown or Little India reveal a more local side beyond the headline attractions.' },
  rishikesh: { overview:'Rishikesh is a quick reset built around the Ganga, yoga, cafés and Himalayan foothills. It suits first-time solo travellers, friend groups and anyone looking to pair easy adventure with a slower riverside rhythm.', planningNotes:'River activities depend on seasonal water conditions. Pack modest, comfortable clothing for ashram or temple visits and avoid overcommitting the short itinerary.', idealDuration:'2 to 4 days', gettingThere:'Rishikesh is reached easily from Delhi via Haridwar or Dehradun by rail and road.', localInsight:'Sunrise by the river and an evening aarti are often more memorable than trying to fit every adventure activity into one weekend.' },
  jibhi: { overview:'Jibhi is a gentle Himachal escape of cedar forests, wooden homes, waterfalls and quiet village lanes. It is best for travellers who prefer slow mornings, scenic drives and low-key mountain time over crowded resort towns.', planningNotes:'Connectivity can be patchy in nearby villages, so download maps and carry cash for small local purchases. Warm layers are useful throughout much of the year.', idealDuration:'3 to 4 days', gettingThere:'Most travellers arrive by road from Delhi or Chandigarh via Aut, Banjar and the Tirthan Valley region.', localInsight:'Keep your itinerary intentionally light—Jibhi’s appeal is the unhurried atmosphere, forest walks and homestay-style hospitality.' },
  chopta: { overview:'Chopta is a high-altitude meadow region known for big Himalayan views, simple stays and the Chandrashila–Tungnath trail. It is a rewarding short mountain escape for travellers comfortable with basic conditions.', planningNotes:'Weather changes fast and temperatures drop sharply after sunset. Carry sturdy shoes, warm layers, a reusable water bottle and allow buffer time for road conditions.', idealDuration:'3 to 5 days', gettingThere:'Road journeys typically route through Rishikesh, Rudraprayag and Ukhimath before reaching Chopta.', localInsight:'Start the Tungnath or Chandrashila walk early for clearer views and a less crowded trail experience.' },
  coorg: { overview:'Coorg offers coffee estates, misty roads, forest viewpoints and a comfortable slower pace in Karnataka’s Western Ghats. It works well for couples, families and Bangalore-based weekend travellers.', planningNotes:'Monsoon brings lush landscapes and frequent rain, while drier months are better for long outdoor days. Pack comfortable shoes for estate walks and viewpoint trails.', idealDuration:'3 to 4 days', gettingThere:'The journey is usually by road from Bengaluru or Mysuru, with the nearest major airports in those cities.', localInsight:'An estate stay, local Kodava meal and early-morning drive through the hills give Coorg more character than a checklist of viewpoints.' },
};
export const destinations = [
  ['Ladakh','ladakh','domestic',19499,'May to September','High passes, blue lakes and unforgettable Himalayan roads',['Pangong Lake','Nubra Valley','Khardung La'],['Bike through mountain passes','Visit monasteries','Camp near Pangong']],
  ['Spiti Valley','spiti','domestic',17999,'May to October','Ancient monasteries and stark high-altitude landscapes',['Kaza','Key Monastery','Chandratal Lake'],['Drive the full circuit','Stargaze in remote villages','Explore fossil villages']],
  ['Manali','manali','domestic',9499,'October to June','A quick Himalayan escape for snow, cafés and adventure',['Solang Valley','Atal Tunnel','Old Manali'],['Try snow activities','Explore local cafés','Visit mountain villages']],
  ['Kerala','kerala','domestic',14999,'September to March','Backwaters, tea gardens and a slower tropical rhythm',['Munnar','Alleppey','Varkala'],['Stay on a houseboat','Walk through tea estates','Watch a coastal sunset']],
  ['Meghalaya','meghalaya','domestic',15499,'October to April','Living root bridges, clear rivers and rain-washed forests',['Shillong','Dawki','Cherrapunji'],['Walk a living root bridge','Boat on the Umngot','Chase waterfalls']],
  ['Bali','bali','international',44999,'April to October','Temples, island adventures and vibrant tropical culture',['Ubud','Nusa Penida','Uluwatu'],['Sunrise at Mount Batur','Island hopping','Explore temples']],
  ['Thailand','thailand','international',32999,'November to March','Tropical islands, street food and legendary nightlife',['Bangkok','Krabi','Phuket'],['Long-tail boat tour','Explore night markets','Visit island beaches']],
  ['Nepal','nepal','international',29999,'March to May, September to November','Himalayan views, heritage towns and welcoming mountain culture',['Kathmandu','Pokhara','Annapurna'],['Watch an Himalayan sunrise','Explore heritage squares','Walk a mountain trail']],
  ['Winter Spiti','spiti-winter','domestic',21999,'January to March','Snowbound villages, Himalayan silence and a rare cold-desert journey',['Kaza','Key Monastery','Kinnaur valleys'],['Watch the winter landscape','Visit monasteries respectfully','Stargaze on clear nights']],
  ['Kashmir','kashmir','domestic',18999,'April to October','Lakes, meadows and mountain valleys with a timeless cultural rhythm',['Srinagar','Gulmarg','Pahalgam'],['Shikara ride on Dal Lake','Explore meadow trails','Visit old Srinagar']],
  ['Uttarakhand','uttarakhand','domestic',8999,'March to June, September to November','River towns, Himalayan drives and forested hill escapes',['Rishikesh','Mussoorie','Auli'],['Walk by the Ganga','Take a hill drive','Explore mountain villages']],
  ['Himachal Pradesh','himachal','domestic',7999,'March to June, September to December','Cedar forests, café towns and Himalayan road-trip views',['Manali','Shimla','Dharamshala'],['Explore Old Manali','Visit hill cafés','Drive through mountain passes']],
  ['Andaman','andaman','domestic',27999,'October to April','Blue-water islands, coral experiences and unhurried beach days',['Havelock','Neil Island','Port Blair'],['Island ferry ride','Snorkel in clear water','Watch a beach sunset']],
  ['Rajasthan','rajasthan','domestic',13499,'October to March','Forts, desert sunsets and rich food-and-craft traditions',['Jaipur','Jodhpur','Udaipur'],['Explore heritage forts','Shop local crafts','Experience a desert evening']],
  ['Vietnam','vietnam','international',49999,'February to April, August to October','Old quarters, coastlines and a vivid food-and-culture trail',['Hanoi','Ha Long Bay','Hoi An'],['Cruise limestone bays','Try local food','Walk lantern-lit streets']],
  ['Sri Lanka','sri-lanka','international',38999,'December to April','Tea-country rail views, wildlife and tropical coastal stays',['Kandy','Ella','Galle'],['Take a scenic train','Visit tea estates','Relax on the southern coast']],
  ['Bhutan','bhutan','international',34999,'March to May, September to November','Peaceful Himalayan valleys, monastery culture and forest trails',['Paro','Thimphu','Punakha'],['Visit dzongs','Walk valley trails','See the Tiger’s Nest region']],
  ['Dubai','dubai','international',54999,'November to March','Skyline experiences, desert evenings and a vibrant city break',['Downtown Dubai','Desert Reserve','Dubai Marina'],['See the skyline','Try a desert safari','Walk the marina']],
  ['Maldives','maldives','international',64999,'November to April','Lagoon stays, reef experiences and effortless island downtime',['Malé Atolls','House reefs','Island resorts'],['Snorkel a house reef','Take a sunset cruise','Relax by the lagoon']],
  ['Singapore','singapore','international',58999,'February to April','Gardens, waterfront neighbourhoods and world-class city experiences',['Marina Bay','Sentosa','Chinatown'],['Explore Gardens by the Bay','Visit Sentosa','Try hawker food']],
  ['Rishikesh','rishikesh','domestic',5999,'September to April','Riverside stays, yoga and easy Himalayan adventure',['Laxman Jhula area','Ganga ghats','Shivpuri'],['Join an aarti','Try rafting in season','Unwind by the river']],
  ['Jibhi','jibhi','domestic',6499,'March to June, September to November','Cedar forests, quiet lanes and a slow Himachal reset',['Jibhi Waterfall','Tirthan Valley','Jalori Pass'],['Walk forest trails','Visit the waterfall','Stay in a mountain homestay']],
  ['Chopta','chopta','domestic',6999,'April to June, September to November','Meadow landscapes and high Himalayan trekking views',['Tungnath','Chandrashila','Ukhimath'],['Trek to Tungnath','Watch a Himalayan sunrise','Explore alpine meadows']],
  ['Coorg','coorg','domestic',9999,'October to March','Coffee estates, misty hills and a relaxed Western Ghats escape',['Madikeri','Abbey Falls','Coffee estates'],['Walk an estate','Visit waterfalls','Try Kodava cuisine']],
].map(([name,slug,category,startingPrice,bestTime,tagline,highlights,thingsToDo]) => {
  const profile = destinationProfiles[slug] || {};
  const summary = profile.summary || `Discover ${name} with transparent inclusions, handpicked stays and experienced TravelEnfield trip captains.`;
  return { name,slug,category,startingPrice,bestTime,tagline,summary,image:img(destinationImage[slug] || slug),seoTitle:`${name} Tour Packages | Best Time, Places & Travel Guide`,seoDescription:`Plan a ${name} trip with destination highlights, things to do, best time to visit and practical travel advice from TravelEnfield.`,overview:profile.overview || `${name} offers a well-rounded journey for travellers looking for meaningful experiences, local flavour and time to explore at an easy pace. Our trip planning balances major highlights with practical routing, comfortable stays and room for the moments that make a holiday personal.`,planningNotes:profile.planningNotes || `Plan around the season, keep your schedule realistic and check current local conditions before travel. Comfortable layers, valid photo ID and a little flexibility will make the journey smoother.`,idealDuration:profile.idealDuration || '4 to 6 days',gettingThere:profile.gettingThere || 'Travel options depend on your starting city and chosen route. Our trip experts can help arrange a practical arrival and transfer plan.',localInsight:profile.localInsight || `The best ${name} journeys leave space for local food, everyday neighbourhoods and unplanned discoveries alongside the key highlights.`,highlights,thingsToDo,travelTips:['Carry a valid government photo ID','Pack for the season and check the local forecast','Respect local culture, wildlife and community spaces','Keep one flexible buffer period in your itinerary'],faq:[...commonFaq(name),{question:`How many days are enough for a ${name} trip?`,answer:`For a well-paced first visit, plan ${profile.idealDuration || '4 to 6 days'}. Your ideal duration depends on arrival time, preferred experiences and whether you want a relaxed or activity-led itinerary.`}] };
});

const itinerary = names => names.map((title, i) => ({ day:i+1,title,details:[`Experience ${title} with your trip captain.`, 'Meals, transfers and stay follow the inclusions listed below.'] }));
const baseTrips = [
  {title:'Leh Ladakh Bike Trip',slug:'leh-ladakh-bike-trip',destinationSlug:'ladakh',categories:['all','upcoming','domestic','bike-trips'],image:cdn('https://res.cloudinary.com/dq3typk9u/image/upload/v1786542549/travelenfield/categories/bike-trips.jpg'),duration:'6 nights / 7 days',nights:6,price:19499,oldPrice:24999,discount:'22% Off',badge:'Free Goodies',summary:'Ride across iconic high passes and remote valleys on a supported Himalayan motorcycle journey.',groupSize:'12–20 travellers',pickup:'Leh Airport',dates:['Aug 15','Aug 22','Sep 5','Sep 12'],itinerary:itinerary(['Arrival and acclimatisation in Leh','Leh local exploration','Leh to Nubra Valley','Nubra to Pangong Lake','Pangong to Leh','Buffer and celebration','Departure']),featured:true},
  {title:'Spiti Valley Road Trip',slug:'spiti-valley-road-trip',destinationSlug:'spiti',categories:['all','upcoming','domestic','backpacking-trips','bike-trips'],image:img('spiti'),duration:'7 nights / 8 days',nights:7,price:17999,oldPrice:22999,discount:'22% Off',badge:'Bestseller',summary:'A high-altitude road trip through monasteries, villages and dramatic cold-desert landscapes.',groupSize:'12–18 travellers',pickup:'Delhi',dates:['Aug 20','Sep 1','Sep 15','Oct 2'],itinerary:itinerary(['Delhi to Shimla','Shimla to Chitkul','Chitkul to Kalpa','Kalpa to Kaza','Kaza local circuit','Kaza to Chandratal','Chandratal to Manali','Departure']),featured:true},
  {title:'Bali Adventure Tour',slug:'bali-adventure-tour',destinationSlug:'bali',categories:['all','upcoming','international'],image:img('bali'),duration:'5 nights / 6 days',nights:5,price:44999,oldPrice:54999,discount:'18% Off',badge:'Free Goodies',summary:'A balanced Bali escape with temples, waterfalls, island views and social evenings.',groupSize:'10–18 travellers',pickup:'Denpasar Airport',dates:['Sep 10','Sep 24','Oct 8','Oct 22'],itinerary:itinerary(['Arrival in Bali','Ubud culture trail','Nusa Penida day trip','Mount Batur sunrise','Uluwatu and leisure','Departure']),featured:true},
  {title:'Thailand Beach Getaway',slug:'thailand-beach-getaway',destinationSlug:'thailand',categories:['all','upcoming','international'],image:img('thailand'),duration:'5 nights / 6 days',nights:5,price:32999,oldPrice:39999,discount:'18% Off',badge:'Trending',summary:'Island scenery, bustling markets and a fun group itinerary across Thailand.',groupSize:'10–18 travellers',pickup:'Bangkok Airport',dates:['Sep 5','Sep 19','Oct 3','Oct 17'],itinerary:itinerary(['Bangkok arrival','Bangkok city highlights','Fly to Krabi','Island hopping','Leisure and night market','Departure'])},
  {title:'Manali Snow Adventure',slug:'manali-snow-adventure',destinationSlug:'manali',categories:['all','upcoming','domestic','weekend','bike-trips'],image:img('manali'),duration:'3 nights / 4 days',nights:3,price:9499,oldPrice:12999,discount:'27% Off',badge:'Weekend Pick',summary:'A compact mountain break with snow activities, cafés and scenic drives.',groupSize:'12–24 travellers',pickup:'Delhi',dates:['Aug 10','Aug 17','Aug 24','Aug 31'],itinerary:itinerary(['Delhi to Manali','Solang Valley adventure','Old Manali and local sights','Return to Delhi'])},
  {title:'Meghalaya Explorer',slug:'meghalaya-explorer',destinationSlug:'meghalaya',categories:['all','upcoming','domestic','backpacking-trips','bike-trips'],image:img('meghalaya'),duration:'5 nights / 6 days',nights:5,price:15499,oldPrice:19999,discount:'23% Off',badge:'New',summary:'Clear rivers, forest trails and living root bridges in India’s northeast.',groupSize:'10–18 travellers',pickup:'Guwahati Airport',dates:['Sep 8','Sep 22','Oct 6','Oct 20'],itinerary:itinerary(['Guwahati to Shillong','Cherrapunji waterfalls','Living root bridge trek','Dawki and Mawlynnong','Shillong local day','Departure'])},
];

const generatedDestinationTrips = destinations.flatMap((destination, index) => {
  const category = destination.category === 'international' ? 'international' : 'domestic';
  const basePrice = Number(destination.startingPrice) || 9999;
  const firstHighlight = destination.highlights?.[0] || destination.name;
  const secondHighlight = destination.highlights?.[1] || 'local experiences';
  const firstActivity = destination.thingsToDo?.[0] || `Explore ${destination.name}`;
  const secondActivity = destination.thingsToDo?.[1] || 'Enjoy a relaxed local experience';
  const departures = index % 2 === 0 ? ['Sep 6', 'Sep 20', 'Oct 4'] : ['Sep 13', 'Sep 27', 'Oct 11'];
  const makeTrip = (variant, priceOffset, badge) => ({
    title: `${destination.name} ${variant}`,
    slug: `${destination.slug}-${variant.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
    destinationSlug: destination.slug,
    categories: ['all', 'upcoming', category],
    image: destination.image,
    duration: destination.idealDuration || '5 nights / 6 days',
    nights: 5,
    price: basePrice + priceOffset,
    oldPrice: basePrice + priceOffset + 4000,
    discount: 'Early Bird Offer',
    badge,
    summary: `${destination.tagline} A thoughtfully paced ${destination.name} group departure with stays, transfers and on-ground support.`,
    groupSize: '10–18 travellers',
    pickup: `${destination.name} arrival point`,
    dates: departures,
    itinerary: itinerary([`Arrive and settle into ${destination.name}`, `Explore ${firstHighlight}`, firstActivity, `Discover ${secondHighlight}`, secondActivity, 'Departure with new stories']),
  });
  return [
    makeTrip('Highlights Group Tour', 0, 'Group Departure'),
    makeTrip('Explorer Group Tour', 2500, 'Traveller Favourite'),
  ];
});

export const trips = [...baseTrips, ...generatedDestinationTrips].map(t => ({...t,inclusions:['Comfortable stays on sharing basis','Transfers as per itinerary','Trip captain throughout the journey','Experiences specifically mentioned'],exclusions:['Flights unless explicitly mentioned','Personal expenses and tips','Meals not listed in the itinerary','GST and applicable taxes'],notes:['Carry a valid photo ID.','Final schedule may change due to weather or local conditions.']}));

export const hotels = [
  ['The Grand Dragon, Leh','the-grand-dragon-leh','ladakh','Leh, Ladakh','4','4.8','412','Bestseller','Mountain-view stay near Leh city','Sumptuous rooms with warm hospitality right in the heart of Ladakh’s capital.','7499','9999','Premium Mountain Room',['Breakfast included','Free WiFi','Oxygen support','In-house café','Airport pickup','Heated rooms'],['Heated rooms with mountain views','Gurudwara Pathar Sahib close by','Popular with group trips','Free airport transfer'],['3.2 km from Leh Airport','Walk to Leh Main Market','20 min to Shanti Stupa'],['Deluxe Mountain Room','2 adults','22 m²','Queen bed','Mountain view',['Breakfast','Heating','Hill view balcony'],'7499','9999','Premium Mountain Room','2 adults','30 m²','King bed','Panoramic valley view',['Breakfast','Heating','Minibar','Balcony'],'9499','12499','Family Suite','4 adults','46 m²','2 Queen beds','Valley + hill view',['Breakfast','Heating','Living area'],'12499','15999'],'14:00','12:00','Free cancellation up to 7 days before check-in',['Is breakfast included in the room rate?','Yes, a vegetarian spread is included for all stays.','Do you help with permits for travellers?','Yes, our front desk assists group trip travellers with permit paperwork.','Is there oxygen support on site?','The property has supplemental oxygen and a clinic on call.']],
  ['The Kaza Stays, Spiti Valley','the-kaza-stays-spiti','spiti','Kaza, Spiti','4','4.9','287','Traveller Favourite','Cosy village stay under star-filled skies','Simple, warm rooms with solar hot water and the best homestyle food in Spiti.','6499','8499','Mountain View Room',['Breakfast & dinner','Solar heating','Free WiFi','Bonfire evenings','Guided walks'],['Star-gazing terrace','Fresh Himalayan food','Supports local families','Bonfire every evening'],['2.1 km from Kaza Bus Stand','Next to Key Monastery road','8 min to Kaza main market'],['Mountain View Room','2 adults','18 m²','Queen bed','Village & peak view',['Breakfast + dinner','Solar heating'],'6499','8499','Courtyard Deluxe','2 adults','24 m²','Queen bed','Courtyard view',['All meals','Fireplace'],'7999','10499','Family Suite','5 adults','40 m²','3 Queen beds','Valley view',['All meals','Private sit-out'],'11999','15499'],'13:30','11:30','Free cancellation up to 3 days before check-in',['Is the water heated by solar?','Yes, solar heating is available in the morning and evening.','Do you arrange local taxis?','We arrange shared taxis to key monasteries and Chandratal.']],
  ['Solang Valley Resort, Manali','solang-valley-resort-manali','manali','Solang, Manali','3','4.6','531','Weekend Pick','Cosy rooms with snow views near Solang','A warm, well-priced retreat minutes from Manali’s best adventure spots.','5499','7299','Superior Valley Room',['Breakfast included','Free WiFi','In-house restaurant','Bonfire nights','Adventure desk'],['5 min from Solang adventure zone','Snow-view balconies','Adventure activity desk','Parking for bikers'],['5.2 km from Solang Valley','1.2 km from Old Manali','8 km from Atal Tunnel'],['Superior Valley Room','2 adults','20 m²','Queen bed','Valley view',['Breakfast','Balcony'],'5499','7299','Premium Snow View','2 adults','26 m²','King bed','Snow-capped peaks',['Breakfast','Heating'],'6499','8799','Family Cottage','5 adults','42 m²','2 Queen beds','River & valley view',['Breakfast','Fireplace','Garden'],'9999','12999'],'14:00','11:00','Free cancellation up to 24 hours before check-in',['Is parking available for bikes?','Yes, secure covered parking is available for motorcycle trips.','Do rooms have heating?','Premium rooms and cottages include heaters in winter.']],
  ['Spice Tree Munnar, Kerala','spice-tree-munnar-kerala','kerala','Munnar, Kerala','4','4.7','398','Couples Choice','Tea-garden cottages wrapped in mist','Stay between cardamom plantations and rolling tea estates with private balconies.','6499','8499','Tea Estate Cottage',['Breakfast included','Free WiFi','Plantation walks','Bonfire on request','Ayurvedic spa'],['Tea-garden views from every room','Guided plantation walk','Spa and wellness corner','Popular with couples'],['9 km from Munnar town','1 km to tea gardens','Near Eravikulam road'],['Tea Estate Cottage','2 adults','24 m²','Queen bed','Tea garden view',['Breakfast','Balcony'],'6499','8499','Plantation Suite','2 adults','34 m²','King bed','Cardamom valley view',['Breakfast','Bathtub'],'8999','11499','Family Villa','4 adults','52 m²','2 King beds','Private garden',['Breakfast','Living room'],'12999','16499'],'14:00','11:00','Free cancellation up to 3 days before check-in',['Do you arrange plantation tours?','Yes, guided walks can be booked at the front desk.','Is the spa included?','Wellness treatments are available at an extra charge.']],
  ['Ri Kynjai, Shillong','ri-kynjai-shillong','meghalaya','Shillong, Meghalaya','4','4.8','246','New','Lakeside retreat above Umiam Lake','A serene stay with dramatic lake views, local food and warm Khasi hospitality.','7999','10499','Lake View Room',['Breakfast included','Free WiFi','In-house restaurant','Lake activities','Fireplace lounge'],['Panoramic Umiam Lake views','Local Khasi cuisine','Kayaking & boating desk','Near Umiam viewpoint'],['15 km from Shillong city','5 min from Umiam Lake','2 km from Umiam viewpoint'],['Lake View Room','2 adults','26 m²','Queen bed','Umiam Lake view',['Breakfast','Balcony'],'7999','10499','Deluxe Lake Suite','2 adults','36 m²','King bed','Full lake panorama',['Breakfast','Bathtub'],'10499','13499','Family Lake House','4 adults','55 m²','2 King beds','Lake + hill view',['Breakfast','Living area'],'14499','18499'],'14:00','11:00','Free cancellation up to 7 days before check-in',['Can we do water activities nearby?','Kayaking and boating are available on Umiam Lake nearby.','Is the property accessible by car?','Yes, the resort has dedicated parking and a scenic drive approach.']],
  ['Aksari Villa, Ubud','aksari-villa-ubud-bali','bali','Ubud, Bali','5','4.9','364','Luxury','Private pool villas in the rice fields','Tranquil pool villas surrounded by jungle and rice terraces, minutes from Ubud’s culture.','11499','15499','Pool Access Villa',['Breakfast included','Free WiFi','Private pool','Airport transfer','Spa services'],['Private pool villa','Rice terrace views','Daily yoga on request','10 min to Ubud market'],['4 km from Ubud Palace','15 min to Monkey Forest','Close to Tegalalang terraces'],['Pool Access Villa','2 adults','40 m²','King bed','Rice terrace view',['Breakfast','Private pool'],'11499','15499','Jungle Villa','2 adults','52 m²','King bed','Jungle view',['Breakfast','Private pool','Outdoor bath'],'13999','18499','Family Pool Villa','4 adults','90 m²','2 King beds','Rice terrace + pool',['Breakfast','Private pool','Butler service'],'20999','27499'],'14:00','12:00','Free cancellation up to 7 days before check-in',['Is there a shuttle to Ubud centre?','Yes, a complimentary shuttle runs to Ubud centre three times a day.','Are villas family friendly?','Yes, the family pool villa is set up for two adults and two children.']],
  ['Amari Phuket, Thailand','amari-phuket-thailand','thailand','Phuket, Thailand','5','4.8','672','Trending','Beachfront rooms with sea views','Modern beachfront stay on Patong Beach with a sunset rooftop pool.','9499','12999','Deluxe Sea View',['Breakfast included','Free WiFi','Rooftop pool','Gym','Beach access'],['Direct Patong Beach access','Rooftop infinity pool','Sunsets from the terrace','Walkable nightlife'],['On Patong Beach','5 min to Bangla Road','45 min from Phuket Airport'],['Deluxe Sea View','2 adults','30 m²','King bed','Sea view',['Breakfast','Balcony'],'9499','12999','Premier Ocean Suite','2 adults','48 m²','King bed','Panoramic ocean view',['Breakfast','Lounge access'],'12999','16999','Beachfront Family Room','4 adults','60 m²','2 Queen beds','Beachfront view',['Breakfast','Kids welcome'],'16999','21999'],'14:00','12:00','Free cancellation up to 5 days before check-in',['Is breakfast included?','Yes, a buffet breakfast is included for all room categories.','Is the rooftop pool open to all guests?','Yes, the rooftop infinity pool is open to all in-house guests.']],
  ['Tiger Mountain Pokhara, Nepal','tiger-mountain-pokhara-nepal','nepal','Pokhara, Nepal','4','4.7','312','Couples Choice','Sunrise-facing rooms over the lake','A hillside boutique stay with sunrise views across Phewa Lake and the Annapurna range.','6999','9299','Annapurna View Room',['Breakfast included','Free WiFi','Rooftop restaurant','Sunrise deck','Bicycle hire'],['Annapurna sunrise view','Steps from Phewa Lake','Bicycle & kayak hire','Local heritage feel'],['2.5 km from Lakeside','On Phewa Lake','Near World Peace Pagoda ferry'],['Annapurna View Room','2 adults','24 m²','Queen bed','Annapurna + lake view',['Breakfast','Balcony'],'6999','9299','Lakefront Suite','2 adults','38 m²','King bed','Phewa Lake frontage',['Breakfast','Sit-out'],'9499','12499','Family Suite','4 adults','50 m²','2 Queen beds','Mountain + lake view',['Breakfast','Living area'],'12499','15999'],'13:00','11:00','Free cancellation up to 4 days before check-in',['Do you arrange sunrise paragliding?','Yes, we help book paragliding and sunrise activities at the desk.','Is breakfast vegetarian friendly?','Absolutely, a vegetarian menu is available every morning.']],
].map(([name,slug,destinationSlug,location,star,rating,reviews,badge,tagline,summary,pricePerNight,oldPricePerNight,roomType,amenities,highlights,nearby,rooms,policiesCheckIn,policiesCheckOut,policiesCancellation,faq]) => {
  const image=cdn(`/images/destinations/${destinationSlug}.jpg`);
  const chunk=(arr,n)=>{const out=[];for(let i=0;i<arr.length;i+=n)out.push(arr.slice(i,i+n));return out;};
  return {name,slug,destinationSlug,location,star:Number(star),rating:Number(rating),reviews:Number(reviews),badge,tagline,summary,pricePerNight:Number(pricePerNight),oldPricePerNight:Number(oldPricePerNight),roomType,image,gallery:[image,cdn('https://res.cloudinary.com/dq3typk9u/image/upload/v1786542569/travelenfield/social-banner.jpg'),cdn('https://res.cloudinary.com/dq3typk9u/image/upload/v1786542561/travelenfield/hero.jpg'),cdn('https://res.cloudinary.com/dq3typk9u/image/upload/v1786542559/travelenfield/group-trips-himalaya-hero.jpg')],amenities,highlights,nearby,rooms:chunk(rooms,8).map(([roomName,occupancy,size,bed,view,perks,price,oldPrice],index)=>({id:`${slug}-r${index+1}`,name:roomName,occupancy,size,bed,view,perks:perks||[],price:Number(price),oldPrice:Number(oldPrice)})),policies:{checkIn:policiesCheckIn,checkOut:policiesCheckOut,cancellation:policiesCancellation},faq:Array.from({length:Math.floor(faq.length/2)},(_,i)=>({question:faq[i*2],answer:faq[i*2+1]})),featured:['bestseller','traveller favourite'].some(x=>x===badge.toLowerCase())};
});

export const categoryData = [
  ['All Trips','trips','Explore all TravelEnfield trips','Compare curated departures across India and international destinations.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542561/travelenfield/hero.jpg','Find your next story'],
  ['Upcoming Group Trips','upcoming-trips','Upcoming group departures','Meet like-minded travellers on fixed-date journeys led by experienced captains.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542569/travelenfield/social-banner.jpg','Fixed dates, effortless planning'],
  ['Domestic Trips','domestic-trips','Explore India','From Himalayan roads to tropical backwaters, discover curated journeys closer to home.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542553/travelenfield/destinations/ladakh.jpg','Journeys across India'],
  ['International Trips','international-trips','Travel beyond borders','Original international itineraries with clear inclusions and on-trip support.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542552/travelenfield/destinations/bali.jpg','Beyond borders'],
  ['Weekend Trips','weekend-trips','Make the weekend count','Short, high-energy escapes designed around convenient departures.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542554/travelenfield/destinations/manali.jpg','Quick escapes'],
  ['Deals','deals','Current trip deals','Limited-period prices and early-bird benefits on selected departures.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542558/travelenfield/destinations/thailand.jpg','Limited-period benefits'],
  ['Bike Trips','bike-trips','Ride farther. Feel more.','Supported motorcycle journeys through Ladakh and India’s most dramatic open roads.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542549/travelenfield/categories/bike-trips.jpg','Two wheels, one unforgettable road'],
  ['Backpacking Trips','backpacking-trips','Backpacking trips for curious people','Social, immersive routes with thoughtful stays and experienced trip captains.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542557/travelenfield/destinations/spiti.jpg','Travel light, connect deeply'],
  ['Trekking Trips','trekking-trips','Trails worth earning','High-altitude landscapes, expert-led routes and small-group mountain experiences.','https://res.cloudinary.com/dq3typk9u/image/upload/v1786542556/travelenfield/destinations/nepal.jpg','Walk into the wild'],
].map(([name,slug,title,description,image,eyebrow]) => ({name,slug,title,description,image:cdn(image),eyebrow,filters:['destination','budget','duration','date'],faq:categoryFaq(name)}));

export const blogs = [
  {
    title:'Leh Ladakh Backpacking Trip', slug:'best-time-to-visit-ladakh', image:img('ladakh'), category:'Ladakh Travel Guide', author:'TravelEnfield Editorial', readTime:'10 min read', publishedAt:new Date(2026,6,1),
    excerpt:'Choose the right Ladakh season for road trips, clear lake views, local culture and a safer high-altitude itinerary.', seoTitle:'Best Time to Visit Ladakh | Weather, Roads & Travel Tips', seoDescription:'Plan a Ladakh trip with a practical month-by-month guide to weather, road access, acclimatisation, packing and responsible travel.',
    sections:[
      {heading:'The Perfect Season for a Leh Ladakh Backpacking Trip',body:'The best season depends on the kind of journey you want. For a first-time backpacking or road trip, late June to September usually offers the most comfortable balance of open routes, daylight and access to popular valleys. Days can feel pleasantly sunny, while evenings at higher stops are still cold enough for proper layers.\n\nSpring and autumn can reward travellers with quieter roads and beautiful light, but access can change quickly. Winter Ladakh is a specialist experience: it requires stronger cold-weather preparation, flexible dates and reliable local support rather than a standard sightseeing plan.'},
      {heading:'What to Explore in Ladakh',body:'Start in Leh and give yourself enough time to acclimatise before heading higher. The city is a good base for monasteries, local food and a gentle first day. Once rested, you can build outward toward Nubra Valley, Pangong Lake, high passes and smaller villages according to the road conditions and your pace.\n\nThe most rewarding itinerary is not the one with the most pins. It is the one that gives you time to adjust to altitude, watch the landscape change and experience Ladakhi culture respectfully.'},
      {heading:'The Chadar Trek',body:'The Chadar Trek is a winter-only expedition on the frozen Zanskar River and should be treated very differently from a summer backpacking trip. Ice quality, weather, route access and safety protocols decide whether it can operate. It is suitable only with an experienced operator, the required fitness preparation and a flexible approach to changing conditions.\n\nIf you are considering it, prioritise route briefings, good footwear, insulated sleep systems and a support team that will turn back when conditions demand it. A safe decision is always more valuable than completing a planned route.'},
      {heading:'The Markha Valley Trek',body:'Markha Valley is a classic Ladakh trek for travellers who want village life, open mountain terrain and a multi-day walking route. It is still a serious high-altitude experience, so build in acclimatisation at Leh and choose a route appropriate for your fitness and time.\n\nThe joy of the trail lies in the rhythm: walking between villages, respecting homestay spaces, taking in monastery landscapes and allowing the guide to set a safe pace. Carry only what you need each day and keep extra energy for the final climbs.'},
      {heading:'The Nubra Valley Trek',body:'Nubra Valley is often explored as part of a road-based Ladakh itinerary, but its walking routes and village trails can add a quieter perspective to the journey. The valleys, dunes and high mountain approaches feel very different from Leh, which makes a slower stay rewarding.\n\nRoads and camps are weather-led, so travel with local guidance and avoid compressing long drives, hikes and altitude gain into one day. Build your plan around safe transfers, a comfortable overnight stop and time to absorb the landscape.'},
      {heading:'The Stok Kangri Trek',body:'Stok Kangri is an advanced mountaineering objective, not a casual first trek. Conditions, permissions and operational access can change, and an attempt should only be considered with technical preparation, current local guidance and an experienced high-altitude team.\n\nFor many backpackers, a lower-altitude Ladakh trek or village walk is a much better introduction. Choose an objective that matches your experience rather than one chosen only for its altitude.'},
      {heading:'What to Bring for a Ladakh Backpacking Trip',body:'A reliable layering system is more useful than one heavy jacket. Start with breathable base layers, add an insulating mid-layer and finish with a windproof or waterproof outer shell. Days can be bright and warm in the sun, yet wind and evening temperatures change the feel quickly.\n\nSturdy walking shoes, sunglasses, sunscreen, a water bottle, personal medication, a compact first-aid kit, power bank and copies of important documents should stay accessible. Pack light enough to move comfortably, but never compromise on warmth, hydration or footwear.',bullets:['Use footwear with grip and ankle support for uneven trails.','Keep a headlamp, spare charging option and reusable bottle in your daypack.','Carry cash for remote areas where network access and card payments can be unreliable.']},
      {heading:'Key Advice for Backpacking in Ladakh',body:'Acclimatisation comes before adventure. Keep your first day in Leh easy, stay hydrated, avoid alcohol initially and let your trip captain or local guide know about any unusual symptoms. Do not try to make up for lost time by rushing to a higher altitude.\n\nPlan with buffers for weather and road changes, respect local customs in monasteries and villages, and carry every piece of waste back from remote stops. The best Ladakh backpacking trip feels prepared, patient and connected to the place rather than hurried through it.',bullets:['Check current permits, weather and road information close to departure.','Book a responsible operator for trekking, camping or motorcycle routes.','Never pressure a driver or guide to continue when local safety advice says otherwise.']},
      {heading:'Conclusion',body:'Ladakh is most rewarding when your plan makes room for the mountains to set the pace. Choose the season and route that suit your experience, carry the right layers, arrive ready to acclimatise and keep safety ahead of a fixed checklist.\n\nWith those foundations in place, a Leh Ladakh backpacking trip becomes more than a collection of beautiful views: it becomes a well-supported journey through one of India’s most remarkable high-altitude regions.'}
    ]
  },
  {
    title:'Places to Visit in Spiti Valley: A Slow Road-Trip Guide', slug:'places-to-visit-in-spiti', image:img('spiti'), category:'Spiti Valley Guide', author:'TravelEnfield Editorial', readTime:'10 min read', publishedAt:new Date(2026,6,8),
    excerpt:'A thoughtful first route through Spiti’s monasteries, villages, high passes and wide-open Himalayan landscapes.', seoTitle:'Places to Visit in Spiti Valley | Route, Villages & Travel Tips', seoDescription:'Discover the best places to visit in Spiti Valley, including Kaza, Key Monastery, Langza and Chandratal, plus essential route planning advice.',
    sections:[
      {heading:'Plan Spiti as a journey, not a checklist',body:'Spiti rewards a slower itinerary. Distances on a map can look small, but high-altitude roads, photo stops and changing weather turn each transfer into a meaningful part of the trip. Most first visits work best as a gradual circuit through Shimla and Kinnaur into Kaza, with a return via Manali only when the route is open.\n\nGive your body time to adjust and give each village more than a rushed stop. The landscape is dramatic, but the lived-in character of Spiti—its homes, monasteries and quiet evenings—is what makes the route stay with you.'},
      {heading:'Kaza and Key Monastery',body:'Kaza is the practical base for fuel, cafés, supplies and nearby explorations. It is a useful place to pause rather than a town to rush through. A short drive away, Key Monastery sits above the valley with layered white buildings and broad views of the Spiti River.\n\nVisit respectfully, keep your voice low in prayer spaces and ask before photographing residents or monks. Morning light and a little patience make the experience far better than arriving in a crowded midday rush.'},
      {heading:'Langza, Hikkim and Komic',body:'These high villages are often grouped into one excursion, yet each deserves its own pace. Langza is known for fossil-rich terrain and a vast valley view, Hikkim is a memorable high-altitude postal stop, and Komic feels wonderfully remote. The highlight is not collecting a location pin; it is noticing how daily life adapts to altitude, wind and long winters.\n\nCarry cash, refill water before leaving Kaza and do not expect city-style services. A local homestay meal or conversation can add more value than one more hurried photograph.'},
      {heading:'Pin Valley and Chandratal',body:'Pin Valley introduces a quieter, wilder side of the district, with stark slopes and small settlements. Chandratal, when access and local rules permit, is a high-altitude lake experience that must be approached responsibly. Weather, campsite rules and road conditions decide what is realistic on the day.\n\nAvoid leaving litter, stay on designated paths and do not treat fragile shorelines as a party spot. In mountain regions, the most memorable travel is often the least intrusive.'},
      {heading:'Road safety and what to carry',body:'Spiti roads are weather-led and plans should be flexible. Begin transfers early, keep warm layers in the vehicle and do not rely on mobile data in remote sections. A reusable bottle, personal medication, power bank, cash and basic snacks are practical rather than optional.\n\nIf you are new to high altitude, choose a route that ascends gradually and travel with reliable local support. The best Spiti trip is one that feels prepared, not over-scheduled.',bullets:['Build at least one buffer day into a longer circuit.','Use refillable bottles and carry all packaging back to a proper bin.','Follow driver and local administration guidance over an ambitious itinerary.']}
    ]
  },
  {
    title:'Things to Do in Bali: A Balanced First-Time Itinerary', slug:'things-to-do-in-bali', image:img('bali'), category:'Bali Travel Guide', author:'TravelEnfield Editorial', readTime:'8 min read', publishedAt:new Date(2026,6,15),
    excerpt:'Build a Bali holiday around temples, coastline, culture and unplanned island time instead of rushing every landmark.', seoTitle:'Things to Do in Bali | First-Time Itinerary, Culture & Travel Tips', seoDescription:'Plan an enjoyable Bali holiday with practical ideas for Ubud, temples, beaches, island days, packing and respectful travel.',
    sections:[
      {heading:'Choose fewer bases and enjoy Bali more',body:'Bali looks compact on a map, but traffic can make a cross-island day far longer than expected. A well-paced first trip normally uses one or two bases: Ubud for rice terraces, food and culture, then a coastal area for sunsets, beach time and easy evenings. This leaves space to actually enjoy a café, pool or local market rather than checking in and out every day.\n\nBefore booking, decide whether you want creative neighbourhoods, surf beaches, quiet coves or a more social base. Your hotel location will shape the holiday more than a long list of attractions.'},
      {heading:'Ubud, rice terraces and temple etiquette',body:'Ubud is a natural starting point for art, wellness, craft workshops and lush inland scenery. Go early for a rice-terrace walk, then keep the rest of the day deliberately light. Temples are living places of worship, not backdrops: wear appropriate clothing, follow local instructions and never step into restricted areas for a photo.\n\nA simple food class, a guided village walk or time at a small local warung can provide more genuine context than moving between viral locations.'},
      {heading:'Coast days, cliffs and island outings',body:'The coast can be shaped around your energy. Uluwatu works well for cliffs and sunset views, Seminyak and Canggu suit dining and a livelier scene, while quieter stretches can be better for rest. Boat trips and Nusa Penida day tours are popular, but early starts, sea conditions and realistic travel times matter.\n\nKeep one open afternoon for the beach or pool. It prevents a beautiful tropical holiday from turning into a commute between viewpoints.'},
      {heading:'Food, markets and local experiences',body:'Bali’s best meals need not be formal. Try regional dishes in family-run warungs, visit an early market with a guide, and ask your host for current recommendations. Bring a refillable bottle where safe water stations are available and prefer locally made keepsakes over disposable souvenirs.\n\nIf you attend a ceremony or enter a community space, dress respectfully and observe before you photograph. Courtesy is part of travelling well.'},
      {heading:'Practical planning before you fly',body:'Check passport validity, entry requirements, insurance and airline baggage rules before departure; these may change. Keep sun protection, a light rain layer, modest temple-covering clothing and reliable footwear in your day bag. Book airport transfers for a smooth first arrival, especially after a late flight.\n\nA balanced Bali itinerary combines one cultural day, one active day and time with no fixed plan. That rhythm gives the island a chance to feel like a holiday rather than a schedule.',bullets:['Use reef-safe sunscreen for water activities.','Leave extra time for airport and inter-area transfers.','Choose licensed guides and operators for boating, diving and adventure activities.']}
    ]
  },
  {
    title:'Meghalaya Travel Guide: Waterfalls, Root Bridges and Responsible Adventure', slug:'meghalaya-travel-guide', image:img('meghalaya'), category:'Meghalaya Travel Guide', author:'TravelEnfield Editorial', readTime:'9 min read', publishedAt:new Date(2026,6,22),
    excerpt:'Plan a deeper Meghalaya journey through Shillong, Cherrapunji, Dawki and village trails with weather-aware travel advice.', seoTitle:'Meghalaya Travel Guide | Best Places, Route & Responsible Travel Tips', seoDescription:'A practical Meghalaya guide for Shillong, Cherrapunji, Dawki and living root bridges, including weather, packing and route-planning advice.',
    sections:[
      {heading:'How to shape a first Meghalaya itinerary',body:'Meghalaya is at its best when you allow weather and road pace to lead. A classic first route begins from Guwahati, pauses in Shillong, then explores Cherrapunji and nearby villages before heading toward Dawki or Mawlynnong. It is tempting to fit every waterfall and viewpoint into a few days, but rain, fog and hill roads reward flexibility.\n\nAim for one major outdoor experience each day. That gives you time to enjoy the changing landscape, eat locally and adjust plans if a trail or river activity is not suitable.'},
      {heading:'Shillong and the road to Sohra',body:'Shillong offers a useful soft landing before the wetter, greener stretches ahead. Spend time in a local café, market or music venue, then set off early toward Sohra, also known as Cherrapunji. The drive itself is part of the experience, with changing cloud cover, viewpoints and smaller settlements along the way.\n\nAvoid treating every roadside stop as a photo sprint. The region is more enjoyable when you leave room for misty weather and unplanned views.'},
      {heading:'Living root bridges and village trails',body:'The living root bridges are remarkable examples of patient ecological knowledge, maintained by communities over generations. Reaching them can involve steep steps and humidity, so good footwear, water and an honest assessment of fitness matter. Follow local guidance, stay on marked paths and do not climb or hang from the roots.\n\nA local guide can add important context about village customs, trail conditions and why these structures need careful visitor behaviour.'},
      {heading:'Dawki, clear rivers and changing conditions',body:'The Umngot River around Dawki is known for clear-water views, especially in calmer conditions. Visibility is never guaranteed: rainfall and current weather determine how the river looks and which activities are appropriate. Early-morning visits are usually more peaceful, but safety instructions always come before a perfect photograph.\n\nUse licensed operators, wear required safety equipment and avoid leaving food wrappers or plastic near riverbanks.'},
      {heading:'Rain-ready packing and respectful travel',body:'A rain jacket, quick-dry layers, grippy shoes, a dry bag and insect protection are useful in Meghalaya for much of the year. Carry cash for smaller villages, download key information offline and keep transfer days realistic.\n\nChoose locally owned stays and guides where possible, keep noise low in village spaces and carry your waste out of natural areas. These choices help protect the landscapes that make Meghalaya special.',bullets:['Keep a weather buffer rather than booking every hour of the day.','Use shoes with traction for wet steps and uneven trails.','Ask before photographing people, homes or places of worship.']}
    ]
  }
];

export const pageData = [
  ['about-us','About TravelEnfield','Our story','Trips that feel unforgettable, not complicated.','We design transparent, social and well-supported journeys for modern Indian travellers.'],
  ['contact-us','Contact TravelEnfield','Let’s plan your journey','Talk to a real travel expert.','Call, WhatsApp or send an enquiry and our team will help you choose the right trip.'],
  ['reviews','Reviews & Community','Traveller stories','Real journeys. Real connections.','Our community is built around safe, memorable trips and the friendships created along the way.'],
  ['faq','Frequently Asked Questions','Need help?','Clear answers before you book.','Find information about payments, departures, cancellations, stays and trip support.'],
  ['privacy-policy','Privacy Policy','Legal','How we handle your information.','We collect only the information needed to operate enquiries, bookings and account services responsibly.'],
  ['terms-and-conditions','Terms and Conditions','Legal','Terms for using TravelEnfield.','These terms explain booking responsibilities, payments, trip operations and acceptable website use.'],
  ['cancellation-policy','Cancellation Policy','Legal','Flexible, clearly explained cancellation terms.','Refund and rescheduling eligibility depends on the trip type and notice period.'],
].map(([slug,title,eyebrow,intro,body]) => ({slug,title,eyebrow,intro,sections:[{heading:'Overview',body},{heading:'Need more information?',body:'Contact TravelEnfield before confirming a booking if any part of a package or policy is unclear.'}]}));

async function seedDatabase() {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/travelenfield');
  await Promise.all([Destination.deleteMany({}),Trip.deleteMany({}),Category.deleteMany({}),Blog.deleteMany({}),Page.deleteMany({}),Hotel.deleteMany({})]);
  await Promise.all([Destination.insertMany(destinations),Trip.insertMany(trips),Category.insertMany(categoryData),Blog.insertMany(blogs),Page.insertMany(pageData),Hotel.insertMany(hotels)]);
  console.log(`Seeded ${destinations.length} destinations, ${trips.length} trips, ${categoryData.length} categories, ${blogs.length} blogs, ${pageData.length} pages and ${hotels.length} hotels.`);
  await mongoose.disconnect();
}

const invokedDirectly = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) seedDatabase().catch(error => {
  console.error('Database seed failed:', error);
  process.exitCode = 1;
});
